smart-village-solutions/smart-village-app-app

src/components/Button.js
src/components/index.js
src/navigation/AppStackNavigator.js
src/screens/HtmlScreen.js
src/screens/WebScreen.js
src/screens/index.js

- created new route `Web` for navigating to a `WebView`
- created a `WebScreen` for rendering a `WebView` with loading indicator
- updated the `HtmlScreen` with adding a `Button` if a
`webUrl` is given in navigation params
- created a `Button` component based on React Native Elements
Button: https://react-native-training.github.io/react-native-elements/docs/button.html
resolves #2
---
---
ℹ️merge https://github.com/ikuseiGmbH/smart-village-app-app/pull/13 first and change the base of this PR to master

Implement WebView component for external services

---

.gitignore
README.md
docs/AUTH.md
docs/INDEX.md
package.json
src/auth.js
src/config/index.js
src/config/secrets.temp
src/index.js
src/queries/index.js
src/screens/DetailScreen.js
src/screens/HtmlScreen.js
src/screens/IndexScreen.js
yarn.lock

- https://github.com/doorkeeper-gem/doorkeeper/wiki/Client-Credentials-flow
- using .gitignore secrets file with credentials
- info in /docs/AUTH.md
- added authentication on startup before creating the apollo client
- the access token is needed for creating it
- save it in SecureStore https://docs.expo.io/versions/v32.0.0/sdk/securestore/
- added authentication refresh on screen component mounts
- changed Component to PureComponent in screens because they are stateless
- updated usage of `getQuery` where missing
- added more docs

Implement OAuth2 per client credentials flow

---

package.json
src/helpers/momentHelper.js
src/screens/HomeScreen.js
src/screens/IndexScreen.js
yarn.lock

Show only upcoming events
- added check for upcoming event based on the `listDate` of a
event record
- used `moment` helper for determining, if an event is in the past
- used lodash `filter` to filter data and reject past events on HomeScreen
and IndexScreen
- still render only the next 3 events on the HomeScreen
- used lodash `take` for it
- now we request always all events and filter afterwards
- this could lead to worse performance than before
**Today: 09.07.2019**

Show only upcoming events

---

src/helpers/shareHelper.js
src/screens/IndexScreen.js

- fixed query parameter in IndexScreen for share messages
- needs to be singular for a certain item and not the `query` variable
available, because that is plural
- updated contents of share messages
- we cannot use the description for pois and tours anymore, because
they are HTML and not plain text

Fix and update share messages

---

src/components/Logo.js
src/components/Wrapper.js
src/components/screens/EventRecord.js
src/components/screens/NewsItem.js
src/helpers/imageHelper.js
src/index.js
src/queries/eventRecords.js
src/queries/newsItems.js
src/queries/pointsOfInterestAndTours.js
src/screens/HomeScreen.js
src/screens/IndexScreen.js

- data for news item can have multiple content blocks forming a longer story
- each content block is now a different section in a whole story
- a news item renders a main image(carousel) and a main title from the first content block
- that is why that data is ignored inside of the story sections for the first index in the iteration
- the order of elements inside of a sections in the story is:
- title
- intro
- image(carousel)
- text
- audio/video
- added a new wrapper with only horizontal padding to separate each section from the other without vertical space
- removed bottom margin from the logo as the body text now comes inside of the story sections
- added necessary keys in the news items queries
Render audio and video as html contents (iframe) in a WebView
- there were problems playing …

Update news item rendering to consider stories

---

src/components/screens/NewsItem.js
src/queries/newsItems.js
src/screens/DetailScreen.js
src/screens/WebScreen.js

Add ability to restrict news according to settings
- added new settings to newsItems queries
- added logics to display only intro and a button if settings say
- otherwise still render the body content
- button links to the source url
Open source of news in WebView instead of linking external
- added navigation to WebScreen to open source url links in WebView
instead of linking to external browser
- added navigation prop to NewsItem
- needed to navigate
Set mediaPlaybackRequiresUserAction prop for WebView
- fixed problem with opening videos automatically after finished loading
in WebView

Update mobile app to restrict news if desired and setup per main server

---

package.json
yarn.lock

Bumps [babel-eslint](https://github.com/babel/babel-eslint) from 10.0.2 10.1.0
- [Release notes](https://github.com/babel/babel-eslint/releases)
- [Commits](https://github.com/babel/babel-eslint/compare/v10.0.2...v10.1.0)
Bumps [eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react) from 7.14.3 to 7.20.0
- [Release notes](https://github.com/yannickcr/eslint-plugin-react/releases)
- [Changelog](https://github.com/yannickcr/eslint-plugin-react/blob/master/CHANGELOG.md)
- [Commits](https://github.com/yannickcr/eslint-plugin-react/compare/v7.14.3...v7.20.0)
Bumps [eslint-plugin-react-native](https://github.com/intellicode/eslint-plugin-react-native) from 3.7.0 to 3.8.1
- [Release notes](https://github.com/Intellicode/eslint-plugin-react-native/releases)
- …

Bump dev dependencies

---

package.json
yarn.lock

This version of React Navigation is no longer supported. Please upgrade to 4.x. See https://reactnavigation.org/docs/en/4.x/upgrading-from-3.x.html for instructions.
- added required package `react-native-screens` in version 2.7.0
Bumps [react-navigation](https://github.com/react-navigation/react-navigation/tree/3.x) from 3.11.1 to 3.13.0
- [Release notes](https://github.com/react-navigation/react-navigation/releases)
- [Commits](https://github.com/react-navigation/react-navigation/compare/3.11.1...v3.13.0)

Bump react-navigation from 3.11.1 to 3.13.0

---

src/auth.js
src/index.js
src/screens/HomeScreen.js

- currently the `auth()` method for retrieving a new
access token is called when components did mount
with requesting the server without condition
- this results in a unnecessary amount of request
- fetching an access token also returns the information
about the time when a token expires
-- this is saved now to the SecureStore in addition to the token
- added a method for checking the validity of the
access token with the expire date, so that new tokens
will be requested only if the old one has expired
Call auth method on did mount of HomeScreen
- we call the method in every component that uses queries,
but it was missing in HomeScreen
Add error catching on first query
- when loading the app, the first query can make
the app crash if something went wrong or if
the acces token for the …

Add check for validity of access token

---

src/screens/HomeScreen.js

- added fix boolean constants that decides rendering
of the main sections on the HomeScreen
-- default: true
- later there can be more logic around that, with
setting the constants dynamically from queries
for example
Avoid renderings for homeService and homeAbout if query is in loading state
- we do not need a loading indicator for that sections,
because there is no headline pre-rendered as for
the main sections
- the headline is rendered with the data after query
has succeeded

Add constants and conditions for rendering sections on HomeScreen

---

src/screens/HomeScreen.js
src/screens/IndexScreen.js

- the mainserver returns only upcoming event records now
so the additional logic for filtering to upcoming events
in the app is not necessary anymore
- we can use the `limit: 3` variable directly like for news on
the home screen, which returns exactly the next three upcoming
events as wanted
- also for the list of event records in index screen the js logic
in the app is not needed anymore
Resolves #75

refactor(upcoming events): remove js logics

---

app.json

- https://docs.expo.io/guides/configuring-statusbar/#configuring-the-status-bar-while-your-app
- > On iOS, it is not possible in the Expo managed workflow to customize the status bar before the app has loaded, while the splash screen is presented.
- adding the config to app.json allows us to set
the colors on android while splash screen is visible
- available options: https://docs.expo.io/versions/latest/config/app/#androidstatusbar
- after the splash screen the status bar is configured with `<StatusBar>`

feat(android status bar): set explicit colors

---

src/components/screens/NewsItem.js
src/screens/HomeScreen.js

- just 'Nachrichte' will be visible now on header of webView news article
- hardcoded in title params instead of previeus condition
-const title is in use in this file in several places , should not be deleted
- this change have been not tested because of network issues

Update on title header in webView news

---

src/auth.js
src/index.js

- added logic on network error while `auth()` on app
start to retry the authentication with a forced fresh
token request
- if the app fails once with the default logic, the
app tries the request again with requesting a new
auth token
- this can only be done once, otherwise we could
crash in an endless loop of retries
---
This feature makes it possible to switch secrets and change the main server without problems. This was necessary for smooth development.

feat(network error): retry authentication with forcing new token

---

src/screens/AboutScreen.js
src/screens/CompanyScreen.js
src/screens/HomeScreen.js
src/screens/ServiceScreen.js

- added variables from global settings
- depend renderings based on that variables so it is server side configured, which of the main sections are visible and what headline texts are set
- news, points of interests and tours, events
- for the sub sections the headlines can also be set per server config
- if no headline is set, no headline container will be rendered
- service, company, about
Screenshot of server json:
Resolves #68

feat(sections): variable title for sections

---

src/queries/index.js
src/queries/newsItems.js
src/screens/IndexScreen.js

For better backwards compatibility and to avoid conflicts with server versions, a global setting is added for news filter, whether to show in the app or not.
To implement this, the `IndexScreen` needed an update to a functional component and the usage of hooks.

Add global setting to de-/activate for news filter

---

src/screens/HtmlScreen.js

- there can be new data in `subQuery` at a `buttons` key with an array of objects, that contain information for navigation to web links
- extended logic in `openWebScreen` to determine which data to use for navigation
- adjusted existing button to call `openWebScreen` without params, so that always the fallback will be used from the method
- with just passing `openWebScreen` instead of `() => openWebScreen()` there would be automatically bound some params from `onPress`
JSON | Screen
-------|-------

Add processing of a new button key in subQuery at HtmlScreen

---

src/components/CategoryListItem.js
src/components/DropdownSelect.js
src/components/Icon.js
src/components/Link.js
src/components/TabBarIcon.js
src/components/TextListItem.js
src/components/index.js
src/components/screens/InfoCard.js
src/components/screens/OperatingCompanyInfo.js
src/components/screens/Service.js
src/components/screens/TourCard.js
src/navigation/MainTabNavigator.js
src/navigation/defaultStackNavigatorConfig.js
src/screens/CompanyScreen.js
src/screens/DetailScreen.js
src/screens/FormScreen.js
src/screens/HtmlScreen.js
src/screens/IndexScreen.js
src/screens/ServiceScreen.js
src/screens/WebScreen.js

- we are using tow different kind of Icons in our tabBar;
- first two are 'svg' fils saved in the app ( home and service )
- second two are 'Ionicons', which have a small white frame on the bottom on the icon
- that's why they were having some margin that now I remove
- add some marginTop for all tabBar icons in order to have space between icons and top of tabBar
- now icons in tabBar are aligned, and text looks centred
- but still looks a bit off on iPad screen ( info on SVA-92 )
- PropTypes for name and focused were missing
SVA-93
- on changes orientation, tab bar icons get some extra margin to the right
- both (Icon and TabBarIcon) are wrapped in a view which as a landscapeStyle prop
- and just on TabBarIcon component icon size increases a bit
- here there is a bug , on landscape this …

Update icons in tab bar

---

src/components/CardList.js
src/components/CategoryList.js
src/components/TextList.js
src/components/screens/About.js
src/components/screens/Carousel.js
src/components/screens/Service.js
src/screens/AboutScreen.js
src/screens/CompanyScreen.js
src/screens/DetailScreen.js
src/screens/HomeScreen.js
src/screens/HtmlScreen.js
src/screens/IndexScreen.js
src/screens/ServiceScreen.js

- it will be possible to pull to refresh in every screen to update
data without respecting the refresh time logic
- the solution is a combination of https://reactnative.dev/docs/refreshcontrol
with https://www.apollographql.com/docs/react/v2.6/data/queries/#refetching
- added `RefreshControl` in screens to trigger `refetch` of the existing query
- in `IndexScreen` the `refreshControl` is passed down as prop to the actual
component that gets rendered (`TextList`, `CardList`, `CategoryList`)
- in `HomeScreen` there are multiple queries. for refetching data on the home screen
we need to re-render the whole screen, in order to re-run every existing query.
there is no solution to call the Apollo `refetch` for every `Query` component.
we simulate state change of `refreshing` with setting it to …

feat(pull to refresh): add refetching in every screen

---

src/NetworkProvider.js
src/index.js

- removed `NetworkContext` to eliminate the behavior of reloading
the whole app container when network connectivity changes
- changed usage to get network information to `NetInfo.fetch()`,
which get called in a loop until main server reachability is
set

feat(NetInfo): refactor usage on app load

---

src/components/screens/About.js
src/components/screens/Carousel.js
src/components/screens/Service.js
src/helpers/shareHelper.js
src/index.js
src/queries/index.js
src/queries/types.js
src/screens/AboutScreen.js
src/screens/CompanyScreen.js
src/screens/DetailScreen.js
src/screens/FormScreen.js
src/screens/HomeScreen.js
src/screens/IndexScreen.js
src/screens/ServiceScreen.js

- created constants for all available query types, which are
used everywhere now instead of hardcoded strings, because
we lost the overview
refactor: remove duplication in navigation calls on HomeScreen
- created constants object with index navigation values for
navigating to categories, event records and news items

feat(query types): created constants with all types

---

src/screens/AboutScreen.js
src/screens/CompanyScreen.js
src/screens/DetailScreen.js
src/screens/HtmlScreen.js
src/screens/IndexScreen.js
src/screens/ServiceScreen.js

Fixed offline behavior for index screens, to show cached data and added a check to not refetch data if offline when using pull to refresh.

Refetch should not be triggered when offline

---

src/screens/HtmlScreen.js

- removed ` && !!subQuery.webUrl` as this does not work
for screen, where the navigation goes to other routes than `Web`

fix: revert additional check in HtmlScreen

---

src/components/Button.js

- implemented OrientationContext , which knows when device is on portrait or landscape mode
- buttonStyle condition , when on landscape mode button is on 60% of its width and centred in the screen
- if portrait we don't want to render new style for button so it must be an empty object
SVA-93
feat(button): corrections on style and condition for landscape mode
- buttonStyleLandscape is an appropriate name, more specific
- it is also in alphabetical order
- refactored conditional logic , aim dry code
SVA-93
- now the condition for new style on landscape mode is placed in the button container
- using alignSelf in order to see the container shrink to the size of its content
- thanks to this article: https://www.skptricks.com/2019/02/react-native-button-width-fit-to-content.html
SVA-93

feat(button): new style on landscape mode

---

src/OrientationProvider.js
src/components/CardList.js
src/components/HtmlView.js
src/components/ImagesCarousel.js
src/components/Wrapper.js
src/components/screens/EventRecord.js
src/components/screens/NewsItem.js
src/components/screens/PointOfInterest.js
src/components/screens/Tour.js
src/screens/DetailScreen.js
src/screens/FormScreen.js
src/screens/HtmlScreen.js

- created a ( possibly temporary ) style component to wrap around detail and html screens if on landscape mode
- WrapperLandscape is increasing space left and right in order to center the text to improve rideability
- it's applied on Detail and HTML screens with necessary condition
- if device is on landscape then content of this screens is wrapped
SVA-93
- on OrientationProvider just a small grammar correction on comment
- WrapperLandscape it's updated with percentage to fit bigger screens as well
- WrapperWithOrientation is a function component that carries WrapperLandscape and pass it to its children
- this happens when orientation is landscape , which reach its children per prop
- wrapping detail and html screens with new component WrapperWithOrientation instead of WrapperLandscape
- …

feat(detail and html screens): condition for landscape mode

---

src/components/CardList.js
src/components/CardListItem.js
src/components/SafeAreaViewFlex.js
src/screens/IndexScreen.js

- passing orientation as prop
- created a condition for new style when orientation is triggered
SVA-93
- in Card List deleted a comment , there is not the place where to make changes
- WrapperWithOrientation is now implemented conditionally around cart item
- in addition imageWidth it should be on 50% when orientation is on landscape
- attempt to implement OrientationContext based on ImagesCarousel
- getting a red screen about an invalid hooks call
SVA-93
- refactored CardListItem into a functional component
- moved WrapperWithOrientation behind card component
- that's where should stay in order to wrap the all card and made changes when orientation changes
- temporary deletion of horizontal logic for preview card list (which is visible on home screen only)
-  it has been deleted due a …

feat(cardListitem): new style condition for landscape mode

---

src/components/ServiceBox.js
src/components/screens/Service.js
src/screens/CompanyScreen.js
src/screens/ServiceScreen.js

- removed `align-items: center` to always be full width inside the flex area
- added conditions for landscape mode and based on dimensions
with re-rendering on orientation change

feat(service boxes): add sizing and positioning based on orientation

---

src/components/Text.js

- regular text prop small line height 16 was not enough that's way text was cut in openingTimecard
- increased just a bit it solves with out breaking anything else
SVA-104

bug(text): increase line height

---

src/config/texts.js
src/queries/newsItems.js
src/screens/HomeScreen.js

feat(multiple news sections): dynamic news on home screen
- refactored news on home screen
- removed hard coded news section and texts
- added map over multiple news categories to
create multiple news sections
- `categoriesNews` array needs to be added on the
main server in `sections` with objects containing
a `categoryId` to filter, `categoryTitle` to show as
headlines, `categoryTitleDetail` to show in header
on details screens and `categoryButton` to show as
button text
SVA-32
feat(news filter): consider category for data providers
- when filtered news on category, the data provider selection
on news index also needs to take care of that
- added parameter for category id for data provider query
in news items
- added TODOs for parts, where the main server is not ready yet
- …

separation of news on category

---

src/components/ListHeader.js
src/config/texts.js
src/queries/eventRecords.js
src/queries/index.js
src/queries/newsItems.js
src/screens/IndexScreen.js

- updated `ListHeader` to be more generic
- now different data can be processed, not only `dataProviders`
- added logics based on query
- updated event record queries
- added `GET_EVENT_RECORDS_AND_CATEGORIES` to event record
queries to request categories together with event records
- query is used on initial query in `IndexScreen` for event records
- placed TODOs that are necessary after main server PR gets merged:
https://github.com/ikuseiGmbH/smart-village-app-mainserver/pull/159
- removed get-method for list header component, as there is no condition,
because the conditional stuff happens inside of the component
SVA-58

feat(event filter): add category filter on index screen

---

App.js
src/components/ToggleListItem.js
src/config/consts.js
src/config/texts.js
src/helpers/matomoHelper.js
src/hooks/matomoHooks.js
src/screens/HomeScreen.js
src/screens/SettingsScreen.js

This PR is a first version of combining Matomo analytics with the settings screen.
When toggling the switch for Matomo an Alert is asking the user and pointing out, that an app restart is necessary for changes to take effect.
For testing locally, the `__DEV__` const needs to be removed or inverted to `!__DEV__` in App.js.
activation alert | deactivation alert
-------------- | --------------
Also added tracking of navigation to the settings screen.

combine settings and matomo

---

src/components/Image.js

Added source and setUri to dependencies of the useEffect within the `Image` component
This change causes the `Image` component to rerender as intended

Fix: dependencies of useEffect in Image component

---

src/screens/DetailScreen.js

- if IOS device render font icon otherwise svg icon
- using same style logic as the icon setting
#120
Current status of header in detail screen:

fix(detail screen): share icon for ios 

---

src/components/Radiobutton.js
src/screens/HomeScreen.js

- for better readability
- if using Platform we need to import an additional object from react native
- which we don't need if we use just our device
- this makes even more sense in Radiobutton where device is used multiple times in the file
(!) this change is not tested on android

feat(icon): dried out the logic for different devices

---

src/hooks/matomoHooks.js
yarn.lock

- updated matomo-tracker-react-native to be able to use `MatomoContext`
- added condition to not show the first matomo alert on startup if matomo is disabled generally

fix(matomo): no alert on startup if disabled

---

src/index.js

- setup of global settings was buggy when there is nothing stored on the device yet
- added lodashs `_isEmpty` because check for empty objects were not implemented correctly

fix(startup): add checks for empty objects

---

src/queries/pointsOfInterestAndTours.js

- this query is used in the home screen, where no fetch more is used so we do not need the offset option

chore(queries): remove unnecessary offset option

---

src/components/screens/EventRecord.js
src/components/screens/NewsItem.js
src/components/screens/Tour.js
src/config/consts.js
src/config/texts.js
src/helpers/index.js
src/helpers/queryDataParser.js
src/helpers/queryHelper.js
src/screens/HomeScreen.js

previously we always used `QUERY_TYPES.NEWS_ITEM` for the navigation triggered by a push notification.
This can cause errors if push notifications for other item types are sent out.

fix(push notification): navigation on interaction

---

src/components/screens/About.js
src/components/screens/HomeCarousel.js
src/components/screens/Service.js
src/index.js
src/screens/AboutScreen.js
src/screens/CompanyScreen.js
src/screens/ServiceScreen.js

- added try/catch for every `JSON.parse` of random public json content from main server, which can have format issues, to ensure that the app does not crash
- used optional chaining to reduce possibilities of types for the returned value
- if one of `data` or `data.publicJsonFile` or `data.publicJsonFile.content` is undefined, `JSON.parse` errors with a SyntaxError as well and we land in the catch -> main variable stays `[]`
SVA-133

fix(parsing public json content): catch errors on JSON.parse

---

src/components/map/LocationOverview.tsx
src/components/screens/PointOfInterest.js

- linting changes in LocationOverview.tsx
- hide the map for pois in offline mode, to prevent rendering a white rectangle

fix(map): hide POI map in offline

---

src/components/Image.js
src/components/ImagesCarousel.js
src/components/map/WebViewMap.tsx
src/components/screens/HomeCarousel.js
src/config/consts.js
src/helpers/imageHelper.js
src/index.js

refactor(image aspect ratio): move default aspect ratio to consts
- changed the ratio to 2:1, because 360:180 is the same as 2:1
- having the image aspect ratio in a central place, we can edit the value on one place, instead of searching for the method
feat(image aspect ratio): set IMAGE_ASPECT_RATIO with value from global settings
- added setter for `IMAGE_ASPECT_RATIO` in src/index.js if `imageAspectRatio` is present in global settings
- added method for parsing and checking the value with returning the defaults, if something is not expected
- added comment in `consts`, hinting that the value can differ
- moved reading the value from `consts` into `imageHeight` to get the correct updated value when calling the method
feat(image aspect ratio): add alternative for home carousel
- added …

customizable image component format

---

package.json
src/components/CardListItem.js
src/components/Image.js
src/components/Logo.js
src/components/screens/Service.js
src/components/weather/DailyWeather.tsx
src/components/weather/HourlyWeather.tsx
src/components/widgets/WeatherWidget.tsx
src/screens/CompanyScreen.js
src/screens/ServiceScreen.js
yarn.lock

- problem: https://github.com/react-native-elements/react-native-elements/issues/2000
- latest v1 is 1.2.7: https://github.com/react-native-elements/react-native-elements/blob/next/CHANGELOG.md#v127
- when updating like this, we needed to make changes where using `Image`
- not all styles will be applied anymore, you need to change styles to props
- we had the need of moving `resizeMode` and `borderRadius` from inside of style prop
to be props itself
- default for `resizeMode` was `cover` before in the code of react-native-elements,
as it is the default for React Native `Image` component https://reactnative.dev/docs/image#resizemode
- refactored all occurrences
SVA-141

fix(image loading spinner android): update react-native-elements from 1.1.0 to 1.2.7

---

src/components/BB-BUS/Authority.js
src/components/CardList.js
src/components/CardListItem.js
src/components/HtmlView.js
src/components/Image.js
src/components/ImagesCarousel.js
src/components/TextListItem.js
src/components/map/WebViewMap.tsx
src/components/screens/EventRecord.js
src/components/screens/NewsItem.js
src/components/screens/PointOfInterest.js
src/components/screens/Tour.js
src/config/styles/html.js
src/helpers/imageHelper.js
src/screens/BB-BUS/DetailScreen.js
src/screens/ConstructionSiteDetailScreen.js
src/screens/HtmlScreen.js

- image sizes depend on orientation of the device,
therefore we already had a method to set correct widths
- this logics are now placed in `imageWidth` to be used elsewhere
if necessary
- with updated react-native-elements image component the `alignSelf` was
missing in some cases
- this needs to be a `containerStyle` with the newer version
- adjusted every usage of `Image`
- the map also needed adjustments concerning height & width
---
i hope i reached every code.
i think it behaves again like expected and in versions before 1.5.1.
---
refactor(image width): use min of dimensions height and width
- we could simplify the logic for correct image width with using the min value of dimensions height and width
- this made it possible to get rid of `orientation` and `dimensions` props in several …

fix(images): correct rendering of images

---

package.json
src/index.js
yarn.lock

forcefully upgraded react-native-safe-area-view to support iPhone 12
Before
After
SVA-145

fix(safe area insets): upgrade safe area view

---

src/components/screens/InfoCard.js
src/queries/eventRecords.js
src/queries/pointsOfInterest.js
src/queries/pointsOfInterestAndTours.js
src/queries/tours.js

feat(InfoCard): merge all available web urls to render
- added attributes to queries to request all necessary data
- created a method to merge all available web urls to render in `InfoCard` for events, points of interest and tours
feat(web urls): filter descriptions starting with "url"
- added a check for descriptions starting with "url" because we do not want to present web urls behind an "url" or "urlInformation" or "urlVideo" or "urlVideoPreview"
- in that case, we render the just the `url` instead of the `description`
SVA-146 (_please see comment in the ticket for screenshots_)

Render missing web urls

---

src/components/CategoryList.js
src/config/texts.js
src/screens/HomeScreen.js

- switched the sections for the list on the category list screen, to have points of interest first and tours last
- renamed every "Touren und Orte" to "Orte und Touren" because we show them in that order on the category screen now

Switch rendering of tours and points of interest

---

src/components/TMB/Notice.js
src/components/screens/EventRecord.js
src/components/screens/PointOfInterest.js
src/components/screens/Tour.js
src/config/styles/html.js
src/config/texts.js

- created new component `TMBNotice` that renders a text at the bottom of events, points of interest and tours, if the data provider is TMB
- the check for the data provider can only be done on the string `name` because the corresponding `id` can differ across apps
- added the new component in detail components
- added the notice as html text to `texts`
- added a html style for emphasized texts to show the notice in italic style
SVA-118
|Event iOS|Event Android|
|---------|--------------|
|![Simulator Screen Shot - iPhone 11 Pro Max - 2021-01-27 at 13 21 16](https://user-images.githubusercontent.com/1942953/105992798-d12a1b00-60a5-11eb-841b-96fa1b79d682.png)|![Screenshot_20210127-133245](https://user-images.githubusercontent.com/1942953/105992681-b5bf1000-60a5-11eb-9493-a953abd62028.png)| …

Add a notice at the bottom of TMB contents

---

src/components/ImagesCarousel.js
src/components/ImagesCarouselItem.js
src/components/index.js
src/screens/HomeScreen.js

chore(home carousel): add pull to refresh
- add missing `refreshing` prop from home screen to force refetch of data
refactor(images carousel): optimize code for carousel items
- created `ImagesCarouselItem` from `TouchableImage`, which returns a simple image or a touchable image that can navigate to a given `routeName` with `params`
- reduced the conditions for return of `renderItem` in `ImagesCarousel` with the result, that there is always a return of `ImagesCarouselItem` whether with extra query or not
- added optional chaining for the remained condition to shorten the checks
- reduced the conditions in `renderItem` for `itemWidth` with using the  new `imageWidth()` helper method, that is taking care of the correct  size
- added `useCallback` for `renderItem` in `ImagesCarousel` to …

Optimize images carousel

---

src/components/Image.js
src/components/ImageMessage.js
src/components/ImagesCarousel.js
src/components/ImagesCarouselItem.js

feat(images carousel): render an items message onto an image
- created `ImageMessage` for rendering a `message` in a `HtmlView` absolutely positioned on the bottom left with some spacing to the container edge
- added `message` prop to `ImagesCarouselItem` to pass through to `Image`
- wrapped `ImagesCarouselItem` with `memo` to reduce re-renderings
- tested it with console logs, that were decreased
- added `message` prop to `Image` and render `ImageMessage` if `message` is present
SVA-81
---
1. `"message": "<h1 style=\"color: #ffffff; margin-bottom: 0\">nur Januar</h1><h2 style=\"color: #ffffff\">ganztägig</h2>"`
2. `"message": "<div style=\"background-color: rgba(20, 20, 20, 0.4); padding: 4px\"><p style=\"background-color: transparent; margin-bottom: 0px; color: #ffffff\">immer, 10:00 - …

Show message on slider item

---

babel.config.js
package.json
src/components/ImagesCarousel.js
src/components/screens/HomeCarousel.js
src/helpers/momentHelper.js
yarn.lock

- created date and time helper methods to identify items to show based on their `dates` object with or without given date and/or time periods
- used `moment` for easier working with date and time values
- added a filter for `carouselData` in `ImagesCarousel` for present items and items with active date/time periods
- this made the check for a present `item` in `renderItem` superfluous
- renamed `carouselImages` to `homeCarouselData` in `HomeCarousel`, because it is more on point as the data is not only about images anymore
SVA-81
---
Any ideas on optimizing logics or readability of the date and time conditions?

Show just in time slider items

---

src/components/Icon.js
src/screens/BB-BUS/DetailScreen.js
src/screens/BookmarkScreen.js
src/screens/DetailScreen.js

On IOS devices : 
- paddingVertical was apparently unnecessary and created a bug
- without it the bug does not occur and there is no break in all other devices
- added a new prop hitSlop. As the removed paddings hitSlop defines how far a touch event can start away from the view
- resulting in a "smooth touch" experience
#167
Has to be tested on Android devices

fix(share icon and settings icon) removed paddingVertical

---

src/components/screens/PointOfInterest.js

The logo of the data provider is now visible on POIs in the same way as it is for tours.
---
SVA-159

Added logo to POIs

---

src/components/map/LocationOverview.tsx

Took the optional chaining one step further to ensure that their is no longer destructuring of props of undefined values.

fix(location overview): crash at null value

---

src/components/Image.js

- the empty string is evaluated to false
- this caused it to be tried to to be rendered (outside of text component)

fix(image copyrights): crashing on empty string

---

src/queries/eventRecords.js

- when fetching more events in list, the GET_EVENT_RECORDS query is fired
- that query needs to have the same attributes requested, otherwise the data sets cannot match and an error occurs

fix: add missing attributes to query

---

src/components/Text.js

The children prop may be undefined, so the `.isRequired` was unnecessary, while causing issues since we use `RegularText` for spacing in a couple of places.

fix(text): removed required flag from prop

---

src/config/texts.js
src/hooks/PushNotification.ts
src/screens/HomeScreen.js
src/screens/SettingsScreen.js

Some communities do not immediately want to have push notifications enabled. so i added the option to disable it through server settings.
this way the permission popup and the settings should not show, when the server sided settings do explicitly set push notifications to a disabled state.
SVA-185

chore(push notifications): enable disabling through server settings

---

src/screens/DetailScreen.js

- added missing optional chaining for details on detail screen
- this caused a crash with push notifications as details are null

fix(detail screen): crash on push

---

src/components/Image.js

- nested message and imagerights to be inside of the image
- this way the absolute positioning is with respect to the image itself
- previously it was with respect to the container (which was wider in landscape)
Before:
After:

fix(image): message outside of image

---

src/components/Image.js
src/hooks/TimeHooks.ts

- updated the useInterval hook to return a timestamp
- this results in always different return values instead of reused ones after app restart
- added a constant for max interval length (currently 100) for the setInterval call
- bigger values for `ms` will result in the timestamp being updated whenever an interval expires that exceeds the `ms` value. eg for a value of 450 the timestamp will be updated after the 5th interval cycle (5x100 = 500 >= 450)
SVA-207

fix image not displaying up to date image

---

src/hooks/matomoHooks.js

- corrected context to get `isConnected` properly, which is necessary to track screen views
- with the wrong context it was always undefined and with that no tracking was sent for screens using the hook

fix(useMatomoTrackScreenView): correct context for matomo tracking

---

src/components/Offer.js
src/queries/genericItem.js

- added dataprovider logo to generic item query
- updated offer to use SectionHeader component
- removed unnecessary arg from onPress function
- the function was only ever used as onPress, which does not get a string as an argument
SVA-202
before:
after:

chore(offer): replace provider name with logo

---

src/components/oParl/Meeting.tsx
src/config/texts.js
src/screens/OParl/OParlDetailScreen.tsx
src/screens/OParl/OParlOverviewScreen.tsx

- with the removal of the diagonal gradient the touchable had more than one child
- the `TouchableNativeFeedback` requires exactly one child
- reintroduced a height for the wrapping views because the screen seemed very empty with only 3 entries being cramped at the top

fix(oparl android): crash on overview screen

---

src/components/SurveyAnswer.tsx
src/components/Text.js
src/components/index.js
src/config/colors.js
src/config/texts.js
src/hooks/surveyHooks.ts
src/queries/survey.js
src/screens/SurveyDetailScreen.tsx
src/types/Survey.ts

- Overhauled the detail screen
- added unique selection logic to response options 
---
SVA2-11
---

Survey: response options

---

src/components/Results.tsx
src/components/SurveyAnswer.tsx
src/components/index.js
src/config/texts.js
src/helpers/surveyHelper.tsx
src/screens/SurveyDetailScreen.tsx

- added results visualization to details
- added logic to either show the hint or show the results
---
SVA2-20
---

Survey: display results

---

src/queries/OParl/meeting.ts

The missing id for the organizations was causing the cache to malfunction.

fix(oparl): missing id in meeting query

---

src/navigation/AppStackNavigator.js

The default screen title was missing for the detail screen of the construction sites.

fix(construction site): missing default screen title

---

src/navigation/DrawerNavigatorItems.js

the values used as keys for the drawer content items were all undefined.
i replaced them by the titles now, as they should be unique at all times.

fix(drawer content): undefined key values for list

---

src/components/HeaderLeft.tsx

The back navigation header is currently shown on initial tab screens, even if there is no option to navigate back.
This change resolves that issue.

Fix: header left showing on initial screens

---

src/navigation/CustomDrawerContentComponent.js

- the drawer content was overflowing the screen to the bottom
- adding a flex to the safe area view improved the behaviour

fix(drawer content): spilling over to the bottom

---

src/screens/IndexScreen.js

previously the index screen did not update, when changing query variables in the navigation params, as long as the query stayed the same.
the screen will now update properly when the query variables inside of the params change, even if the query remains the same.
SVA-260

fix(index screen): not updating on query variable change

---

package.json
src/components/HtmlView.js
yarn.lock

- the react-native-render-html-table-bridge is outdated and deprecated
- instead added a version of @native-html/table-plugin that is compatible with our version of react-native-render-html
- adjusted some stylings to make it close to how it was before

chore(html table): exchange dependency

---

src/components/screens/NewsItem.js
src/config/navigation/defaultStackConfig.tsx
src/hooks/openWebScreen.ts

feat: passing shareContent as a param 
- in openWebScreen type of shareContent is defined and passed it to params
- in newsItem is defined and passed to openWebScreen
- screenOptionsWithShare containing the share logic, must be the screen option of WebScreen
Share logic is now working just fine in WebScreen newItwms 
https://github.com/ikuseiGmbH/smart-village-app-app/issues/81

 share logic in webScreen

---

src/components/widgets/SurveyWidget.tsx

- the icon was too big, which caused the text to be not in line with other widgets
---
SVA-256
| before | after |
|--|--|
|  ![Simulator Screen Shot - iPhone 12 Pro - 2021-08-25 at 14 18 36](https://user-images.githubusercontent.com/59824597/130789582-0e995362-d402-44f2-997a-a9650923dc59.png)| ![Simulator Screen Shot - iPhone 12 Pro - 2021-08-25 at 14 18 11](https://user-images.githubusercontent.com/59824597/130789590-066ec4ea-04f5-4ee0-880a-90960381095c.png)  |

fix(survey widget): icon being too big

---

App.js
package.json
src/hooks/matomoHooks.js
src/screens/HtmlScreen.js
src/screens/IndexScreen.js
src/screens/WebScreen.js
yarn.lock

- created `userInfo` object from different sources and pass it to matomo tracking
- ⚠️  new matomo-tracker-react-native 0.3.0 is required for this to work!
- PR: https://github.com/donni106/matomo-tracker-react-native/pull/6
- `userInfo` contains app-version, language, screen resolution and an user agent to identify devices more detailed (still anonymously!)
- added a new hook to build this object
- added new hook to async track screen view for a given `name` using the new user info hook
---

feat(matomo): add more device infos to tracking

---

src/screens/DetailScreen.js

There was a require cycle caused by the import of the navigation config in the detail screen through the index file. this resolves the cycle.
@SoleCincis this is an example of the possible cycle creation using index files, that we talked about.

fix(require cycle): navigation config

---

src/screens/LunchScreen.js

During the react navigation upgrade a wrong default was added to the `poiId` of the lunches, resulting in wrong filtering behaviour.
---
SVA-266

fix(lunch): wrong default for poiId

---

src/components/ToggleListItem.js
src/components/wasteCalendar/WasteReminderSettings.tsx

- on android the switch is bigger than visually rendered, there is space integrated so we need to reduce the list item padding to adjust according our overall list items
- values like 3.85 and 3.125 are used to result in paddings that makes the list item heights fit in size
- removed bottom dividers where not necessary, for last items in lists
**waste:**
|ios before|ios after|
|---|---|
|![IMG_0007](https://user-images.githubusercontent.com/1942953/140933785-4f9271fe-b805-420b-a849-f42bbe05e6ba.PNG)|![IMG_0008](https://user-images.githubusercontent.com/1942953/140933827-2dd22312-3de0-4de1-b25b-9f61d01d0ddd.PNG)|
|android before|android after|
|---|---|
|![Screenshot_20211109-141250](https://user-images.githubusercontent.com/1942953/140934089-19974c62-2449-4c15-80f2-b77184254c3e.png)|![Scre …

fix: adjust paddings for list items with switches

---

src/components/Image.js

- previously the image would never load, when the caching failed
- now it tries to fetch the remote directly
---
closes #361

feat(image): set original source on cache fail

---

src/components/infoCard/AddressSection.tsx
src/config/texts.js
src/hooks/openWebScreen.ts

- added option to pass in a specific title for navigation to openWebScreen
- adjusted link text and navigation title for bbnavi
---
SVA-352

BBNavi: text adjustments

---

src/config/consts.js
src/helpers/refreshIntervalHelper.js

- added new const for refresh intervals: NEVER
- if this is selected as the refresh interval the request will always be 'cache-first'
SVA-194

BB Bus: always use cache first

---

src/components/encounter/EncounterWelcome.tsx
src/config/texts.js
src/hooks/index.js
src/hooks/staticContent.ts
src/queries/pointsOfInterest.js
src/screens/EncounterHomeScreen.tsx

- extracted `useStaticContent` hook and made it usable for html and json contents
- added a button to the home screen that leads to a category of pois
- added possibility to have additional info html content on the registered home screen
SVA-352

Encounter: added more info and poi category

---

src/components/map/LocationOverview.tsx
src/screens/IndexScreen.js

- previously we exclusively used the category string, now we also use the id
- we still use a specific selection of query variables to avoid interactions with pagination
SVA-352

fix(location overview): category id not being used

---

src/screens/WebScreen.js

feat: optimize webview scroll behavior
- added `decelerationRate="normal"` to WebScreen to increase speed of scrolling like user are used to from the browser
Closes #300
feat: add custom useragent string to identify app requests on web servers
- auto organized imports
- used scheme string to pass as application name for user agent that can be used on web servers
- first use case is bbnavi, where the user agent will be used
BBNAV-61

WebViews: add props for extended usage

---

App.js
package.json
src/CustomMatomoProvider.js
src/OnboardingManager.tsx
src/SettingsProvider.js
src/components/Text.js
src/config/texts.js
src/helpers/initializationHelper.ts
src/helpers/matomoHelper.js
src/helpers/storageHelper.js
src/hooks/locationHooks.ts
src/hooks/matomoHooks.js
src/hooks/staticContent.ts
src/index.js
src/jsonValidation/appIntroValidator.ts
src/jsonValidation/index.ts
src/navigation/Navigator.tsx
src/pushNotifications/PermissionHandling.ts
src/screens/AppIntroScreen.tsx
src/screens/HomeScreen.js
src/screens/SettingsScreen.js
src/screens/index.js
src/types/AppIntroSlide.ts
src/types/index.ts
yarn.lock

- added new app intro feature
- this app intro will be displayed at app start until completed once
- it can handle the required permission alerts in a more structured way
- the splashscreen and orientation lock handling was moved to the new `OnboardingManager` component
- the handling of system and matomo permissions are now being handled by the new `OnboardingManager` (and if an app intro is configured through that as well)
---
SVA-305
---
- for testing multiple scenarios it is best to not save that the intro was completed at first by commenting out line 58 of the `OnboardingManager`
- by manipulating the conditions in lines 66 and 80 different situations can be simulated

Feature: app intro

---

src/components/CommentSection.tsx
src/components/Results.tsx
src/components/SurveyAnswer.tsx
src/hooks/surveyHooks.ts
src/queries/survey.js
src/screens/SurveyDetailScreen.tsx
src/screens/SurveyOverviewScreen.tsx
src/types/Survey.ts

- added new flag `isMultiLanguage` to `Survey` type
- when used no polish texts are displayed
- adjusted some string constructions
- adjusted `useLanguages` hook to accept `isMultiLanguage`
- slight adjustments to styling of answers where needed
---
SVA-362

Survey: multilanguage optional

---

src/queries/survey.js
src/screens/SurveyDetailScreen.tsx
src/types/Survey.ts

- updated `Survey` type to include `canComment` flag
- hide `CommentSection` if `canComment` flag is not equal to `true`
---
SVA-363

Survey: hide comment section when disabled

---

app.json

despite documentation specifying otherwise, the android permissions for location services need to be added explicitly
SVA-387

fix(location service): missing android permissions

---

src/components/map/LocationOverview.tsx
src/screens/IndexScreen.js

- `LocationOverview` was not passed any prop to handle the state of the opening filter switch while fetching and displaying data internally
- a new prop was added to the `LocationOverview`, which causes the filter for opening times to be applied according to the toggle state
--
SVA-319

Fix: location overview ignoring opening times filter

---

package.json
yarn.lock

- added a new commit to the fork of @digorath to disable hardware accelerration on android to prevent android devices from crashing when navigating to a screen containing a map
SVA-404
This PR updates the dependency to react-native-webview-leaflet to another custom fork which contains a change to disable hardware acceleration on android devices as this causes crashes on some Android devices when showing the map
---
SVA-404
---
Open the app, open the drawer menu, open the app settings.
The app should crash at this point.
*NOTE:* The crash only happens sometimes and only on some devices. We could trigger the crash on two Pixel devices and a Samsung Galaxy S8

fix(leaflet-crash): switch to another fork

---

src/components/ConnectedImagesCarousel.js
src/components/ImagesCarousel.js
src/components/screens/Service.js
src/components/screens/ServiceTiles.js
src/helpers/graphqlHelper.js
src/hooks/staticContent.ts
src/index.js
src/navigation/DrawerNavigator.tsx
src/queries/publicHtmlFiles.js
src/queries/publicJsonFiles.js
src/screens/HtmlScreen.js
src/screens/WasteCollectionScreen.js

- refactored all places where we use static contents to use the `useStaticContent` hook
- added app.json version  to `queryVariables` used in the `useStaticContent` hook
- added app.json version to `queryVariables` of the `globalSettings` query in `src/index.js`
---
SVA-150
---
- added versioned static content to internal development server
- for nested info json (loop) referenced in home about
- for table referenced in navigation
- by changing the version string in app.json you can get different contents

Feature: versioned static contents

---

src/hooks/staticContent.ts
src/index.js
src/queries/BB-BUS/getTop10Ids.js
src/screens/BB-BUS/IndexScreen.js

- removed `JSON.parse`s around public json contents because the
`publicJsonFile` query now returns proper json instead of a string
- therefore we also do not need the try catch bocks for possible
errors with `JSON.parse` anymore
---
ℹ️ i will bring this to int/development demo app directly per `expo publish`

fix: public json contents

---

src/components/Button.js
src/components/Text.js

feat: remove `big` prop for `BoldText`
- the `big` definition is already existing for `RegularText`
thus was a duplication
feat: add smarter button style
- some apps already have a custom button style set
which should be possible right from master, therefore
a `buttonStyle` is added
- for `invert` buttons both styles should be applied,
therefore the condition on `invert` is removed and
the styles passed per array
- sorted styles alphabetically per key for better overview

Update base components

---

src/hooks/listHooks.js

a `bottomDivider` could be passed, which should be used in first case.

fix: respect `item.bottomDivider` in list hooks if present

---

src/components/wasteCalendar/WasteReminderSettings.tsx
src/screens/BB-BUS/DetailScreen.js
src/screens/WasteCollectionScreen.js

* Added feedback footer to the screens of
* BB-Bus/DetailsScreen
* WasteCollectionScreen
* WasteReminderSettingsScreen
SVA-327
It was requested to add the feedback to the waste calendar and bb bus screens.
---
SVA-327
---
Examples of the new feedback placements.
| Portrait | Landscape |
| --------------- | --------------- |
| ![Simulator Screen Shot - iPhone 13 mini - 2022-02-11 at 14 13 22](https://user-images.githubusercontent.com/13070135/153597941-ac06fb45-2315-4741-b872-bd267a7f1011.png) | ![Simulator Screen Shot - iPhone 13 mini - 2022-02-11 at 14 13 34](https://user-images.githubusercontent.com/13070135/153597978-4ebaab1c-bdbe-43de-ae82-729668b259f4.png) |
| ![Simulator Screen Shot - iPhone 13 mini - 2022-02-11 at 14 14 09](https://user-images.githubusercontent.com/13070135/15359802 …

feat(feedback): Added feedback to bbbus detail and waste screens

---

src/screens/AppIntroScreen.tsx

Solved the issue that the app intro content is under the status bar. The status bar component in the app intro screen is not translucent any more.
SVA-305
---

fix(app-intro): fix app intro content below status bar

---

src/components/wasteCalendar/WasteReminderSettings.tsx

* The settings of the waste calendar have a time picker to select when to be notified. The time within the picker was invisible when the iPhone was on DarkMode as it was light text on white background. The text color is now set to be textDark to be visible again
discovered while working on SVA-327
---
| Before | After |
| --- | --- |
| ![IMG_A39F21564079-1](https://user-images.githubusercontent.com/13070135/153595411-493be50d-e92b-457a-b2b1-efb2fe104b41.jpeg) | ![IMG_E8D6326B6C00-1](https://user-images.githubusercontent.com/13070135/153595440-3863956e-89ce-417b-947e-39550e352265.jpeg) |

fix(theming): Set the text color for the date picker of waste reminder

---

src/components/screens/ServiceTiles.js
src/config/navigation/defaultStackConfig.tsx
src/screens/TilesScreen.js
src/types/Navigation.ts

- added a generic TilesScreen that recieves necessary info through route params
- this makes it possible to nest a TilesScreen into any route
HDVT-40
---
- added new service link "Tiles" on home screen of internal test app

feature: nested services

---

src/components/screens/ServiceTiles.js
src/hooks/staticContent.ts

- if a json static content is not found there could be
a `content: {}` which we assume as error now
- without it this crashed the app

fix(static content): check for content emptiness

---

src/components/wasteCalendar/WasteReminderSettings.tsx

The time send to the API only contained the hours and minutes so that the server assumed it is UTC while the user sees the time in their local time zone
SVA-467

fix(waste calendar): Fixed the missing time zone

---

src/components/volunteer/VolunteerWelcome.tsx
src/config/texts.js
src/screens/WebScreen.js

- added a link to webview with "registration"/possibility to invite other users
in registration process
- needed to add a noop `onMessage` to the webview of the webscreen in addition to
`injectedJavaScript` for making `injectedJavaScript` work in some cases
- injected javascript that manipulates the dom of the humhub page to
remove the login form and just show the required form
- secrets needs to be updated with a `volunteer.inviteUrl`
||||
|---|---|---|
|![Simulator Screen Shot - iPhone 11 Pro - 2022-02-25 at 10 21 09](https://user-images.githubusercontent.com/1942953/155689480-12f92d94-ac02-44dd-8da1-1bd342a9e55e.png)|![Simulator Screen Shot - iPhone 11 Pro - 2022-02-25 at 10 21 12](https://user-images.githubusercontent.com/1942953/155689487-d4bdf342-f891-444b-8b90-18225528d115.png)|![Si …

Volunteer: invite users

---

src/components/oParl/File.tsx
src/components/oParl/Row.tsx

- changed styling of clickable links to be underlined
- made download, access and externalService urls of oparl files open externally on press
SVA-498

Feature: make OParl file urls open externally

---

src/components/Text.js

This improves the android line break behaviour
SVA-220
s. Veranstaltungen-events-lang
| before | after |
|--|--|
|![image](https://user-images.githubusercontent.com/59824597/160403615-7f09cbda-b87a-42fc-a11b-e171d0e48a1f.png)|![image](https://user-images.githubusercontent.com/59824597/160403065-bdea2121-9cc2-44ed-abb5-ea3bee5559ac.png)|

chore(text): insert zero width space after dashes

---

src/hooks/locationHooks.ts

* The location access was to slow for older iOS devices resulting in lists depending on the location being either slow or not ordered by location
* Accuracy was highest which is <<10m accuracy and is now set to balanced which is <100m accuracy
SVA-473

Fix(location): Reduced accuracy for location access on iOS

---

src/helpers/initializationHelper.ts

with this change we will no longer repeatedly ask for location permission on android

Fix: repeated location permission request on app start

---

src/hooks/staticContent.ts
src/screens/MultiButtonScreen.tsx

- follow up for #469
- set error true if there is bad data without `publicJsonFile.content`
or some `queryError`, otherwise it would be always true for the time
data is not yet fetched entirely

fix(static content): add condition for setting error

---

src/components/screens/consul/Debates/NewDebate.js
src/components/screens/consul/Proposals/NewProposal.js
src/config/texts.js
src/screens/consul/LoginRegister/ConsulLoginScreen.js
src/screens/consul/LoginRegister/ConsulRegisterScreen.js

Errors set in rules come in `errors[ITEM_NAME].messages`. In this way, you can display more than one error message on the screen.
---
||||
|--|--|--
|  ![Simulator Screen Shot - iPhone 13 - 2022-04-28 at 13 29 04](https://user-images.githubusercontent.com/11755668/165742902-3b679fb9-14ec-4a06-8a92-fe70127b4d16.png) | ![Simulator Screen Shot - iPhone 13 - 2022-04-28 at 13 29 14](https://user-images.githubusercontent.com/11755668/165742901-a8ea0cb5-ee1b-4107-8af4-1add92640179.png) | ![Simulator Screen Shot - iPhone 13 - 2022-04-28 at 13 29 37](https://user-images.githubusercontent.com/11755668/165742898-2f8e5284-d89b-4ed5-a31e-46e53c35db51.png)
|`rules:require` | `rules:minLength`  | `rules:validate`
SVA-574

fix(consul): multiple error messages

---

src/ConsulClient.tsx
src/components/screens/consul/Debates/NewDebate.js
src/components/screens/consul/Proposals/NewProposal.js
src/helpers/consul/homeData.js
src/screens/consul/LoginRegister/ConsulRegisterScreen.js

- added conditional chaining for access of `consul` values
from secrets, because cities without consul will not have
something or consul configured, thus chaining would break
SVA-403

fix(consul): error for cities without consul

---

src/components/consul/detail/ConsulCommentListItem.js
src/components/consul/detail/ConsulDocumentListItem.js
src/components/consul/detail/ConsulQuestionsListItem.js
src/components/consul/detail/ConsulVotingComponent.js
src/screens/consul/ConsulIndexScreen.js

- fixed the error caused by `TouchableNativeFeedback` used for android
because more than one component is not
supported.
- replaced with `TouchableOpacity` as there
is no `Touchable` style support in
`ConsulQuestionsListItem`.
|||
|--|--|
|old question item|new question item|
SVA-403

fix(consul): android crash fix

---

src/components/consul/detail/ConsulQuestionsDescriptionListItem.js

- added condition to check for `item.description` for not passing empty `html`, due to
"react-native-render-html, Please provide the html or uri prop."

fix(consul): warning with empty `html` for `HtmlView`

---

src/components/form/DropdownInput.tsx
src/components/volunteer/VolunteerFormConversation.tsx
src/components/volunteer/VolunteerUser.tsx
src/config/texts.js
src/helpers/parser/listItemParser.js
src/screens/volunteer/VolunteerFormScreen.tsx
src/screens/volunteer/VolunteerIndexScreen.tsx

- added button to stat a conversation with all members of a group
- adjusted values from `number` to `number[]` where necessary
to be able to handle arrays
- converted all values to arrays where necessary
- adjusted list item parser to take an id from `user.id` if there is no `id`
which is the case for members
HDVT-23
|list with new button|prefilled all members except self|
|---|---|
|![Simulator Screen Shot - iPhone 11 Pro - 2022-05-16 at 18 54 17](https://user-images.githubusercontent.com/1942953/168644983-418022af-5ccd-4a06-b181-cb90b9343109.png)|![Simulator Screen Shot - iPhone 11 Pro - 2022-05-16 at 18 54 21](https://user-images.githubusercontent.com/1942953/168644998-1c42ce13-fe3c-43fb-a6af-09cd9eb5d566.png)|

feat(volunteer): start conversations with whole group

---

src/components/TextListItem.tsx
src/components/volunteer/VolunteerConversationListItem.tsx
src/components/volunteer/index.ts
src/helpers/parser/listItemParser.js
src/hooks/listHooks.js
src/queries/volunteer/conversation.ts

- updated api endpoints to v2 for new conversation/mail
functionalities to mark conversations read and get the status
read/unread
- created a new list item for conversations that are aware of
conversation statuses and render bold texts if unread
and regular texts if read
- based on `TextListItem` with adjustments
- restructured code in `TextListItem` to match
our best practices
HDVT-23
|unread|read|
|---|---|
|![IMG_0057](https://user-images.githubusercontent.com/1942953/168838389-f2db33c5-2fc8-4e55-9740-5472fb169263.PNG)|![IMG_0058](https://user-images.githubusercontent.com/1942953/168838415-dc33338c-9258-44a7-866a-0f33b50cbd14.PNG)|
there is a bug which causes the date/time to update to the date/time when a message is read.
i already opened an issue for this: …

feat(volunteer): read/unread status of conversations

---

src/components/consul/detail/ConsulQuestionsList.js
src/components/consul/detail/ConsulQuestionsListItem.js
src/components/screens/consul/Polls/PollDetail.js
src/queries/consul/Polls/polls.js

- added new fields to the `poll query to show the
results of the poll
- added `resultsReadyToBeShown` prop to
`ConsulQuestionsList` and `ConsulQuestionsListItem`
which allows us to see if it wants to show poll results
- added `totalVotes` and `totalVotesPercentage` data to
`ConsulQuestionsListItem.js` to show poll results on
the screen according to `resultsReadyToBeShown` data
- used the `Math.max()` function to select the highest
rated answer
|||
|--|--|
|Poll not expired and answered|Expired and the winning answer is poll|
SVA-597

feat(consul): add poll results

---

src/config/texts.js
src/helpers/parser/listItemParser.js
src/hooks/listHooks.js
src/queries/consul/Proposals/proposals.js
src/queries/consul/User/user.js
src/screens/consul/ConsulIndexScreen.js

- added a new `published` field to the `proposals` and
`user` query to see if the `Proposal` is drafted
- added the published field to listItemParser to
be able to use it in list item
- added if condition to `listItemParser` to add
`draft` text to `title` according to `Public Proposals`
query and according to `published` data
- add a new if condition to `listHooks` to not show it on
proposal data listing page in draft state
- edited subtitle in `listItemParser` to improve
readability
- added draft text to `texts.js`
SVA-617
|Before List|After List|My Content|
|--|--|--|
|Proposals.js|Proposals.js||

feat(consul): filter draft proposal

---

src/screens/BB-BUS/DetailScreen.js

- adjusted title for "Kosten..." to match the api response
in order to be sorted correctly
- added `TEASER` as block to be removed from rendering
SVA-576
|before|after|
|---|---|
|![IMG_0068](https://user-images.githubusercontent.com/1942953/171187170-dcf78678-7459-47c4-9deb-a4518c86e538.PNG)|![IMG_0067](https://user-images.githubusercontent.com/1942953/171187186-94b1d78f-df6b-48c2-af73-ebba7be0afd1.PNG)|

feat(bus bb): remove teaser and fix order typo

---

src/components/HomeSection.tsx
src/screens/HomeScreen.js

- adjusted condition to set `showButton` depending on correct `query`
in order to check the received data length
- reordered `fetchPolicy` for consistency
SVA-614
|before|after|
|---|---|
|![IMG_0072](https://user-images.githubusercontent.com/1942953/171195727-09c8116b-b5cd-486e-8d0e-eb8b4160de00.PNG)|![IMG_0073](https://user-images.githubusercontent.com/1942953/171195807-0c8ff2f8-7a12-42b6-b9ec-b6ee8ca0d615.PNG)|

fix(home screen): render button for all points of interest and tours

---

src/OnboardingManager.tsx
src/config/texts.js
src/screens/SettingsScreen.js

- added an option to the `SettingsScreen` so that
users can see the intro of the application again
- added new texts to the `texts` file for the intro
option in the settings
---
|SettingsScreen.js|SettingsScreen.js|SettingsScreen.js|AppIntroScreen.js|
|--|--|--|--|
|Settings Screen|If the user turns on this option, they will see an alert|If the user turns this option off, they will see an alert|If the application is restarted with the option turned on, the intro will appear on the screen|
SVA-458

feat(intro): repeat app intro

---

src/components/wasteCalendar/WasteReminderSettings.tsx
src/pushNotifications/WasteReminder.ts

- the database time field is always represented at 01.01.2000 so when saving, we need to force a winter time even if we have summer
- this way the server should always be able to take the right time into account across the whole year regarding one database entry
- sending a `"notify_at": "16:00+01:00"` results in `"notify_at_time": "16:00"`
- sending a `"notify_at": "16:00+02:00"` would result in `"notify_at_time": "15:00"`
- adjusted code for consistency
- we always use `keyboardShouldPersistTaps="handled"` so it should here as well
SVA-467

fix(waste reminder): send notify_at always in winter time

---

src/SettingsProvider.js
src/components/FeedbackFooter.tsx
src/components/infoCard/AddressSection.tsx
src/components/settings/ListSettings.js
src/index.js
src/screens/DetailScreen.js
src/screens/EncounterHomeScreen.tsx
src/screens/HomeScreen.js
src/screens/SettingsScreen.js

- adjusted conditional chaining and initial empty objects everywhere to avoid errors while accessing settings objects
- removed `matomo: false` fallback in settings screen as we now always can access the settings object and if there is no matomo it resolves to false
- we cannot add fallback initial values for every possible settings
- added fallback to `initialGlobalSettings` on setting up the global settings to ensure a valid value also if there was nothing stored locally before or accessing failed somehow
- fixed error: `[Unhandled promise rejection: TypeError: null is not an object (evaluating 'globalSettings.settings')]`

fix(global settings): initializations and accesses

---

src/components/screens/About.js

- added rendering of version number if there is no data
for "homeAbout", which resulted to a missing version number
in latest version, as it was moved to section list footer, that
was only rendered if there are list entries

feat: always show version number in drawer mode

---

src/components/volunteer/VolunteerEventRecord.tsx
src/screens/volunteer/VolunteerLoginScreen.tsx
src/screens/volunteer/VolunteerMeScreen.tsx
src/screens/volunteer/VolunteerRegistrationScreen.tsx
src/screens/volunteer/VolunteerSignupScreen.tsx

- `data?.code` could be 0 in some cases which resulted in false
and the check for `data?.code !== 200` was not running,
so every kind of that occurrence is updated

refactor: conditional chaining in favor of && chained check

---

src/components/consul/detail/ConsulCommentListItem.js
src/components/screens/consul/Debates/DebateDetail.js
src/components/screens/consul/Polls/PollDetail.js
src/components/screens/consul/Proposals/ProposalDetail.js
src/config/Icon.tsx

- removed `Send` icon as we used `Mail` in other places
and want to have the same icon everywhere
- also `Mail` is svg and does not depend on a font icon set
so there are no changes necessary across different cities

refactor: unify mail icon

---

__tests__/components/__snapshots__/Link.test.js.snap
__tests__/config/colors.test.js
src/components/BB-BUS/IndexFilter.js
src/components/Checkbox.js
src/components/DropdownSelect.js
src/components/Link.js
src/components/Radiobutton.js
src/components/Text.js
src/components/Title.js
src/components/consul/detail/ConsulDocumentListItem.js
src/components/form/Input.tsx
src/components/screens/consul/Debates/DebateDetail.js
src/components/screens/consul/Polls/PollDetail.js
src/components/screens/consul/Proposals/NewProposal.js
src/components/screens/consul/Proposals/ProposalDetail.js
src/components/volunteer/VolunteerAvatar.tsx
src/components/volunteer/VolunteerFormCalendar.tsx
src/components/volunteer/VolunteerFormGroup.tsx
src/components/volunteer/VolunteerMessage.tsx
src/config/colors.js
src/navigation/DrawerNavigatorItem.js
src/screens/EncounterHomeScreen.tsx
src/screens/FeedbackScreen.js

- changed `lightestText` to `surface` where it was used for background, as both are white, but one for texts and the other for surfaces
- removed `lighterText` as it was rarely used and gray, so `gray60` could be used
- changed `secondary` to `primary` for bus bb link icons to always have the same color for the icon and the text
- properly set error color for form validations of inputs
- updated jest snapshots with missing colors
SVA-646

refactor(colors): adjust and cleanup

---

src/screens/volunteer/VolunteerMeScreen.tsx
src/screens/volunteer/VolunteerSignupScreen.tsx

- there could be no `status` at all in an successful response
so we need to check for existing `.status` explicitly, conditional
chaining cannot achieve that
---
follow up for #561

refactor/fix: && chained check in addition to conditional chaining

---

app.json
eas.json
index.js
package.json

setup(eas build): initial configuration
- ran `eas build:configure` after installing the cli tool per `npm install -g eas-cli`
setup(eas build): individual configuration
- adjusted the configs to our build tools and versions from `.nvmrc` and `.yvmrc`, see https://docs.expo.dev/build/eas-json/#configuring-your-build-tools and https://docs.expo.dev/build/eas-json/#build-profiles
- `production` builds will be submitted to app stores, for release to the general public or as part of a store-facilitated testing process
- `preview` builds don't include developer tools, they are intended to be installed by your team and other stakeholders, to test out the app in production-like circumstances
- `development` builds include developer tools, and they are never submitted to an app store
- …

setup eas build

---

src/components/Image.js
src/components/ServiceBox.js
src/components/screens/Service.js
src/components/screens/ServiceTile.tsx
src/components/screens/ServiceTiles.js
src/components/screens/index.js

refactor(service tiles): reduce duplication
- crated new `ServiceTile` that combine duplicated code
for `Service` and `ServiceTiles` with condition for coloring
based on `hasDiagonalGradientBackground`
feat(service tiles): new possibility for big tiles
- added option for big tiles with an image `tile`
that is styled bigger (orientation aware) and
with less spacings to each other in the grid
- added option for `accessibilityLabel` in order
has `tile`-image has text on it and no separate
title rendered
feat(service tiles): increase size
- updated calculation of tile sizes based on device orientation,
safe are insets and paddings
feat(service tiles): increase size even more
- updated `ServiceBox`s flex basis to result in bigger tiles
conditionally
- refactored conditions for the flex basis …

feat(service tiles): new option for bigger tiles

---

src/screens/augmentedReality/ARShowScreen.js

- added the ability to start and stop
animation to 3D object
- added a new if to the parser to
distinguish if there is an animated
3D object
- added animation prop to `Viro3DObject`
to start and stop animation
SVA-633
|Animation Start Button|
|--|

feat(ar): start animation

---

README.md
package.json
yarn.lock

- there could be problems with different versions of react types so we fixed it to 17.x per resolutions
- https://stackoverflow.com/a/72714740/9956365
- updated versions of packages used in README

fix: react types version and versions listed in README

---

src/screens/IndexScreen.js

added check for POI type when considering `showMap` to delete the `limit` param in `queryVariables` which could lead to requesting all news items when this is not intended

fix: query variables without limit

---

src/screens/augmentedReality/ARShowScreen.js

- deleted object `moveObject` and `rotateObject` functions
as they are not necessary
- replace the `position` and `rotation` props with default
data since the object  `moveObject` and `rotateObject`
functions are deleted
SVA-633

refactor(ar): delete object move and rotate functions

---

src/components/CrossData.tsx
src/components/DataListSection.tsx

- fixed the error of displaying empty sections on
`CrossData` page
- added `navigateButton` prop to `CrossData` to
make `Alle anzeigen` button appear in sections
- added if to `DataListSection` to prevent rendering
if `listData` is empty
- added to show placeholder render on screen if
`listData` comes empty
- added null return if placeholder is empty
|Before|After|
|--|--|

fix: solve empty section error

---

src/components/screens/consul/Debates/DebateDetail.js
src/components/screens/consul/Polls/PollDetail.js
src/components/screens/consul/Proposals/ProposalDetail.js
src/components/screens/consul/UserComments/UserCommentDetail.js
src/helpers/consul/index.js
src/screens/consul/ConsulHomeScreen.js
src/screens/consul/LoginRegister/ConsulLoginScreen.js

- updated to store only the user's id information
to avoid storing unused information about the
user in memory
- updated with the user's id information directly
from `asyncStorage` instead of `JSON.parse(...).id`
for places where user id is needed

refactor(consul): save user id

---

src/config/texts.js
src/screens/augmentedReality/ARShowScreen.js

- updated the screen recording button, screenshot
button and animation button to be shown after the
model is loaded because the buttons are not
functional without loading the 3D object
SVA-633

feat(ar): show buttons after loading the 3D object

---

src/hooks/NewsCategories.ts
src/queries/newsItems.js
src/screens/HomeScreen.js

Added an option to request multiple category ids on the index screen if passed with `indexCategoryIds`. If not it uses the `categoryId` like before. The main-server is prepared to accept `categoryId` or `categoryIds`.
SVA-660
---
For global settings here is an example to request category with id 1 on the home screen and when navigating to the index screen there should be requested category ids 1 and 78:

feat(news): index with multiple category ids

---

src/components/augmentedReality/AugmentedReality.js
src/components/augmentedReality/AugmentedRealityView.js
src/components/augmentedReality/index.js
src/config/texts.js
src/screens/SettingsScreen.js
src/screens/augmentedReality/ARShowScreen.js

- added image recognition feature to show
3D model
- wrapped augmented reality features with
the `ViroARImageMarker` component to
make the image recognition feature work
- added `targetImage` in `createTargets`
object from `ViroARTrackingTargets` to
add image information
- update the scale because the model looks
too big
- added animation of the model and sound file
when the image is recognised
SVA-633
In order to test this feature, you must first delete any downloaded model data on your device. Then refresh the model list and download it again (54.9 MB). Because the target image must be added to the server for the image recognition feature.
After the download is complete, go to `ARShowScreen` and show the image shared below to the camera.

feat(ar): recognise image and show model

---

src/components/augmentedReality/AugmentedRealityView.js

- added `orientation` prop to `createTargets`
because image recognition feature is crash
in android
-  orientation prop: determines the orientation
of the source image
[viro document for orientation](https://viro-community.readme.io/docs/viroartrackingtargets#orientation)
SVA-633

fix(ar): solve android crash for recognise image

---

src/components/CategoryList.js
src/components/DropdownHeader.js
src/components/DropdownSelect.js
src/components/EventList.js
src/components/VerticalList.js
src/components/widgets/EventWidget.tsx
src/config/texts.js
src/queries/newsItems.js
src/screens/IndexScreen.js

- added a new switch on event index screens to toggle daily events which are default when coming from the event widget
- needed to make this `refetch` magic like we already did in `updateListData` to re-render the index screen
- re-organized imports in index screen and refactored `... ?... : null` to a shorter `&&` for the opening times filter
refactor(lists ): optimize behavior when filtering
- created a callback that handles the update of the switch state as well as the update of the query variables
- this way we get rid of one re-rendering (first switch statte, second query variables state) which seems to affect the list rendering in a weird way
- refactored loading screen to refresh control to not have a full full white screen with the loading spinner when filtering but a loading …

feat: add filter for daily events on index screen

---

src/components/map/Map.tsx
src/components/settings/LocationSettings.js

- updated `WebViewMap` in settings page
with new map
- added `onMapPress` prop to `Map`
component for user to change location
- added `mapStyle` prop to `Map` component
because we may need different map styles on
different pages
- added `maxZoomLevel` prop to `MapView`
component because zoom value may vary on
different pages
- integrated the style used in `WebViewMap`
into the new `Map` component to achieve the
same look and feel
- added alphabetical order to the `Map`
component's props to make it more understandable
SVA-634
|Old Map|New Map|
|--|--|

feat(map): add on settings screen new map

---

src/helpers/linkHelper.js

- fixed `canOpenURL` bug that prevented links
from opening on android
SVA-689

fix(linking): error android linking not opening

---

src/screens/MultiButtonScreen.tsx

Changed rendering component to a html view in order to put styles and images on the screen above buttons.
SVA-629
---
|before|after|with image|
|---|---|---|
|![Simulator Screen Shot - iPhone 11 - 2022-08-09 at 19 49 47](https://user-images.githubusercontent.com/1942953/183725395-8af6d8f0-af61-4a66-9ea7-9feba1d29c76.png)|![Simulator Screen Shot - iPhone 11 - 2022-08-09 at 19 51 10](https://user-images.githubusercontent.com/1942953/183725410-0677e930-4dea-4ff5-85af-689da4bc3174.png)|![Simulator Screen Shot - iPhone 11 - 2022-08-09 at 19 53 34](https://user-images.githubusercontent.com/1942953/183725424-4aa33c04-caac-49d8-b67e-e15392acaeef.png)|

feat: multi button screen with html

---

src/components/volunteer/VolunteerEventRecord.tsx
src/config/Icon.tsx

- added method to filter for files on their mimetype to differentiate
between image and file (application)
- added rendering of files/documents with same style like in uploads
but with new icon on the left
HDVT-55
|render|press|
|---|---|
|![simulator_screenshot_5181392D-6317-4F92-87C7-AF79EECC47B8](https://user-images.githubusercontent.com/1942953/183933225-25a33560-51f4-4030-9c3e-3518395f033c.png)|![Simulator Screen Shot - iPhone 11 - 2022-08-10 at 16 37 55](https://user-images.githubusercontent.com/1942953/183933124-030cdd34-02a1-4c75-bda2-3fd7a3a34182.png)|

feat(volunteer): render documents for volunteer events

---

src/components/augmentedReality/ARModal.js
src/components/augmentedReality/ARObjectList.js
src/components/augmentedReality/ARObjectListItem.js
src/components/augmentedReality/AugmentedReality.js
src/components/augmentedReality/AugmentedRealityView.js
src/components/augmentedReality/IconForDownloadType.js
src/components/screens/Tour.js
src/helpers/augmentedReality/checkDownloadedData.js
src/helpers/augmentedReality/deleteObject.js
src/helpers/augmentedReality/downloadAndDeleteAllData.js
src/helpers/augmentedReality/downloadObject.js
src/helpers/augmentedReality/storageNameCreator.js
src/queries/index.js
src/queries/tours.js
src/queries/types.ts
src/screens/SettingsScreen.js
src/screens/augmentedReality/ARShowScreen.js
src/screens/augmentedReality/ArtworkDetailScreen.js

- added `tourStops` query to `tour` query
- updated all helpers accordingly as the model
information is included in the `payload` object
- changed from `png` to `texture` in the resource
section to support different file types
- removed `refetch` because the data came with
tour data
- updated `DOWNLOAD_TYPE` to `downloadType`
- added `imageType` to `storageNameCreator`
and updated `objectName` to capture the actual
name and extension of the texture file
SVA-633

feat(ar): add `tourStops` query

---

src/components/widgets/DefaultWidget.tsx
src/components/widgets/EventWidget.tsx
src/types/WidgetProps.ts

- added `noCount` bool expression in
`additionalProps` to catch changes
on the server
- added `noFilterByDailyEvents` bool
expression in `additionalProps` to
catch changes on the server
- added not showing count on widget if
`additionalProps.noCount` is set to
`true` in `globalSettings`
- added control to `filterByDailyEvents`
param to turn off the daily event filter
when opening the index page
- converted `styles` to function and 
added `count` prop to set styles 
according to the number of widgets
- deleted the blank line rendered to 
the screen in case there is no count 
to centre the icon
- changed `count` to a boolean expression 
by adding `!` at the beginning to 
eliminate the problem of `false` if 
`count` is `0`
SVA-664
⚠️ please add the necessary objects to `globalSettings` to …

feature(event): not showing count in event widget

---

src/screens/EncounterDataScreen.tsx

- updated the `hasChanges` state
to `false` in the `updateUserData`
function to deactivate the save
button after saving the user's
information
SVA-719
|Before changing the information|After changing the information|After saving the information|
|--|--|--|

feat(encounter): deactivate after pressing the save button

---

src/screens/WasteCollectionScreen.js

- changed props of the `Autocomplete`
package due to version upgrade have
been reorganised
- changed some styles to provide the
same style on both platforms
SVA-703
|iOS|iOS|
|--|--|
|Android|Android|
|--|--|

fix: solve error to `Autocomplete` package

---

src/components/augmentedReality/AugmentedReality.js
src/components/map/Map.tsx
src/components/screens/Tour.js
src/components/screens/TourCard.js
src/config/Icon.tsx
src/config/navigation/defaultStackConfig.tsx
src/config/texts.js
src/helpers/augmentedReality/index.js
src/helpers/augmentedReality/navigationToArtworkDetailScreen.js
src/screens/MapViewScreen.js
src/screens/index.js
src/types/Navigation.ts

- added `IndexFilterWrapperAndList` component to
Augmented Reality section for map view and list view
- added `mapToMapMarkers` function to make the
location data from the server suitable for the map
component
- added new texts to `texts` file to show in filter section
- added redirection to `artworkDetailScreen` with
markers on the map
- added `showUserLocation` as a prop and set true
by default
- added full screen map view
- added a new button for full screen
navigation at the bottom right of the
small map view
- added `onMaximizeButtonPress` prop to
`AugmentedReality` component to switch
to large map view
- added new map navigation to
`defaultStackConfig`
- added artwork information window shown below
the map when clicking on the marker on the full
page map
- used …

feat(ar): add map view to augmented reality

---

src/components/augmentedReality/AugmentedReality.js
src/components/map/Map.tsx
src/components/screens/Tour.js
src/queries/tours.js
src/screens/MapViewScreen.js

- added `Polyline` to `Map` component to show
the route on the map
-  to see the route we need location information
of type `LatLng[]`
- added `geometryTourData` to `Tour` query for
route information
- added the necessary props to display the route
on the fullscreen map page
- added control to prevent an error if the
`augmentedReality` object does not have location
information
SVA-634
|Polyline without loading the map|Polyline wit loading the map|Full screen Polyline on the map|
|--|--|--|

feat(maps): add polyline to map

---

package.json
src/screens/EncounterScannerScreen.tsx
yarn.lock

- added `expo-barcode-scanner` package to make barcode scanner work
SVA-724
⚠️ the reason for the error after qr code scann is that the requested information is not received from the server. the server may need to be updated to correct this error.
|||
|--|--|

feat(encounter): add expo barcode scanner

---

src/components/settings/LocationSettings.js

- added `latitude` and `longitude` information for the application to read since the location information from `globalSettings` is `lat` and `lng`
SVA-634

fix(map): fix map on settings screen

---

.gitignore

- moved native application folder lines up to make it easier to translate to comment line when building with eas

refactor: change places inside the gitignore

---

src/components/settings/LocationSettings.js

- moved `locationObject.coords` upwards to avoid overwriting longitude and latitude information
SVA-634

refactor(map): relocate

---

app.json

- iOS simulator builds are not running with viro package integrated
- if apps do need viro for AR features, `"@viro-community/react-viro"` needs to be added individually from now on
- for development purposes that is needed as well temporarily

fix(viro): remove plugin integration by default

---

src/components/Chat.js

- centred text typed in textInput for android
- added border over the media preview section as shown in the design
HDVT-85
|before iOS (text input)|after iOS (text input)|before iOS (media preview)|after iOS (media preview)|
|--|--|--|--|
|before android (text input)|after android (text input)|before android (media preview)|after android (media preview)|

style(volunteer): change text input and media preview style

---

src/components/Chat.js

- added `lightboxProps` to the `MessageImage` component to remove the `useNativeDrive` warning when an image is opened in the `GiftedChat` component
SVA-767

fix(volunteer): solve `useNativeDrive` warn

---

src/components/map/Map.tsx

- added `zIndex` prop to `Polyline` component in `Maps` to make polyline visible on Android devices
SVA-634
|iOS|android portrait|android landscape|
|--|--|--|

fix(maps): make polyline visible for android

---

src/components/screens/ServiceTiles.js
src/config/navigation/defaultStackConfig.tsx
src/screens/TilesScreen.js

- added `imageKey` to `defaultStackNavigator` for the key of the image information added to the server
- added image link as a prop to `ServiceTiles`
- checking the image information and displaying it on the screen if there is an image
SVA-761
⚠️ add an image link to the image field in the required `globalSettings` on the development server to try it ⚠️
|iOS portrait mode|android portrait mode|android landscape mode|
|--|--|--|

feat: add image to service page

---

src/components/augmentedReality/AugmentedReality.js
src/screens/SettingsScreen.js

- updated id to send tourId added to `globalSettings` to `AugmentedReality` component in settings page
- changed the ar variable in `globalSettings` from a boolean expression to an object, so this value is changed to a boolean expression in `SettingsScreen` and `AugmentedReality` component
- updated settings object in `globalSettings` to be accessible from everywhere since it is used in multiple places in `SettingsScreen`
SVA-633

feat(ar): add `tourId` to ar object in `globalSettings`

---

src/components/augmentedReality/AugmentedReality.js
src/screens/SettingsScreen.js

I have tested locally with Android emulator, where Viro is not supported - it crashed.
So I needed to add a try catch to avoid crashes with Viro where we do not use Viro.

fix: add try catch if Viro is not integrated per app.json

---

src/components/map/Map.tsx
src/components/settings/LocationSettings.js

- set `initialRegion` more explicitly to avoid undefineds
- extended setting coords in `getLocationMarker` because in global settings we are storing the short ones

fix: coords in location settings

---

src/screens/SettingsScreen.js

- added `selectedFilterId` as second parameter to `useEffect` for `SettingsToggle` to update itself when switching between tabs on `SettingsScreen`
SVA-789
|before|after|
|--|--|
|<video src="https://user-images.githubusercontent.com/11755668/196155730-22338df6-862c-47fd-b01c-34bd34cd82e6.mp4" controls="controls" style="max-width: 300px;"></video>|<video src="https://user-images.githubusercontent.com/11755668/196155451-86eb751f-5da7-4012-9950-2eb5b788bbdb.mp4" controls="controls" style="max-width: 300px;"></video>|

feat: add parameter to useEffect

---

src/helpers/augmentedReality/checkDownloadedData.js
src/helpers/augmentedReality/deleteObject.js
src/helpers/augmentedReality/downloadAndDeleteAllData.js
src/helpers/augmentedReality/downloadObject.js
src/helpers/augmentedReality/storageNameCreator.js
src/screens/augmentedReality/ARShowScreen.js

- added `for..of` loop for downloading multiple 
3D models and downloading scenes within a 
`scenes` array
- added `sceneIndex` to add the uri of whichever 
index in `scenes` was downloaded to `localUris`
- added `sceneIndex` to `storageNameCreator` 
to ensure that the file names are different if the 
names of the objects in the scene are the same
- added control of the `scenes` array with a `for..of` 
loop to ensure that different downloaded scenes 
are deleted from the device
- added `sceneIndex` to access the uri of the 
downloaded scene added to `localUris` and empty 
the array
- added check with `for...of` loop to the `scenes`
array to check if the downloaded scenes are on
the device
- added `for...of` loop to `scenes` array 
to download all scenes with a single button
- added …

feat(ar): multiple model management

---

src/components/augmentedReality/ARObjectList.js
src/helpers/augmentedReality/progressSizeGenerator.js
src/helpers/fileSizeHelper.ts

- added `formatSizeForAugmentedReality` to `fileSizeHelper` to convert byte more accurately
- updated `formatSize` helper used in `ARObjectList` and `progressSizeGenerator` files with `formatSizeForAugmentedReality`
SVA-565

feat(ar): add format size for augmented reality

---

src/screens/MapViewScreen.js

- removed the description text when shown on the map page because it was shown full screen
- changes have been made to display the `locationInfo` data carried inside the payload object on the screen
SVA-565

feat(ar): remove description on map page

---

src/components/augmentedReality/AugmentedRealityView.js
src/helpers/augmentedReality/deleteObject.js
src/helpers/augmentedReality/downloadObject.js
src/screens/augmentedReality/ARShowScreen.js

- added light props from server to
`ViroAmbientLight` component
- added uri check in `deleteObject`
because the light prop has no
downloadable link, otherwise
`deleteAsync` will give an error
because there is no uri
- added uri check to `downloadObject` 
because `fileSystemDownload` will get 
an error because the light prop does not 
have a uri
- added new control to `maxDistance`, 
`minDistance` and `physicalWidth` so 
they don't take up unnecessary space in `JSON`
- added to the parser function in `ARShowSceen`
to parse new light props
SVA-632

feat(ar): add light props for viro ambient light

---

src/components/volunteer/VolunteerEventRecord.tsx
src/components/volunteer/VolunteerFormCalendar.tsx
src/components/volunteer/VolunteerFormGroup.tsx
src/components/volunteer/VolunteerGroup.tsx
src/queries/volunteer/group.ts
src/types/volunteer/group.ts

- added settings button to
the header that only the
group owner can see
- added new styles for buttons
in the header
- added default values for
editable data
- added route prop to receive
editable data
- added `mutateEdit` to 
update the edited information 
on the server
- added control based on data 
from param to use `mutateEdit`
- added `groupDelete` function 
to `group` to delete group
- added new button to 
`VolunteerFormGroup` to delete 
group
- added alert to get user's 
confirmation to delete group
- added `onGroupDelete` function 
to send group delete request
- deleted as `owner` inputs not required
- deleted as the `owner` types are not needed
- deleted the `owner` sections that were added
as html code to the `description` section when
uploading to the server because they were …

feature(volunteer): editing of group data

---

src/components/Button.js
src/components/screens/ServiceTiles.js
src/config/colors.js
src/hooks/HomeRefresh.ts
src/queries/types.ts
src/screens/volunteer/VolunteerHomeScreen.tsx

The new home screen is working for logged in and logged out users with different static contents for texts and service tiles. This way we can configure multiple things on the server more dynamically and customer can access and change these data and information as well.
HDVT-87
|logged in|logged out|
|---|---|
|![Simulator Screen Shot - iPhone 11 - 2022-11-01 at 11 21 54](https://user-images.githubusercontent.com/1942953/199212970-a0a63483-de89-40b2-bdbe-cd3fbaea42e6.png)|![Simulator Screen Shot - iPhone 11 - 2022-11-01 at 11 22 06](https://user-images.githubusercontent.com/1942953/199212983-7da84672-b163-4ec2-82b1-f42759132b6a.png)|

feat(volunteer): new home screen

---

src/config/navigation/defaultStackConfig.tsx
src/hooks/HomeRefresh.ts
src/navigation/screenOptions.tsx
src/queries/types.ts
src/screens/volunteer/VolunteerLogoutScreen.tsx
src/screens/volunteer/VolunteerPersonalScreen.tsx
src/screens/volunteer/index.ts
src/types/Navigation.ts

The new personal screen is working with different static contents for texts and service tiles. This way we can configure multiple things on the server more dynamically and customer can access and change these data and information as well.
HDVT-87
|personal screen|logout screen|
|---|---|
|![Simulator Screen Shot - iPhone 11 - 2022-11-01 at 16 10 59](https://user-images.githubusercontent.com/1942953/199267382-69ecdb35-dfac-4951-a31e-6f1273a5ad29.png)|![Simulator Screen Shot - iPhone 11 - 2022-11-01 at 16 11 10](https://user-images.githubusercontent.com/1942953/199267395-0db0b3d6-8c65-4bdb-b09f-034cfff557e9.png)|

feat(volunteer): new personal screen

---

src/components/volunteer/VolunteerFormGroup.tsx
src/config/texts.js
src/queries/volunteer/group.ts

- added selectable visibility properties 
when creating a group
- created `VISIBILITY_OPTIONS` array 
to select visibility options with checkbox
- updated the visibility values sent during 
the request with the selected value
- added selectable `joinPolicy` properties 
when creating a group
- created `JOIN_POLICY_OPTIONS` array 
to select `joinPolicy` options with checkbox
- updated the `joinPolicy` values sent during 
the request with the selected value
- added `watch` function to not show `joinPolicy` 
Checkboxes if visibility value is 
`VISIBILITY_TYPES.PRIVATE`
HDVT-90
You can add this code to `VolunteerHomeScreen` to try it out:
```       
<Button
title="Create Volunteer Group"
onPress={() =>
navigation.navigate(ScreenName.VolunteerForm, { query: QUERY_TYPES.VOLUNTEER.GROUP })
}
/> …
```

feat(volunteer): add visibility and `joinPolicy` to create a group

---

src/helpers/parser/listItemParser.js

- solved the problem by taking the `user` object into the user object if there is no `volunteer.user` object in the data coming from the server because there is no user object that `VolunteerAvatar` needs
HDVT-87
|before|after|
|--|--|

fix(volunteer): fix avatar not appearing in event attendee list

---

src/components/augmentedReality/AugmentedRealityView.js

- removed rotation prop in `ViroAmbientLight` to prevent application crashes
SVA-565

fix(ar): android error due to `ViroAmbientLight`

---

src/components/CommentSection.tsx
src/components/Radiobutton.js
src/components/map/Map.tsx
src/components/screens/ServiceTile.tsx
src/components/screens/ServiceTiles.js
src/components/survey/SurveyAnswer.tsx
src/components/volunteer/VolunteerHomeSection.tsx
src/components/wasteCalendar/WasteReminderSettings.tsx
src/screens/EncounterDataScreen.tsx
src/screens/EncounterRegistrationScreen.tsx

moved `normalize` imports from `react-native-elements` to our configs as it seems to be happened mistakenly before.
please also check around with different simulators and systems, if anything seems to break or be misaligned now.

refactor: adjust `normalize` import

---

src/components/screens/PriceCard.js
src/config/texts.js
src/helpers/priceHelper.js

- there can be free entries, which we were not showing because it resulted in `false`
SVA-822
|before|after|
|---|---|
|![Simulator Screen Shot - iPhone 12 mini - 2022-11-21 at 11 59 39](https://user-images.githubusercontent.com/1942953/203036512-bca16d04-7d05-410b-8136-5b93a641187a.png)|![simulator_screenshot_FE2E8DF8-3BBC-44A8-872C-007904303AB0](https://user-images.githubusercontent.com/1942953/203051075-ffcfcc06-2164-4636-9da5-1f9ec08adb46.png)|

feat(price card): show 'kostenlos' instead of nothing

---

src/config/navigation/defaultStackConfig.tsx
src/config/texts.js
src/screens/NestedInfoScreen.tsx
src/screens/NoticeboardIndexScreen.tsx
src/screens/index.js
src/types/Navigation.ts

- added index screen for `noticeboard` `genericItem`
- `noticeboardIndexScreen` differs from `nestedInfoScreen` in that it has a `genericItem` list with query
- added the necessary information for the navigation structure to `defaultStackConfig` and `Navigation`
- added `EmptyMessage` component to show on screen if there is no data in `noticeboardIndexScreen`
SVA-739
|Noticeboard Offers Screen|Noticeboard Searches Screen|Noticeboard NeighbourlyHelp Screen|
|--|--|--|

feat(noticeboard): add `noticeboardIndexScreen`

---

app.json
src/components/settings/PermanentFilterSettings.tsx
src/config/secrets.temp
src/pushNotifications/PermissionHandling.ts
src/pushNotifications/TokenHandling.ts

- added request to call a new endpoint on switching data provider settings with passing excluded data provider ids that will be respected for push notifications
- added `experienceId` needed to properly create expo push tokens
- therefore added `owner` in app.json, which is the account name registered at expo.dev
SVA-710
|switches|passed object|
|---|---|

feat(push notifications): exclude data providers

---

package.json
src/components/augmentedReality/AugmentedRealityView.js
src/helpers/augmentedReality/downloadObject.js
src/helpers/augmentedReality/index.js
src/helpers/augmentedReality/multipleSceneIndexGenerator.ts
src/helpers/augmentedReality/objectParser.js
src/screens/augmentedReality/ARShowScreen.js

- added `multipleSceneIndexGenerator` to calculate texture and model indexes for a model containing more than one scene
- added moment-range package to measure day difference
- added stable key to `downloadObject` helper to save stable textures coming from server
- added selecting the required model from the scenes array with the index information from the `multipleSceneIndexGenerator` function
- added the required texture data to the newly created `variableTextures` array after the `modalIndex` and `textureIndex` data have the number type and added to the `parsedObject.textures` array
- renamed the `texture` array to `textures` for clarity
- changed the `multipleSceneIndexGenerator` function to `void` format as there is no need for `async/await` function
- filtering the texture files in …

feat(ar): multiple scene logic

---

src/components/augmentedReality/AugmentedRealityView.js

- added `loop` prop to `ViroSound` and `ViroSpatialSound` component for unlimited looping
- deleted the `onFinish` function in the `ViroSound` and `ViroSpatialSound` component to prevent the audio file from being stopped after finishing
SVA-565

feat(ar): make the sound infinite loop

---

src/components/augmentedReality/AugmentedRealityView.js
src/helpers/augmentedReality/multipleSceneIndexGenerator.ts
src/helpers/augmentedReality/objectParser.js

- added multiple models and textures from the `scene` array to the `models` and `textures` arrays in order to show the models using the map function on the `AugmentedRealityView` screen
- deleted objects according to their types with `_remove` method to prevent unnecessary texture and model information
- creating `variableTextures` based on index 0 of the scene and we were constantly getting variable textures of the model at index 0. To avoid this, `variableTextures` has been updated with `modelIndex`
- deleted the direct return of `localUris` in case `variableTexturesCount` is `false` because we need `models` and `textures` arrays inside `localUris`
- added `models` array in `parsedObject` to parse one or more models
- changed `parsedObject?.vrx` control to `parsedObject?.models?.length` …

feature(ar): show multiple models in one scene

---

src/helpers/parser/listItemParser.js
src/screens/Noticeboard/NoticeboardIndexScreen.tsx

- added `consentForDataProcessingText` information required for `noticeboard` to options instead of `titleDetail`
SVA-739

refactor(noticeboard): add `consentForDataProcessingText` to `listItem`

---

src/components/screens/Service.tsx
src/components/screens/ServiceTiles.js
src/hooks/staticContent.ts

static contents can be corrupt if they are not valid jsons after editing on the main server. this could lead to crashes of the application without a proper solution.
- added a json validation with checking of proper object, which results in an error if there is something bad
- added error condition in `ServiceTiles` to not render `Service` if there is an error
- removed rendering of tiles toggler if there are no tiles
SVA-844

fix(static contents): add error if not an object

---

src/helpers/genericTypeHelper.ts
src/helpers/parser/listItemParser.js

- created helper that returns different values for different generic types respecting the current state for noticeboard entries (empty string) and the fallback of the data provider name
SVA-710

feat(deadlines): show category in list

---

src/components/Modal.js
src/components/augmentedReality/ARModal.js

- added height to modal because modal cannot be switched off on small screen phones if there are too many models
SVA-565
|before|after|
|--|--|

fix(ar): add height to modal

---

src/helpers/augmentedReality/multipleSceneIndexGenerator.ts

- removed `texture` and `vrx` deletion because we encountered an error when we wanted to view the model again because we deleted `texture` and `vrx` objects from `localUris`
SVA-565

fix(ar): fixed model not displaying a second time

---

src/components/augmentedReality/AugmentedRealityView.js
src/helpers/augmentedReality/downloadObject.js
src/helpers/augmentedReality/objectParser.js

- added `ViroSpotLight` component which is required to show a shadow effect under the model
- added `ViroQuad` to create a virtual floor
- added the `arShadowReceiver` prop to `ViroQuad`, which is required for the shadow to mask the model
- added `shadowCastingBitMask` prop to `Viro3DObject` component to show the shadow of the model on the ground
- added new properties to `downloadObject.js` to be able to add the new information needed for `ViroSpotLight` and ViroQuad` to `localUris` to show the shadow
- edited `objectParser.js` to move newly added features to `AugmentedRealityView` screen
- removed the extra checks in the `AugmentedRealityView` screen, as we have already checked that the `object` contains the required information
SVA-565
|before|after|
|--|--|

feat(ar): add `ViroSpotLight` and `ViroQuad` to scene

---

src/components/weather/DailyWeather.tsx
src/screens/WeatherScreen.js

- changed daily weather forecasts from two text components to one text component to enable `VoiceOver` to read them continuously
- changed `showsHorizontalScrollIndicator` to false to avoid preventing VoiceOver from reading the degree of weather in hourly weather
SVA-885

refactor(accessibility): convert weather forecast to one text

---

src/components/screens/PriceCard.js

- deleted `groupPrice` from the code because it caused the Android App to crash. `groupPrice` is a boolean value and cannot be formatted.
SVA-913

fix: delete `groupPrice` because the android app crashed

---

src/components/CategoryList.js
src/screens/IndexScreen.js

- added `categoryListIntroText` to the `sections` section on the server to be able to change the text on the `CategoryList` screen via the server
- added intro text used in `CategoryList` component to `IndexScreen`
SBB-19
To try it out, add the following line to the `sections` section in `globalSettings` on Main-Server.
```
"categoryListIntroText": "Intro Text",
```

feat(category): make category intro text changeable from server

---

src/components/defectReport/DefectReportCreateForm.tsx

- added `*` to the label of the category because it is required
SVA-738
|before|after|
|--|--|

refactor(defect report): add star for required field

---

src/config/consts.js

- changed the maximum screen length to solve the problem of the icons in the tabbar being aligned to the left side
SBB-5
🔍 in our code, the `FULL_SCREEN_MAX_WIDTH` value we set in our code perceived the devices after a certain size as tablets and shifted the icons in the tabbars to the right side as much as the `normalize(10)` value.
i updated `FULL_SCREEN_MAX_WIDTH` according to the size of current phones and managed to centre the icons in the tab
|iPhone 14 Plus (before)|iPhone 14 Plus (after)|
|--|--|
|iPhone 14 Pro Max (before)|iPhone 14 Pro Max (after)|
|--|--|
|iPhone 8 (before)|iPhone 8 (after)|
|--|--|

refactor(tabbar): change the full screen max width

---

src/helpers/augmentedReality/multipleSceneIndexGenerator.ts

- added to `localUris` by finding the information in the first index for more stable operation of the AR feature
SVA-571

feat(ar): add missing information

---

src/components/BB-BUS/TextSearch.js
src/components/form/InputSecureTextIcon.tsx
src/config/texts.js

- added `accessibilityLabel` for `searchIcon` and `clearIcon` used in search input for users using `VoiceOver` feature
- added `accessibilityLabel` for the show or hide password button used in the password input for users using the `VoiceOver` feature
- added `accessibilityLabels` section to texts for use in new accessibility features
SVA-899

feat(accessibility): add new labels for input buttons

---

src/navigation/DrawerNavigatorItem.js

- added `undefined` if there is no `subQuery` object to solve the param error that occurs when navigating between two pages with the same name via the drawer menu
SVA-940
- open the drawer menu and first go to the `Abfallkalender mit Zwischenseite` screen
- this page is an `HtmlScreen` + multi button page and depends on `subQuery`
- go to the `CMS` screen again via the drawer menu before going to another screen
- this page is also an `HtmlScreen` but without buttons. because `subQuery` is not added in the navigation structure
- since there is no change in the navigation, that is, both screens are `HtmlScreen` pages, the `subQuery` parameters are automatically moved to the `CMS` page
- with the change in the navigation structure, if there is no `subQuery` in the parameters, it is set to …

fix: fix param errors when navigating between the same pages

---

package.json
src/components/HtmlView.js
yarn.lock

- integrated the plugin required for `iframe` after the `rn-render-html` update
- added `0.99` value to `iframe`'s opacity to solve the crashing problem on android
SVA-942
[iframe Plugin](https://github.com/native-html/plugins/tree/rnrh/6.x/packages/iframe-plugin#readme)
|before - ios|after - ios|
|--|--|
|before - android|after - android|
|--|--|

feat(iframe): add iframe plugin

---

src/components/HtmlView.js
src/components/StorySection.js
src/components/Text.js
src/config/styles/html.js
src/config/styles/index.js

- edited according to arrow function format to be able to use `useContext` in html style
- updated `RegularText` to arrow function format to be able to replace text using `RegularText` `styled-component` with bold font
- updated `RegularText` to `RegularTextStyledComponent` to use `RegularText` `styled-component`
- updated `styles.html` in `HtmlView` because html style was updated to arrow function format
- added `fontFamily` style for the `p` tag to `StorySection` since the `p` tag is inside the `div` tag and uses the style of the `p` tag as a priority
- added `bold` or `regular` `fontFamily` option to all text using html style according to `isBoldTextEnabled`
SVA-886
|before (home screen)|after (home screen)|before (news screen)|after (news screen)|
|--|--|--|--|
|before (POI …

feat(accessibility): add bold option to all text styles

---

src/queries/mediaContent.js
src/queries/waterTemperature.js

- returned `undefined` according to `response.status` to resolve the json parse error caused by the water widget server not responding

fix: solve json parse error

---

src/components/survey/SurveyAnswer.tsx

- added opacity instead of `fadeStyle` to set  the opacity of the options of the finished  survey without any user-selected answer
SVA-928
|active survey|finished and one option selected survey|finished survey with more than one option selected|finished survey with no options selected|
|--|--|--|--|

feat: change the opacity of the options in finished surveys

---

src/components/Radiobutton.js
src/components/survey/SurveyAnswer.tsx

- added `disabled` prop so that if a survey is over, the poll options cannot be selected with `RadioButton`
- added `disable` prop to `RadioButton` to prevent clickability
- alphabetised `RadioButton`'s props
SVA-928

fix: click problem for inactive survey

---

__tests__/components/Wrapper.test.js
__tests__/components/__snapshots__/Wrapper.test.js.snap
src/components/BB-BUS/TextBlock.js
src/components/CardListItem.js
src/components/Checkbox.js
src/components/OrientationAwareIcon.tsx
src/components/Wrapper.js
src/components/map/Map.tsx
src/config/device.js

- added `isPad` to `device.js` to recognise whether the app is running on a tablet or a phone
- added `isPad` prop to `WrapperLandscape` to overwrite side padding on tablet
- in this way the white bars on the sides are removed
SBB-6
|before|after|
|--|--|

feat: delete the white bar on the edges

---

src/screens/IndexScreen.js

- added `RegularText` and `Button` inside `ListHeaderComponent` to appear at the top of the event list
- added controls so that it does not appear in other lists and the event list does not appear in calendar mode
- added extra `url` and `buttonTitle` controls for `Button` so that only text can be added according to the request
- added `useOpenWebScreen` to redirect within the application without opening any other browser
- added `eventListIntro` from `sections` section in server
SVA-951
|before|after|after (without button)|after (calendar mode)|
|--|--|--|--|

feat: add an intro text above the event list

---

src/components/VersionNumber.js

- changed the color of the version code to `darkText` if the user has activated the `Reduce Transparency` setting via accessibility to increase the contrast difference
SVA-872
|reduce transparency off|reduce transparency on|
|--|--|

feat(accessibility): add accessibility style for version code

---

src/components/Switch.js

- changed the `ios_backgroundColor` to `overlayRgba` when `Reduce Transparency` is turned on to achieve a contrast ratio of at least 3:1 between the background of the switch and the background of the application
SVA-873
|reduce transparency off|reduce transparency on|
|--|--|

feat(accessibility): change background colour of switch

---

src/components/Chat.js
src/screens/volunteer/VolunteerIndexScreen.tsx

- added orientation lock to the chat screen to resolve the half-screen display that occurs after turning the screen sideways while viewing any image on the chat screen
- added `useFocusEffect` to `VolunteerIndexScreen`  screen to work when navigating back from  chat page and remove orientation lock
SVA-768

fix: orientation error on chat screen

---

src/components/weather/HourlyWeather.tsx

- updated the background color to `primary` and `RegularText` to `lightest` if `isReduceTransparencyEnabled` is `true` to increase contrast in the hourly weather section
SBB-24
|before|after|
|--|--|
|background contrast|background contrast|
|text contrast|text contrast|

feat(accessibility): increase contrast for hourly weather

---

src/auth.js
src/helpers/volunteerHelper.ts

- added `try/catch` inside the `isTokenValid` function because
we cannot extract `ACCESS_TOKEN_EXPIRE_TIME` data from
`SecureStore` after the update
- getting the token fails, but the application gets stuck here because of await.
`try/catch` prevents it from getting stuck. since the token is deleted, it is recreated
and added to the `SecureStore`
- added `try/catch ` to `SecureStore` items used for volunteer so
that the data in the application can be loaded properly
- added `ACCESS_TOKEN_EXPIRE_TIME` constant because we use more than one in the code
SVA-704

fix: solve android app hanging on splash screen error after update

---

src/auth.js
src/helpers/volunteerHelper.ts
src/pushNotifications/PermissionHandling.ts

- added `setNotificationChannelAsync` function to `handleSystemPermissions`
function because it is necessary to create a notification channel before creating
a token with android 13
SVA-1000
Expo Doc. : https://docs.expo.dev/versions/latest/sdk/notifications/

fix: notification problem for android

---

src/components/wasteCalendar/WasteReminderSettings.tsx
src/jsonValidation/reminderSettingsValidation.ts
src/types/WasteCalendar.ts

- updated the types of `city` and `zip` before validation to prevent them
from coming from the server with different types
- added to `WasteCalendar` types to use `ReminderSettingJson` from anywhere
SVA-1028
It was not possible to create a new reminder because of a previously saved reminder. The reason for this problem is that the types here are different from what we expected.
**Difference between data**
|with `city` & `zip`|without `city` & `zip`|
|--|--|

fix(waste calendar): the type problem in the waste calendar reminder

---

src/components/form/Input.tsx

- added the `inputAccessibilityBorderContrast` style so that the borders of inputs have a better contrast ratio with the background after turning on `Reduce Transparency` in accessibility settings
SBB-29
|Reduce Transparency off|Reduce Transparency on|
|--|--|

feat: change input border color

---

src/components/Checkbox.js
src/screens/FeedbackScreen.js

- added `marginTop` to the `Checkbox` with `checkboxContainerStyle` because the checkbox appears above the input
- added `containerStyle` prop to checkbox
- sorted checkbox's props alphabetically
SVA-1029
|before|after|
|--|--|
|before|after|
|--|--|

fix(feedback): checbox appearing above input

---

src/components/Calendar.tsx

- added `ListComponent` to show event list under calendar
- added `globalSettings` to set whether to show the list and how many dots to show in the calendar
- added event query to show the events of the selected day in the calendar in the list if the `subList` value in `globalSettings` is `true`
- added to update the `queryVariable` instead of redirecting to the `Index` screen after clicking a day in the calendar if the `subList` value is set to true on the `globalSettings`
- added as prop instead of `selectedDay` variable in `getMarkedDates` function to mark the selected day in calendar
- added `buildListItems` function to properly parse the selected day's event data in the list
- added `dotCount` and overridden `MAX_DOTS_PER_DAY` if there is `dotCount` value in `globalSettings` to show …

feat(calendar): add a list under the event calendar

---

src/helpers/linkHelper.js

- deleted spaces in links because the links could not be opened by the application due to spaces in some links
SVA-1036

fix: remove spaces in the link

---

src/components/IndexFilterWrapperAndList.js
src/components/ListSettingsItem.js
src/config/texts.js

- added `menuItem` instead of tabs `AccessibilityLabel` in `ListSettingsItem` to make it more understandable
- replaced `a11yLabel.drop` in `IndexFilterWrapperAndList` with `a11yLabel.tabs` because it was `undefined`
SBB-55

refactor: fix accessibility labels

---

src/components/Results.tsx

- added `AccessibilityProvider` to `SingleResult` to use `isReduceTransparencyEnabled` property
- added `opacity` and `backgroundColour` change depending on `isReduceTransparencyEnabled` to increase contrast in survey results
- added border to `baseBarStyle`
SBB-26
| isReduceTransparencyEnabled on | isReduceTransparencyEnabled off |
|--|--|

feat: increase the contrast of survey results

---

src/screens/WasteCollectionScreen.js

- added `hideResults` prop to `Autocomplete` component to hide street results according to `inputValue` and `isStreetInputFocused` data
- added `keyboardShouldPersistTaps` property to `flatListProps` so that the data in the list can be selected without closing the keyboard
- added `onBlur` to the street `Autocomplete` component to change the state to false after selecting data from the list
- removed the if control from the `onFocus` prop in the `Autocomplete` component to be able to change the state value
SVA-833

feat: hide results based on input data

---

src/screens/WebScreen.js

- changed `applicationNameForUserAgent` to `undefined` for bbnavi website because bbnavi prevents the website from opening
BBNAV-321

fix: resolve the error preventing the bbnavi website from opening

---

src/screens/WasteCollectionScreen.js

- updated `height` in `flatListProps` to `undefined` if city is selected to fix a bug where the `AutoComplete` list would remain open after a city search because `height` had not changed
SVA-833
|before|after|
|--|--|

fix: autocomplete list not closing problem

---

src/components/Calendar.tsx
src/components/EventList.js
src/screens/IndexScreen.js

- added `refetch` to refresh the data in the list after selecting any day from the calendar
- added `fetchPolicy` for `refetch` to work
- added `loading` control to the `data` props of `ListComponent` to show the user that the data has been refreshed
SVA-665

fix: solve serial events display error in the list

---

src/screens/WasteCollectionScreen.js

- added not to show the results if `inputValueCitySelected` is `true` to the city `Autocomplete` component to solve the problem of the space between the two inputs that occurs if there are more suggestions related to the selected city name after a place is selected from the city input
SVA-833
|Android before|Android after|Android before|Android after|
|--|--|--|--|
|iOS before|iOS after|iOS before|iOS after|
|--|--|--|--|

fix: a space error between two inputs

---

src/config/texts.js
src/hooks/surveyHooks.ts

- added alert to `submitSelection` function to show alert after answering the survey
- added new text to text file to show in alert
SVA-1059
|before|after|
|--|--|

feat: show alert after the survey is answered

---

__tests__/helpers/openingHoursHelper.test.ts
jest-setup.js
src/components/screens/OpeningTimesCard.js
src/helpers/openingHoursHelper.ts

In the future, TMB pois will have adjusted dates for specific cases, being returned from the main server with year 1970. This way we can identify them to adjust checking opening time and rendering.
|before|after|
|---|---|
|![Simulator Screen Shot - iPhone 12 - 2023-07-03 at 17 20 55](https://github.com/smart-village-solutions/smart-village-app-app/assets/1942953/2ef71428-5466-4953-81b5-70adb3dd61f1)|![Simulator Screen Shot - iPhone 12 - 2023-07-03 at 17 18 41](https://github.com/smart-village-solutions/smart-village-app-app/assets/1942953/2f49e93b-2780-44be-8c5d-a01bef4bf0b3)|
In order to test with the POI Eiscafé "Zur Postmeile" you need to set the `TMB_YEAR_TO_PARSE` to 2020.
SVA-985

feat(opening times): dates with parsed TMB year

---

eas.json

- updated `releaseChannel` in `eas.json` to `channel` so that the `expo-updates` package can work
SVA-1091
even if we don't use the `expo-updates` package, it needs to be configured to prevent the application from crashing on android.
in order for the expo-updates package to work with eas, the `releaseChannel` in `eas.json` had to be replaced with `channel`.
expo doc.: https://docs.expo.dev/build/updates/
expo doc.: https://docs.expo.dev/eas-update/eas-cli/?redirected
**channel**: The channel is a name we can give to multiple builds to identify them easily. [Learn more](https://docs.expo.dev/eas-update/how-it-works/?redirected)
This field only applies to the EAS Update service, if your project still uses Classic Updates then use the …

fix: android crash

---

package.json
yarn.lock

- updated because 2 packages needed to be updated after running the `npx expo-doctor` command

chore: update the necessary packages for expo

---

app.json
config-plugins/withAndroidMailQueriesAndWhatsappPackage.js

- added `withAndroidMailQueriesAndWhatsappPackage` config for `mailto:` and `whatsapp:` custom link in webview to work on Android devices
SVA-1047
In order to run any custom link inside the webview, it is necessary to update the native files of Android. With Expo config-plugins, I updated the AndroidManifest.xml file in the Android folder (android/app/src/main/AndroidManifest.xml) so that the application can be redirected with `mailto:` and` whatsapp:` links.
I got help from the following issue.
[React-Native Issue](https://github.com/facebook/react-native/issues/30909)
To try it out:
1. select branch and run `yarn prebuild` command
2. connect the android device to the computer with the cable, run the `yarn android -d` command and select your device
3. while waiting for the build to …

feat: integrate custom links for android

---

src/config/texts.js

- adjusted the polish texts of the survey module:
commentSubmissionAlert: 
de: 'Ihr Kommentar wird nun redaktionell geprüft und schnellstmöglich veröffentlicht.'
pl: 'Twój komentarz zostanie teraz zweryfikowany przez redakcję i opublikowany tak szybko, jak to możliwe.'
dateEnd:
de: 'Abschluss der Umfrage:'
pl: 'Zakończenie ankiety:'
dateStart: 
de: 'Start der Umfrage:'
pl: 'Rozpoczęcie ankiety:'
multiSelectPossible: 
de: 'Mehrfachantwort möglich.'
pl: 'Wybór wielokrotnych odpowiedzi jest możliwy.'
SVA-1085

refactor: adjust polish texts

---

src/components/augmentedReality/AugmentedRealityView.js
src/config/consts.js
src/config/device.js

- added `totalMemory` value to `device.js` to see the `RAM` information of the device and used `totalMemory` in `expo-device` package
- added `GB_TO_BYTES` section to `consts.js` because the `totalMemory` property gives us RAM in bytes and therefore we need to know gb in bytes
- removed `spot` and `quad` (shadow) to optimise AR for devices with less than 2 gb of RAM
SVA-1073
|iPhone 7 (shadowless and spotless)|iPhone 13 Pro Max (shaded and spotlighted)|
|--|--|

fix: optimise augmented reality

---

__tests__/helpers/openingHoursHelper.test.ts
src/components/screens/OpeningTimesCard.js
src/helpers/openingHoursHelper.ts
src/queries/pointsOfInterest.js
src/types/OpeningHour.ts

the main server removed the 1970-hack and introduced a `useYear` flag, that we will be able to use in order to render without the year if false
SVA-985
| `useYear = true`| `useYear = false`|
|---|---|
| ![image](https://github.com/smart-village-solutions/smart-village-app-app/assets/1942953/fe81a658-ccdf-49fd-8d57-44f57a224ccc) | ![image](https://github.com/smart-village-solutions/smart-village-app-app/assets/1942953/41e98d63-5cf5-4aa9-9c44-128086ec4679) |

feat(opening times): respect `useYear` instead of 1970-hack

---

src/components/widgets/EventWidget.tsx
src/screens/HomeScreen.js
src/types/WidgetProps.ts

- added editing the `queryVariables` `limit` in `IndexScreen` for all sections shown in `HomeScreen` via `globalSettings`
- added default limit value of all sections as 15
- added `queryVariables` limit when going to the event screen via widget
- added default limit value as 15 on the event screen navigated using widget
- added `limit` to `WidgetProps` to prevent type error
SVA-1119
---
make the following adjustments to the `globalSettings` to try the feature.
the `queryVariables` required to go to the Event screen with the "Alle Veranstaltungen anzeigen" button on the `HomeScreen`
```
"sections": {
...
"limitEvents": 20,
"limitNews": 20,
"limitPOI": 20
...
},
```
to go to the Event screen with the widget `queryVariables`
```
{
"widgetName": "event",
"additionalProps": {
...
"limit": 20 …
```

feat: add query variables that can be set from the server for the event

---

src/screens/IndexScreen.js

There is a new global setting that allows hiding the filter for opening times, which results in an index screen without that:
SVA-1127

feat: add setting to show or hide filter by opening times

---

src/screens/IndexScreen.js

- deleted the component that is not shown according to the `showFilterByOpeningTimes` control to fix the problem of the switcher appearing twice after `showFilterByOpeningTimes` is set to `true` in `globalSettings`
SVA-1127
|before - showFilterByOpeningTimes:true|after - showFilterByOpeningTimes: true|before - showFilterByOpeningTimes: false|after - showFilterByOpeningTimes: false|
|--|--|--|--|

fix: prevent the open only switcher from being duplicated

---

src/components/CategoryList.js

- added `queryVariables.ids` control with `category.parent` control in `CategoryList.js` to list subcategories when going from HamburgerMenu or `staticContent` to `IndexScreen` with `ids` `queryVariables`
- changed `CategoryList`'s props to alphabetical sorting
SVA-1115
For this feature to work, you need to write the `ids` array in `queryVariables` in the navigation to `IndexScreen`. The numbers in the ids array represent `categoryIds`. In this way subcategories can be listed in `IndexScreen`.
staticContent:
```
{
"title": "GastronomiemitUnterkategorie",
"routeName": "Index",
"icon": "ImageUrlFromMinio",
"iconName": "orIconNameFromExpoIcons",
"params": {
"query": "categories",
"queryVariables": {
"ids": [
89,
90,
95
]
},
"rootRouteName": "categories",
"title": "Categories"
}
},
``` …

feat: list subcategories on index screen

---

src/components/widgets/SurveyWidget.tsx
src/screens/SurveyOverviewScreen.tsx
src/types/WidgetProps.ts

- added `HtmlView` inside `ListHeaderComponent` to `SectionList` to show html on the survey list
- added `Props` type to remove the type error of the `route` prop in `SurveyOverviewScreen`
- added as param to use the `additionalProps.htmlName` added to the survey widget in `globalSettings` on the `SurveyOverview` screen
- added `useStaticContent` to get the html content from the main server added to `additionalProps.htmlName` to show html in `HtmlView`
- added `htmlName` type as string to `WidgetProps` to avoid type error
SBB-109
|before|after|
|--|--|

feat: add html section above the survey list

---

src/helpers/parser/listItemParser.js

- added a check to the `subtitle` section in `listItemParser` to not show the date in the list if it is a `Deadline`
SVA-710
|before|after|
|--|--|

refactor: remove the date from the list and sort the list alphabetically

---

src/SettingsProvider.js
src/config/navigation/config.ts

- added the logic to switch the navigation type between drawer and tabbar through the server config
- added `navigation: {}` to `SettingsProvider.js` to extract the navigation type from the server config
- added `useSettingsContext` to `SettingsProvider.js` to get the navigation type in `config.ts`
SVA-1117
- if you want to quickly switch between the tab and drawer navigation without editing the server config file edit in `src/config/navigation/config.ts`, line 14, `!= "drawer"` to the desired option

refactor: ability to switch navigation through server config

---

App.js
src/screens/DetailScreen.js
src/screens/HomeScreen.js
src/screens/HtmlScreen.js
src/screens/IndexScreen.js

- reduced `auth()` refreshs by calling the `auth()` function when the app returns to the foreground from the background or from the inactive `AppState` by checking the apps `AppState` globally through `App.js`
- `auth()` function is already being called at every app start from the closed state in `src/index.js`
- removed now unnecessary and before insufficient `auth()` calls and related imports from `DetailsScreen.js`, `HomeScreen.js`, `HtmlScreen.js`, `IndexScreen.js`
SBB-91

refactor: reduce auth refreshs

---

src/screens/IndexScreen.js

- added `poiListIntro` to the destructured `sections` object to fetch intro text for points of interest
- introduced `htmlContentName` and `htmlContent` to fetch and display HTML content conditionally for points of interest
- modified `ListComponent` to include the new HTML content as a header when displaying points of interest
to be able to try this feature, please edit the `sections` section in `globalSettings` as follows.
```
"poiListIntro": {
"Bildung": "noticeboardMainContent"
},
```
the key in the object of `poiListIntro` must belong to a category. In this way, if you go to the correct poi category screen, the html content here will be automatically displayed above the poi list. then you should create the htmlContent that we named here on the main server.
SBB-110
|bildung category …

feat: add dynamic intro content for points of interest list

---

src/config/navigation/defaultStackConfig.tsx
src/config/navigation/tabConfig.tsx
src/config/texts.js
src/types/Navigation.ts

- deleted `companyTabConfig` tab navigation as we don't need it
- added `pointOfInterest` screen as the 3rd tab because we want to see it in tab navigation
- added `EventScreen` as the 4rd tab because we want to see it in tab navigation
- updated `texts.js` to show the title and tab name of `EventScreen` and `pointsOfInterest` screens
- sorted `tabBarLabel` alphabetically to improve readability
SVA-1116
to try this feature, please update the codes in `config.ts` according to the tab navigation structure
|before|after|POI Screen|EventScreen|
|--|--|--|--|

refactor: change navigation structure

---

src/components/screens/Service.tsx
src/components/screens/ServiceTile.tsx

- if tiles are not 1:1 aspect ratio, we can now have a factor to properly size them
- `tileSizeFactor` can be set through `settings` in global settings
|without factor|with factor|
|---|---|
|<img width="376" alt="image" src="https://github.com/smart-village-solutions/smart-village-app-app/assets/1942953/b073f7d4-e917-4d3a-bc89-115644615ea0">|<img width="376" alt="image" src="https://github.com/smart-village-solutions/smart-village-app-app/assets/1942953/22dd57d2-d43d-4fb4-b68d-0b1603a17356">|
MQGB-27

feat: add ability for a factor to size tiles

---

src/components/screens/AvailableVehicles.tsx
src/components/screens/PointOfInterest.js
src/components/screens/index.js
src/config/texts.js
src/queries/pointsOfInterest.js

- replaced displaying only the number of bikes with a list of available vehicles
- implemented dynamic `SectionHeader` title based on the vehicle type
- added prop 'category' to replace 'categoryName'
- updated the props passed to `AvailableVehicles` to pass the whole `category` object instead of just the name
- code cleanup, including the removal of unused imports
- added state management using `useState` and `useEffect` hooks in `AvailableVehicles`
- implemented fetching of available bike data based on `freeBikeStatusUrl`
- added new props types `AvailableVehiclesProps` to handle fetched data
- updated UI to display the number of available bikes in the station
- included a new text label for 'bike' in `texts.js`
- added the `AvailableVehicles` component for displaying available vehicle …

feature: show available vehicles in detail screen

---

src/components/map/LocationOverview.tsx
src/components/map/Map.tsx

- removed the hide function from the preview feature on the map screen
MQGB-34
|before|after|
|--|--|

refactor: remove hide button in preview

---

src/queries/eventRecords.js

- added `description` to `eventRecords` query to fix the error of showing the link instead of the description text when a link is added for the organiser
SVA-1166
|before|after|
|--|--|

fix: not showing a description when adding a link to the organiser

---

src/components/map/Map.tsx

- if we have a given icon name, we want to render it individually on top of our location pin
- except for `ownLocation` which already is a kind of location pin
- added styles to render the icon on top of the location pin smaller and positioned in the center top of the location pin with different color to be visible
|heartFilled|check|home|
|---|---|---|
|<img width="376" alt="image" src="https://github.com/smart-village-solutions/smart-village-app-app/assets/1942953/85fc6cbd-f93d-4758-9c66-5b2f26d00b36">|<img width="373" alt="image" src="https://github.com/smart-village-solutions/smart-village-app-app/assets/1942953/16a76e07-810b-40ca-9d71-c94b9ac2c1d7">|<img width="375" alt="image" src="https://github.com/smart-village-solutions/smart-village-app-app/assets/1942953/fb55adb3-6e64-4315-aa4f …

feat:(map icons): render two icons in some cases

---

src/components/screens/TimeTables.tsx
src/screens/DetailScreen.js

- fixed the `date` value with state, which causes the `DetailScreen` to re-render when the location information is active
- renamed `date` to `today` for clarity
- created today value in `TimeTables` with moment to ensure code integrity
MQGB-54

fix: solve detail screen rerender problem

---

src/components/Disturber.tsx
src/components/augmentedReality/AugmentedReality.js
src/components/map/LocationOverview.tsx
src/components/map/Map.tsx
src/components/oParl/Location.tsx
src/components/screens/AvailableVehicles.tsx
src/components/screens/PointOfInterest.js
src/components/screens/TimeTables.tsx
src/components/screens/consul/Proposals/ProposalDetail.js
src/components/settings/LocationSettings.js
src/config/Icon.tsx
src/icons/location.js
src/icons/ownLocation.js
src/screens/ConstructionSiteDetailScreen.js
src/types/Map.ts

- changed to render a map icon from our icon library instead of fixed location svg icons
- created `MapIcon` with default `'location'` as icon to be able to remove all occurrences across the code base where the location icon was set
- added `anchor` in `MapMarker` that was missing until now, to properly position icons on map with pin point at the bottom of location icons
- removed icon anchor const exports as we do not need them individually
- added `OwnLocation` in our `Icon` library to be accessible with `Icon[_upperFirst(iconName)]`
- fixed type issues with `Icon[_upperFirst(iconName) as keyof typeof Icon]`
MQGB-34

refactor(map icons): use from `Icon` to be flexible

---

src/navigation/AppStackNavigator.tsx
src/navigation/DrawerNavigator.tsx

- moved styles to `drawerStyle` inside `screenOptions` of the Drawer in `DrawerNavigator.tsx`
and refactored with orientation provider
- removed `drawerType` of the Drawer in `DrawerNavigator.tsx`,
since the default for iOS is now set to `slide` and to `front` for other plattforms:
https://reactnavigation.org/docs/drawer-navigator/#drawertype
- linted `AppStackNavigator.tsx`
SVA-1130

refactor:  additional changes for react navigation 6.x

---

src/components/screens/Overviews.js

- added `switchBetweenListAndMap` control to `useLayoutEffect` to fix the problem of not being able to go back in navigation when `top-filter` is on in POI list
SVA-1181

fix: the bug of not navigating back from map view

---

app.json
src/pushNotifications/PermissionHandling.ts

- added `projectId` to `getExpoPushTokenAsync` because it needs `projectId` for notifications due to the new update of expo
- added `projectId` to `app.json` for use in `getExpoPushTokenAsync`
SVA-1180

fix: the problem that notifications cannot be activated

---

src/components/Calendar.tsx
src/components/EventList.js
src/components/VerticalList.js
src/components/screens/EventRecords.js
src/components/screens/Overviews.js

- updated `sectionedData` to be overwritten only with new data to fix the bug where `sectionedData` is constantly being rebuilt
- added `removeClippedSubviews` to `SectionList` to improve scrolling performance
- added `refreshing` state to ensure that the list is refreshed when new data arrives
- reduced the number of items to be loaded at the beginning of the list from 20 to 15 because the limit of the query is 15
- added `uniqBy` to the return section of the `fetchMoreData` function according to id to fix the error of showing the same data more than once in the `EventList`, `Overviews` and `Calendar` caused by multiple executions of the `fetchMoreData` function
- the list was still fetching in the background even if the calendar with its own list is visible
- changed the offset …

fix: new data not loading into the list

---

src/SettingsProvider.js
src/components/IndexMapSwitch.js
src/components/ListSettingsItem.js
src/components/map/LocationOverview.tsx
src/components/settings/LocationSettings.js
src/config/navigation/config.ts
src/index.js
src/navigation/Navigator.tsx
src/screens/MapViewScreen.js

the problem was, that changing settings context triggered a rerendering of the navigation as the config file relied on it. the refactoring made passing the navigation type on initialising the application without the need of reading from the settings context.
also there are some refactorings to unify the code and understand things better.
SVA-1130

fix(navigation): configs without `useContext` and refactorings

---

src/components/EventList.js

- added checking if `sectionedData` is empty to `EventList` to fix an issue where `SectionList` would crash the application if `sectionedData` was an empty array before creating the list for android
SVA-1114

fix: event list screen app crashes on android devices

---

src/screens/SUE/SueMapScreen.tsx

- added `SueImageFallback` to show in list item if there is a report without image in map view
SUE-4
|with image|without image (before)|without image (after)|
|--|--|--|

feat(sue): add `SueImageFallback` to reports without image

---

src/components/SUE/report/SueReportDescription.tsx
src/components/SUE/report/SueReportLocation.tsx
src/components/SUE/report/SueReportUser.tsx
src/components/consul/selectors/ImageSelector.js
src/components/map/Map.tsx
src/components/settings/LocationSettings.js
src/config/texts.js
src/helpers/parser/sueParser.js
src/queries/SUE/requests.tsx
src/screens/SUE/SueReportScreen.tsx

- removed `Screen` from `texts.sue.reportScreen` as it is not necessary
- resized the preview of the image after selecting an image on the report screen
- updated the background color of the delete button in the image preview on the report screen as `placeholder`
- removed undefined checks in `sueParser` as unnecessary
- added a requirement to some inputs to prevent the server from sending reports with incomplete information
- lastName & firstName & street & homeNumber & zipCode
- added new alerts and controls to `SueReportScreen` to show which input needs to be filled when the report is sent with unfilled inputs
- added `DefaultKeyboardAvoidingView` to `SueReportScreen` to make inputs appear above the keyboard when clicked on
SUE-7
|image preview with new style|inputs with keyboard …

refactor(sue): adjustments for report screen

---

src/screens/SettingsScreen.js

- fixed an issue that caused the application to crash when the AR models download tab on the settings screen in applications with AR feature was selected, navigating back and re-entering the settings screen
SVA-1195
The reason for the problem is that in applications with AR feature and devices that support AR feature, we add the filter required for AR to `INITIAL_FILTER` later. For this reason, `selectedFilterId` cannot be found and the application crashes. Therefore, if `selectedFilterId` is `undefined`, the AR filter is made `true`.

fix(ar): app crashes in settings screen

---

src/components/CardListItem.js

- added controls to prevent the app from crashing if the required data is not available in the `CardList` view
SVA-1227
|text list|text with image|card list|
|--|--|--|

fix: add control to prevent the app from crashing

---

src/screens/SUE/SueListScreen.tsx

- deleted the reverse property from `listItems` and added it to the data prop of `ListComponent` to prevent the list from changing order when the pull to refresh function is executed

chore: protect the list from changing when refreshing

---

src/components/augmentedReality/AugmentedReality.js
src/components/settings/ListSettings.js
src/components/settings/MowasRegionSettings.tsx
src/components/settings/PermanentFilterSettings.tsx
src/components/settings/index.js
src/config/texts.js
src/pushNotifications/TokenHandling.ts
src/reducers/index.ts
src/reducers/mowasRegionalKeysReducer.ts
src/screens/SettingsScreen.js

- added MoWaS settings entry to be able to de-/select regions to get news and notifications for
- added new token handling for MoWaS regional keys in the way we already do it for data providers
- added reducer like the one existing for data providers to handle actions when toggling in settings
- cleanup & refactorings
to see and have the MoWaS section in settings a `globalSetting` needs to be added on the main-server, for example:
```
"mowas": {
"regionalKeys": [
{
"name": "Internal Development",
"rs": "999999999999"
},
{
"name": "Angermünde",
"rs": "120730008008"
},
{
"name": "Amt Schlieben",
"rs": "120625209445"
}
]
},
```
SVA-1149
|settings overview|MoWaS settings|
|---|---|
|![Simulator Screen Shot - iPhone 14 - 2023-10-18 at 16 15 …

feat(settings): MoWaS regional keys handling

---

src/components/Disturber.tsx
src/components/ImagesCarousel.js

- added `ImagesCarousel` component instead of `Image` component to show when more than one image is added to disturber
- added the ability to add a link directly from the image to disturber
- changed the duration of the cycle of the disturber carousel on the server
- added `isDisturber` prop to `ImagesCarousel` to not show pause button in carousel
SVAK-20
|first image with link|second image without link|third image without link|
|--|--|--|

feat(disturber): add multiple images to disturber

---

src/components/TextListItem.tsx
src/hooks/listHooks.js

- added `EventSectionHeader` to `LIST_TYPES.CARD_TEXT_LIST` to fix the problem of header not appearing in `EventList` in text list type with big picture
SVA-1200
|before|after|
|--|--|

feat: add `EventSectionHeader` for text list with big picture

---

src/components/SUE/report/SueReportUser.tsx
src/config/texts.js

- added `Link` prop to `Checkbox` component in `SueReportUser` to add a clickable link in the checkbox on the report screen
SUE-16

feat: add link to checkbox on report screen

---

src/components/DeleteHeader.tsx
src/components/HeaderRight.tsx
src/components/index.js
src/config/texts.js
src/screens/SUE/SueReportScreen.tsx

- added the ability to write data to the device's memory with the `storeReportValues` function to prevent deletion of data when the user fills in a report screen, returns to the previous screen or closes and reopens the application
- added `setValue` in `readReportValuesFromStore` to add memorised data to inputs
- added delete button with `HeaderRight` to the right of the header to delete all saved data if any
- added `DeleteHeader` component to add delete button to the right of the header and added `withDelete` prop to `HeaderRight`
- added that if the report is sent successfully or if the user wants to delete the saved data, the `resetStoredValues` function is used to delete the saved data
SUE-28
|with Delete button|
|--|

feat: store data on the report screen

---

src/components/TextListItem.tsx
src/helpers/parser/listItemParser.js
src/queries/index.js
src/queries/types.ts
src/queries/vouchers.js
src/screens/Voucher/VoucherIndexScreen.tsx

- added `GET_VOUCHERS_CATEGORIES` query to list only the category information of the voucher
- added `parseVouchersCategories` parser to `listItemParser` so that we can show the category list of the voucher in the format we want
- changed query in `parseListItemsFromQuery` to parse voucher category in `VoucherIndexScreen`
- added control in `ListHeaderComponent` to show only query value in `Vouchers`
- added count to `TextListItem` to show how many vouchers are in which category of the voucher on the list
SVAK-35
|VoucherIndexScreen `query === vouchers`|VoucherIndexScreen `query === vouchersCategories`|
|--|--|

feat: add voucher categories list

---

src/config/texts.js
src/helpers/parser/listItemParser.js
src/screens/Voucher/VoucherIndexScreen.tsx

- set `showFilter` param to `false` in `parseVouchersCategories` because we don't need dropdown filter in categorised voucher list
- added `categoryId` to `queryVariables` to filter vouchers by category id
- updated the header title of the categorised list screen to `offersCategories` instead of category name
SVAK-35

feat: remove dropdown menu of categorised list

---

src/components/vouchers/VoucherList.tsx
src/helpers/parser/listItemParser.js
src/queries/vouchers.ts
src/screens/Voucher/VoucherDetailScreen.tsx

- updated `vouchers` query with `genericItems` as `vouchers` query is no longer in use
- added controls to prevent the application from crashing if the data is undefined
SVAK-35

feat: integrate generic item query

---

src/components/map/Map.tsx

- added `doubleTileSize` prop to `UrlTile` component to solve the pixelation problem of the map in android
- https://github.com/react-native-maps/react-native-maps/blob/master/docs/tiles.md
SUE-27
Since this feature is standard on iOS, there is no pixelation problem on the iOS platform. In order to solve the pixelation problem on Android, doubleTileSize has been activated only for android devices.
|before|after|
|--|--|

fix: map pixelation problem on android

---

package.json
yarn.lock

- added version 14 of the `@expo/vector-icons` package to be able to use the newly added icon packages
https://github.com/expo/vector-icons
icon packages:

chore: add `@expo/vector-icons` package

---

src/screens/SUE/SueReportScreen.tsx

- added `isLoadingStoredData` to `SueReportScreen` to fix the bug where stored images could not be deleted because the `Image` component renders before the stored images are read from the store, and ensured that the `Image` component does not render before the stored images are read from the store
SUE-28

fix: failure to delete stored image file

---

src/components/consul/selectors/ImageSelector.js
src/config/texts.js
src/hooks/imagePicker.ts

- added `useCaptureImage` to `imagePicker` to take a photo with the camera
- added alert to select image from gallery or camera
- added `useCaptureImage` to be able to run the camera
- added `imageFunction` prop to `imageSelect` function to avoid code repetition and made it work with the function sent with the prop
- updated `imageSelect` `onPress` in `Button` component with `secImageSourceAlert`
SUE-31
|image source select alert|camera screen|image edit screen|show a photo taken from the camera|
|--|--|--|--|

feat: take a photo with the camera

---

src/components/SUE/report/SueReportLocation.tsx
src/components/map/Map.tsx

- reverted `bottom` in `mapPadding` to fix bounce bug when selecting location on map
- added `OpenStreetMap` text only for android platform to cover the google logo that appears on android devices
- added `latitudeDelta` and `longitudeDelta` values to solve the delta error that causes the application to crash when the location is selected from the map on android devices
SUE-32
|before|after|
|--|--|

fix: app crashes when selecting location from map

---

src/components/CardListItem.js
src/components/Chat.js
src/components/Image.js
src/components/TextListItem.tsx
src/components/consul/selectors/ImageSelector.js
src/components/screens/ServiceTile.tsx
src/components/weather/DailyWeather.tsx
src/components/widgets/DefaultWidget.tsx
src/components/widgets/WeatherWidget.tsx

- added `childrenContainerStyle` instead of `containerStyle` to `Image` component in `ServiceTile` to increase the space between tiles
- added `childrenContainerStyle` prop to avoid style confusion in `Image` component
SVA-1256
|before|after|
|--|--|

fix: tile appearance

---

src/config/Icon.tsx

- updated `Icon.tsx` to resolve the issue of some icons not loading after expo updated the icon package
the icons of each application upgraded to version 3.3.4 with this update should be checked.
|before|after|
|--|--|

chore: update icons

---

src/queries/SUE/requests.tsx
src/screens/SUE/SueListScreen.tsx
src/screens/SUE/SueMapScreen.tsx

- added possibility to pass params to the fetch for requests
- refactored `useQuery` to `useInfiniteQuery` to be able to paginate
- set limit to 10000 to ensure loading "all" requests, as we cannot use pagination, because the response isn't sorted with latest first
- we need to reverse the result manually, which contradicts infinite scroll
- added workaround on map screen to avoid rendering problems with images
- there were images of one case shown at a different case while loading the right image
- now we will see the loading indicator after a short reload of the overlay
- fixed image component style
- moved `reverse` in the list items `useMemo` hook to avoid unnecessary renderings caused by list items not being reversed before
- renamed `selectedRequest` to `selectedRequestId` as it is …

feat(sue): update react-query usage

---

src/components/screens/Service.tsx
src/config/consts.js

- created `UMLAUT_REGEX` to detect hopeless letters that cause the application to crash when editing tile view
- changed the umlaut letters in the texts used in `draggableId` to prevent the application from crashing when organising the order of the tiles
SVA-1291

fix: unable to edit tile error

---

src/screens/SUE/SueMapScreen.tsx

- removed the `limit` and `offset` required for pagination in list view because they are not required in map view and cause the app to crash
SUE-39
`limit` and `offset` values required for pagination have been removed from the api request in the map view. When `limit` and `offset` values are in `queryVariables`, a blank page is encountered when switching from map view to list view. In order to get the data in list view, it is necessary to pull the data from the api again with pull to refresh.

fix: app crashes in map view due to pagination

---

App.js
src/screens/SUE/SueReportScreen.tsx

- added `AsyncStorage.removeItem` to the `isFontLoaded` controller in `App.js` according to the `sueReportValues` key to ensure that the saved data is deleted when the application is reopened
- created `sueReportValues` constant to prevent code repetition
SUE-48

feat: delete saved data when the application is reopened

---

src/screens/SUE/SueMapScreen.tsx

- added `CloseButton` to `SueMapScreen` to add the option to close the list item that appears after selecting any pin from the map
- added into `item.picture?.url` control so that `CloseButton` component appears on the picture and list item design is not broken
- added '72' to `colors.darkText` to make the background color of `closeButton` transparent
SUE-50
|before|after|after with image|
|--|--|--|

feat: add button to close list item in map view

---

src/screens/BB-BUS/DetailScreen.js

- added `useOpenWebScreen` to `DetailScreen` to open form links in bbbus service from web browser in application instead of browser
SVA-1299
the navigation to follow in the app to test it:
Service Tab -> HTML - Buergerservice -> Bürger- und Unternehmenservice öffnen -> Gewerbe anmelden -> Gewerbe Anmeldung (Button)

fix: links open externally instead of the application

---

src/screens/SUE/SueListScreen.tsx
src/screens/SUE/SueMapScreen.tsx

- API responds with last 90 days per default so we need to extend the requested data to a range from a very past start date
- removed pagination as we always need to fetch all data
SUE-53
example with more markers on the map:

feat(sue): fetch all requests

---

src/screens/SUE/SueReportScreen.tsx

- updated the description text with - to correct the `null` expression that occurs if the description text is not filled when sending the report
SUE-54

fix: the error that null occurs when the description text is sent empty

---

src/screens/SUE/SueReportScreen.tsx

- added `isLoadingStoredData` control to the return section to overwrite the old image when a new image is added after deleting the saved data with the button on the top right in the header and to reload the content
- updated the `setIsLoadingStoredData` value in `resetStoredValues` so that the `Content` content can be refreshed after the data is deleted
SUE-55

fix: an image reinsertion error that was deleted during the reporting process

---

src/components/SUE/report/SueReportDone.tsx
src/components/SUE/report/SueReportSend.tsx
src/components/SUE/report/index.ts
src/components/consul/selectors/ImageSelector.js
src/screens/SUE/SueReportScreen.tsx

- added `isMutationLoading` to understand when sending the report
- added `loadingTitle` and `loadingSubtitle` that can be edited from the server to show when sending the report in the `SueReportDone` component
- added `isDone` and `isLoading` props to `SueReportDone` component to check if the report is in the status of being sent to the server
- updated the `style` prop in the `Image` component with `childrenContainerStyle` to fix the style distortion bug after the image is selected in `ImageSelector`
- apdated the name of the `SueReportDone` component to `SueReportSend` for clarity
SUE-38
|report send loading|
|--|

feat: add sending report loading screen

---

src/components/filter/Filter.tsx
src/config/texts.js
src/screens/SUE/SueListScreen.tsx

- added new dropdown type filter to `filterTypes` prop to add sort feature
- added `SORT_OPTIONS` to show sorting options
- added sort feature in `listItems` function because sort feature is not supported by api
- set to switch off the filter section when the filter reset button is pressed
- changed the `isCollapsed` value to `true` first to avoid performance problems and reset the filter values after 500 milliseconds.
SUE-14
|filters with sort dropdown|list sorted by `requestedDatetime`|
|--|--|

feat: add sort feature

---

src/components/Modal.js
src/components/SUE/report/SueReportDescription.tsx
src/components/consul/selectors/ImageSelector.js
src/config/Icon.tsx
src/config/texts.js

- added `Modal` to `ImageSelector` instead of alert to show where to select the image
- added `overlayStyle` and `closeButton` props to customise the `Modal` component
- added icon for selecting photos from gallery
- updated the necessary texts for the component
SUE-52
|portrait mode|landscape mode|
|--|--|

feat: add modal to upload photos

---

src/components/SUE/report/SueReportLocation.tsx
src/config/texts.js
src/screens/SUE/SueReportScreen.tsx

- added alert to notify that if the postcode input is filled in, the city input must also be filled in to prevent the city input from being empty
- added a new alert to fill in the street input if the house number is entered
- added * for required inputs
MQGB-60
|post code alert|city alert|
|--|--|

feat: add control to fill the city input

---

package.json
src/components/DefaultKeyboardAvoidingView.tsx
src/helpers/headerHelper.ts
src/hooks/index.js
src/hooks/keyboardHeight.ts
src/screens/SUE/SueReportScreen.tsx
yarn.lock

- added the `headerHelper` to `DefaultKeyboardAvoidingView`, which is used in many parts of the code to avoid code duplication
- using `statusBarHeight` of `expo-constants` package because `react-native-status-bar-height` package cannot calculate status bar size of iPhone 14 Pro and higher models
- https://github.com/ovr/react-native-status-bar-height
- removed `react-native-status-bar-height` package from `package.json` because it is not used
- added `getKeyboardHeight` helper to detect the size of the keyboard when it is opened
- added a `View` half the size of the keyboard, which is created only when the keyboard is opened, into `ScrollView` in order to make the inputs hidden behind the keyboard visible by scrolling the screen on android devices
- wrapped all content with …

feat: show inputs above the keyboard

---

src/components/SUE/report/SueReportSend.tsx
src/screens/SUE/SueReportScreen.tsx

- increased the waiting time of the report from 1.5 seconds to 3 seconds if there is no image
- added a control to avoid waiting an extra 3 seconds because images take a long time to load
- added width value of 100% to prevent the loading gif from being clipped
SUE-38
please remember to set the version in `app.json` to `60.0.0` during testing.

feat: extend the waiting time when sending a report

---

src/components/filter/DateFilter.tsx

- added `endTimeOfDay` to include the selected `end_date` in the filter and set it to `'T22:59:59+01:00'` which is the last time of the day
SUE-14
|before|after|
|--|--|

feat: include the selected day in the filter

---

src/components/ImagesCarousel.js

- changed `Carousel`'s `autoplay` property with `carouselRef` instead of the `isPaused` control to solve the problem of starting from zero when silder is paused and then restarted
SVA-1296

fix: paused slider restart problem

---

src/screens/AppIntroScreen.tsx

- added `paddingTop` style as the size of the status bar to the `AppIntroSlider` component to solve the problem of the images on the onboarding screen appearing above the `StatusBar` on android devices
SVA-1155
I can't share screenshots because this problem doesn't occur in development mode. We can first see if the problem is solved after creating a new version.

fix: the problem of images on the onboarding appearing above the status

---

src/components/CardListItem.js
src/screens/SUE/SueDetailScreen.tsx

- added width style for the list to cover the entire screen when using the app in landscape mode while in list view
SUE-67
currently there is a problem on the API side, so the data is not being loaded. Therefore, I cannot upload before and after screenshots here. To test, switch to list view in the app and turn the phone sideways.

feat: add style for landscape mode to photos

---

src/components/ImagesCarousel.js
src/screens/SUE/SueReportScreen.tsx

- added `PORTRAIT_UP` lock to `SueReportScreen` because calculating the sizes of different steps on the report screen and scrolling at the same rate is not possible on different sized devices
- added listener to automatically set the orientation of the screen to `DEFAULT` when the user leaves `SueReportScreen`
- updated the style so that the pictures in the `ImagesCarousel` we use in `HomeScreen` can also adjust themselves according to orientation
SUE-67
please set the version in app.json to 60.0.0 for testing.
|HomeScreen before|HomeScreen after|
|--|--|

feat: disable orientation for the report screen

---

src/screens/SUE/SueReportScreen.tsx

- updated the `alertTextGeneratorForMissingData` function to prevent the report screen from moving to the next step if a selected image is higher than 10MB, since the server allows a maximum of 10MB for each image and the total image size should be maximum 30MB
SUE-63
For Test:
To download an image larger than 10MB, please follow these steps:
https://commons.wikimedia.org/wiki/File:Pizigani_1367_Chart_10MB.jpg
To test, drag the following image with a size greater than 10MB into the Simulator. Select this image from the `SueReportScreen`. Because this image is larger than 10MB, you will receive an alert that will prevent you from proceeding to the next step.
|warning|alert|
|--|--|

feat: add size limit control for each image

---

src/components/SUE/report/SueReportDescription.tsx
src/components/SUE/report/SueReportLocation.tsx
src/components/SUE/report/SueReportUser.tsx
src/config/texts.js
src/screens/SUE/SueReportScreen.tsx

- added `city` and `zipCodes` limitations that can be updated via main-server when creating a report
- added `errorMessage` which can be set via main-server as there may be different alert messages for different cities
SUE-57
please set the version in app.json to 60.0.0 for testing.
The config added to main-server is as follows. For reports that do not match the postal codes or city in this config, the next step is prevented.
the limitation can be done only with the `zipCodes` array or only with the `city`.
If the `errorMessage` value is not added to the configuration, the following message is displayed by default.
`Leider kann die Sag's uns Einfach nur Standorte der  nutzen.
```
"limitOfArea": {
"zipCodes": [
"85625"
],
"city": "kiel",
"errorMessage": "Leider kann die Sag's uns Einfach …
```

feat: add city and postcode limits to create a report

---

src/helpers/sueHelper.ts
src/queries/SUE/priorities.tsx
src/queries/SUE/requests.tsx
src/queries/SUE/requestsWithServiceRequestId.tsx
src/queries/SUE/services.tsx
src/queries/SUE/statuses.tsx
src/screens/SUE/SueReportScreen.tsx

- added `fetchSueEndpoints` function to `sueHelper` to update `apiKey` via `globalSettings`
- integrated `fetchSueEndpoints` into queries
- updated `SueReportScreen` because the `limitOfArea` object has been moved into the `sue` object
SUE-82
create a new object named `sue` inside the `settings` object in `globalSettings` for testing
create an object called `apiConfig` inside the `sue`
```
"settings": {
"sue": {
"apiConfig": {},
}
},
```
the `apiConfig` object may look as follows
```
"apiConfig": {
"serverUrl": "xxx",
"apiKey": "xxx",
"jurisdictionId": "1"
}
```
```
"apiConfig": {
"whichApi": "testApi",
"testApi": {
"serverUrl": "xxx",
"apiKey": "xxx",
"jurisdictionId": "2"
},
"productionApi": {
"serverUrl": "xxx",
"apiKey": "xxx",
"jurisdictionId": "3"
}
}
```
If more than one api is …

feat(sue): update api key via server

---

src/components/SUE/report/SueReportLocation.tsx
src/screens/SUE/SueMapScreen.tsx

- added `query` to `SueReportLocation` to see open and edited reports in the map view shown in the location step on the report screen
- added `mapMarkers` to convert the data coming from the API via query into the correct format for the map
- exported from `SueMapScreen` to use the `mapToMarkers` function in `SueReportLocation`
- added location information created with `mapMarkers` to `locations` array
- updated query's `cacheTime` to 24 hours
- added `SueStatus` `enum` to see statuses in one place
- added `start_date` to `queryVariables` to get all data
- updated the query in `parseListItemsFromQuery` with `REQUESTS_WITH_SERVICE_REQUEST_ID` to keep the code in the same structure
SUE-75
- To test, upgrade the version in `app.json` to `60.0.0`,
- Click the Jetzt Meldung machen button on …

feat(sue): list previous reports on the report screen

---

src/components/SUE/report/SueReportServices.tsx

- added description text for categories to be shown in tiles in `SueReportServices`
SUE-84
since there is no limit on the description text, a limit of `numberOfLines={3}` has been added until a better solution is found
|iPhone SE|iPhone 15 Pro Max|
|--|--|

feat: add description of categories to report screen

---

src/PermanentFilterProvider.tsx
src/components/DropdownHeader.js
src/components/screens/Overviews.js
src/components/settings/PermanentFilterSettings.tsx
src/hooks/permanentFilter.ts
src/queries/newsItems.js
src/screens/HomeScreen.js

- updated `PermanentFilterProviderValues` type to include separate state and dispatch variables for `dataProviderIds` and `mowasRegionalKeys`
- updated `PermanentFilterContext` to reflect the changes in `PermanentFilterProviderValues`
- extended `PermanentFilterProvider` to use `mowasRegionalKeysReducer` and added logic to load and dispatch `mowasRegionalKeys` alongside `dataProviderIds`
- refactored the `usePermanentFilter` hook to return `excludeDataProviderIds` and `excludeMowasRegionalKeys`
- updated `PermanentFilterSettings` to integrate the change to the `usePermanentFilter` hook
- integrated changes to the `usePermanentFilter` hook into `Overviews` and `HomeScreen`
- added `excludeMowasRegionalKeys` `queryVariables` to `newsItems` query
- added `excludeMowasRegionalKeys` to …

feat: expand `PermanentFilterProvider` with `mowasRegionalKeys`

---

src/screens/SUE/SueReportScreen.tsx

- added to the top of the function because `isAnyInputMissing` never appears because it is generated at the end of the function, and added `isAnyInputMissing` check for the 3rd case
SUE-86
|before|after|
|--|--|

feat(sue): update alert messages

---

eas.json

- updated xcode version in `eas.json` to latest to eliminate Apple's warning when a new build is created
SVA-1305

chore: compile in the latest xcode version for iOS

---

src/screens/SUE/SueReportScreen.tsx

- adjusted the name of the `const` because `some` returns a boolean
SUE-63
previous conversation: https://github.com/smart-village-solutions/smart-village-app-app/pull/1054#discussion_r1550347242

refactor: adjusted const naming

---

src/config/consts.js
src/config/navigation/config.ts
src/config/navigation/defaultStackConfig.tsx
src/config/texts.js
src/screens/DetailScreen.js
src/screens/EncounterScannerScreen.tsx
src/screens/Voucher/VoucherScannerScreen.tsx
src/screens/Voucher/index.ts
src/types/Navigation.ts

- added `detail` to `screens` object in `config.ts` to redirect qr codes read with system camera to `DetailScreen` in the app
- added `VoucherScannerScreen` to be able to scan qr from within the app
- added `parseQrCode` function to get the data we need for routing from the data generated when qr is scanned
- the link that should be in the qr is like this -> `smart-village-app://detail?query=pointOfInterest&id=41147`
- added query value as `pointOfInterest` as default, although there is no query value in the data
- added alert to notify the user if the data in the qr does not contain an `id` and added state control to prevent the alert from being rendered infinitely
SVAK-40
For the test, go to the VoucherScannerScreen and show the following QR to the camera.
After the QR is recognised you …

feat(voucher): add qr code scan screen

---

src/components/vouchers/VoucherRedeem.tsx
src/helpers/voucherHelper.ts
src/hooks/voucherHooks.ts
src/queries/vouchers.ts
src/screens/Voucher/VoucherDetailScreen.tsx
src/screens/Voucher/VoucherIndexScreen.tsx
src/screens/Voucher/VoucherLoginScreen.tsx

- added `storeVoucherMemberId` to save `memberId` to device
- added `voucherMemberId` to read saved `memberId` data
- updated `addToStore` with `storeVoucherMemberId` to save `memberId` to device after login process
- added `memberId` value to queries as `queryVariables`
- added `memberId` to `voucherHook` to read `memberId` data from everywhere via `useVoucher` hook
- integrated `memberId` which can be read via `useVoucher` into screens and added as queryVariables
SVAK-35

feat: add member id to query

---

src/components/vouchers/VoucherRedeem.tsx
src/helpers/voucherHelper.ts

- added `uuid` to create a unique `deviceToken` when using voucher
- added the ability to create and save a `deviceToken` to the device if there is no `deviceToken` saved on the device
SVAK-35

feat: add `deviceToken` for redeem voucher

---

src/components/screens/PointOfInterest.js
src/config/texts.js
src/helpers/parser/listItemParser.js
src/queries/pointsOfInterest.js
src/screens/Voucher/VoucherDetailScreen.tsx

- added `|| data` to `listItemParser` to fix the error that occurs in POI query because the data is not in the `genericItem` object and the direct data is an array
- added `EmptyMessage` component to display the `quota` data in case it is null
- added `FlatList` to show the coupon list if there is voucher data in `DetailScreen`
- added `parseListItemsFromQuery` to convert voucher data to the format requested by `VoucherListItem`
- added the feature that if a POI has more than one voucher, instead of showing all of them, it shows 2 at the beginning and then shows 5 more by pressing the button at the bottom of the list
Please change the server connection as the voucher feature is not available on the development server. 
Then follow this path:
Service Tab -> Stadtwerke Tile -> TreueClub …

feat: add voucher list to poi detail screen

---

src/components/bookmarks/BookmarkSection.tsx
src/components/vouchers/VoucherList.tsx
src/hooks/listHooks.js
src/screens/Voucher/VoucherIndexScreen.tsx

- added a redirect to the `BookmarkCategory` screen in `listHook` to fix the problem that clicking on the title of a voucher in the favourites list opens the `VoucherIndex` screen and shows all vouchers
- added `screenName` to `queryVariables` in `VoucherIndexScreen` to find out if the voucher list is on the favourite screen or the `VoucherIndex` screen
- added category id with category name in the array parser in `VoucherList` in order to filter by category ids
- updated `queryVariables` in `listHooks` because `genericItems` query has `categoryId` variables instead of `category` variables
- updated the condition in `listHooks` because the list structure has been updated and is now an object instead of a string
- updated the condition so that the `DropdownHeader` does not appear when we …

fix: listing error for vouchers in favourites

---

src/hooks/listHooks.js
src/screens/Voucher/VoucherIndexScreen.tsx

- replaced `categoryId` with `category` in `VoucherIndexScreen` to solve the dropdown disappearing problem
- added `category` to `queryVariables` in `listHooks` to ensure that the dropdown does not appear when clicking on any section
- removed the `loading` condition in `VoucherIndexScreen` to solve the problem of the whole screen refreshing when any filter is selected
SVAK-75

fix: the dropdown hiding problem when category is selected

---

src/config/texts.js
src/screens/Voucher/VoucherScannerScreen.tsx

- added `requestCameraPermissionsAsync` to fix the problem of encountering a black screen because the camera permission is not checked on the scanner screen
SVAK-40

fix: the black camera on the scanner screen

---

src/components/EventList.js
src/components/screens/EventRecords.js
src/helpers/parser/listItemParser.js
src/helpers/textHelper.js

- added `withTime` option to `listItemParser` to show the event time in the event list
- added `withTime` and `dates` control to `listItemParser` to show the timing of the event in the list
- added `second` prop to `textHelper` to show the time in the list in the desired format and updated returns
SVAK-84
|with time|without time|
|--|--|

feat: add time subtitle to event list

---

src/components/vouchers/VoucherRedeem.tsx
src/screens/Voucher/VoucherHomeScreen.tsx

- added `localRedeemedVoucherCheck` function to ensure that if a user has redeemed a voucher without an internet connection, they cannot redeem the same voucher again and updated the button to disabled if the voucher has been redeemed
- saved coupon information in the device's memory in case of a problem with the internet connection has been moved to the catch section
- moved `deviceToken` information out of the `try` blog as needed when saving voucher information
- added `redeemLocalVouchers` function to ensure that the vouchers stored in the device are sent to the server and used online in case of internet connection
- added resetting of the `voucherTransactions` array saved on the device if the exchange of information with the server has been successful
SVAK-90
To test, create a fake …

feat: add the check whether the voucher is redeemed locally

---

src/components/screens/PointOfInterest.js
src/config/texts.js
src/queries/vouchers.ts
src/screens/Voucher/VoucherDetailScreen.tsx

- added `genericItems` query with `ids` variables to `VoucherDetailScreen` to show current coupons list
- added the `id` of the vouchers to the `pointOfInterest` query in `vouchers.ts` to get the `ids` variables
- added filtering with `id` to not list the voucher shown in DetailScreen
- coded the listing codes in the same way as POI detail screen
SVAK-87
|voucher detail screen|voucher detail screen actual list|
|--|--|

feat: add other offers section to detail screen

---

src/hooks/voucherHooks.ts
src/screens/HomeScreen.js
src/screens/Voucher/VoucherHomeScreen.tsx

- developed the `useRedeemLocalVouchers` hook and added it to `HomeScreen` so that if there is a coupon saved on the device, the user can redeem coupons online no matter which screen the user is on in the whole app
SVAK-35

feat(voucher): send saved redeemed vouchers to the server

---

src/components/DropdownHeader.js
src/screens/Voucher/VoucherIndexScreen.tsx

- added `dropdownData` hook to `VoucherIndexScreen` to get the object data needed by `DropdownHeader`
- added `forEach` method in `DropdownHeader` to `dropdownData` hook in `VoucherIndexScreen` and `categories` object is returned
SVAK-35

fix(voucher): the data type problem sent to `DropdownHeader`

---

src/components/bookmarks/BookmarkSection.tsx
src/queries/vouchers.ts
src/screens/BookmarkCategoryScreen.js

- added `variables` object according to `query` in `BookmarkSection` to solve the problem of more than 3 items not being listed in favourite list
- added `limit` prop to `DataListSection` in `BookmarkSection` to show more than 3 items
- added `queryVariables` to `BookmarkCategoryScreen` to list only the favourited items of that category when the title of an item in the favourite list is pressed
SVAK-35

fix: favourite list not loading completely

---

app.json
package.json
src/components/consul/selectors/ImageSelector.js
src/hooks/imagePicker.ts
yarn.lock

- added `expo-media-library` package needed to save images to gallery
- added `saveImage` prop to `useCaptureImage` hook so that captured images can be saved to gallery
- added the feature that if the `saveImage` prop is `true`, the picture taken is added to the album with the same name according to the albums previously created or on the device, or a new album is created and the picture is added to the new album
- added album name to be created in gallery as app name
SUE-79
A new app build needs to be created due to native dependencies.  
`yarn ios -d` or `yarn android` commands can be used.

feat: save images captured with the camera to the gallery

---

src/components/Image.js

- added `apiKey` in the `headers` object to the get function in the `Image` component because the images are not accessible without api key
SUE-22
|before|after|
|--|--|

fix: the problem of images not appearing

---

src/hooks/imagePicker.ts

- updated `copyAsset` value from `false` to `true` in order to remove the alert whether the image should be changed while saving after the image is taken on the android platform
SUE-79

feat: remove the question whether to change the picture for android

---

package.json
patches/react-native-maps+1.7.1.patch
yarn.lock

Added a patch to react-native-maps package to resolve an issue where street names overlap custom map overlays on iOS 16 and above.
Thanks to [@cixio](https://github.com/cixio) for the starting solution to use `MKOverlayLevelAboveLabels` https://github.com/react-native-maps/react-native-maps/pull/4549/commits/49bbdf693d9ddcd052fec2e5bec90349cc04210a
**Changes:**
- Updated AirMap.m to use `MKOverlayLevelAboveLabels` for overlays.
- Added patch-package and postinstall script to package.json to ensure patch is applied automatically.
- Included the generated patch file in the patches directory.
This ensures consistent behavior across all developer environments.
SUE-43
Usage:
- To see the wanted results, make sure to run `yarn prebuild` and rebuild the app
**Additional information:**
The +1.7.1 …

fix: apply patch to react-native-maps to fix street name overlap on iOS 16+

---

src/screens/SettingsScreen.js

- moved `setData` out of the `if` control to fix the problem of the settings screen not loading in apps with augmented reality feature if the device does not support augmented reality feature
SVA-1356

fix: settings screen not loading problem

---

src/components/map/Map.tsx

- retracted doubleTileSize feature as we have a new map view
SUE-27
Reverts #1002

chore(sue): retract `doubleTileSize` property

---

src/components/SUE/report/SueReportSend.tsx
src/config/texts.js

- added `createAppUserContent` mutation to send feedback form to server
- added `ScrollView`'s `scrollTo` property in the `onFocus` prop to make the screen scroll up automatically when the keyboard is opened because input has a multiline property
- wrapped with `ScrollView` to make the form fully visible on the screen
SUE-78
To test, set the if condition in line 437 of `SueReporScreen` to `true`.
`if (isDone || isLoading) {...` -> `if (true) {...`
Then set the condition on line 98 in the `SueReportSend` component to `true`.
`{!isLoading && isDone && (...` -> `{true && (...`
Then, when you go to the report sending screen in the app, you will see the feedback form.
|before|after|after with keyboard|
|--|--|--|

feat(sue): add user feedback form

---

src/components/Chat.js
src/components/SUE/report/SueReportDescription.tsx
src/components/SUE/report/SueReportLocation.tsx
src/components/SUE/report/SueReportServices.tsx
src/components/SUE/report/SueReportUser.tsx
src/components/consul/selectors/ImageSelector.js
src/hooks/imagePicker.ts
src/hooks/index.js
src/hooks/reverseGeocode.ts
src/screens/EncounterDataScreen.tsx
src/screens/SUE/SueReportScreen.tsx

- converted props in `imagePicker` to object format to avoid confusion in props
- returned the reverseGeocode function to the hook and exported it so that it can be used in other parts of the code
- added the props needed by the `useReverseGeocode` hook for location control to `SueReportDescription`
- added `coordinateCheck` prop to check when the image is selected in `ImageSelector`
- added `usePosition` and `useLastKnownPosition` hooks to `ImageSelector` to use the current location of the device since location information cannot always be obtained from the image
- added location control to `ImageSelector` by `useReverseGeocode` hook with location information from image or device location information
- prevented the image from being added to the report if the image is not in the desired …

feat: get coordinate data in the image

---

src/components/Chat.js
src/components/SUE/report/SueReportDescription.tsx
src/components/SUE/report/SueReportLocation.tsx
src/components/SUE/report/SueReportServices.tsx
src/components/SUE/report/SueReportUser.tsx
src/components/consul/selectors/ImageSelector.js
src/components/map/Map.tsx
src/hooks/imagePicker.ts
src/hooks/index.js
src/hooks/reverseGeocode.ts
src/queries/SUE/areaService.tsx
src/queries/SUE/index.ts
src/queries/index.js
src/queries/types.ts
src/screens/EncounterDataScreen.tsx
src/screens/SUE/SueReportScreen.tsx

- added `apiKey` and `serverUrl` information to add connection with field service can be updated via main-server as `requests` request
- added `zipCode` state due to late change of `getValue('zipCode')` and no data from area service
- added rules that `limitOfCity` must be true and `zipCode` must be 5 digits to activate an area service request
- added rule to show `errorMessage` alert that can be updated via main server in case the `limitOfCity` value that can be updated via main server does not match with area service
- updated area service link with `id` instead of `getByPostalCode`
- added comparing postcode data from area service with the postcodes of the location selected from the map
- added errors in the `reverseGeocode` function to catch the error message
- updated `onMapPress` …

feat(sue): connect with the area service

---

src/components/SUE/report/SueReportSend.tsx
src/config/sue/default.ts

- connected to the `showFeedbackSection` value in `ConfigurationsContext` to make the feedback section shown after sending a report adjustable from main-server
SUE-78
To test, set the if condition in line 437 of `SueReporScreen` to `true`.
`if (isDone || isLoading) {...` -> `if (true) {...`
Then set the condition on line 98 in the `SueReportSend` component to `true`.
`{!isLoading && isDone && (...` -> `{true && (...`
Then, when you go to the report sending screen in the app, you will see the feedback form.

feat(sue): make feedback form adjustable from main server

---

src/components/SUE/report/SueReportServices.tsx
src/screens/SUE/SueReportScreen.tsx

- updated `scrollViewContentRef` to `[]` instead of `null` to create a separate scroll view ref for each step
- added `onContentSizeChange` prop to calculate the content size at each step and added `handleContentSizeChange` helper
- updated the `scrollTo` function to automatically scroll the scroll view according to the size of the content at each step
- added `useEffect` to scroll the scroll view at that step in the content size when the `serviceCode` changes
- updated the `serviceCode` state to `service` because the description and title data of the service is needed
- added the category description to `SueReportScreen` if a category is selected
SUE-84
|before|after|
|--|--|

feat: add category details texts under tiles

---

src/components/consul/selectors/ImageSelector.js
src/config/texts.js
src/screens/SUE/SueReportScreen.tsx

SUE-100
You can only get this warning if you add an image of the specified location in the config. Otherwise this feature will not work. 
To do this:
Go to areaService.tsx and update the id to 18116.
Then select a photo taken in Kiel from the gallery. If the address information is loaded correctly, you will not receive an error warning. Press the Continue button and see the new warning.

feat(sue): add warning when address inputs are filled from the image

---

src/components/SUE/report/SueReportLocation.tsx
src/config/navigation/defaultStackConfig.tsx
src/screens/MapViewScreen.js
src/screens/SUE/SueMapViewScreen.tsx
src/screens/SUE/index.ts
src/types/Navigation.ts

- turned `onMapPress` into a separate method to send it as param to `MapViewScreen`
- added `position` state to `MapViewScreen` to add pins to the map
- updated the `locationsWithPin` state in the `useEffect` to prevent two pins from being added when clicking on the map in `MapViewScreen`
- added `onMyLocationButtonPress` as an extra method to use the current location information on the full screen map
- added `updateRegion` to refresh the map when the user presses the current location button
SUE-80
|||
|--|--|

feat: add location selection on full screen map

---

src/config/texts.js
src/helpers/fileSizeHelper.ts
src/screens/SUE/SueReportScreen.tsx

- added optional `decimal` prop to `formatSize` to remove comma expression
- updated the text in `SueReportScreen` to show the data limitation from config as a warning
SUE-90

feat(sue): update total size error according to config

---

app.json

- updated `microphonePermission` in `app.json` to prevent the app from crashing due to insufficient permissions when taking enough pictures for the iOS platform
SUE-108

fix(sue): the problem of the app crashing when taking a picture

---

App.js

- updated the `debug` section in `Sentry.init` to the comment line so that the sentry log is not generated
on every click in development mode defaults to `false`
- https://docs.sentry.io/platforms/react-native/configuration/options/#debug
- deleted `enableNative` value because it has `true` value by default
SVA-1383

feat(sentry): reduce sentry logs

---

src/components/Button.js
src/config/normalize.js

- added `guidelineBaseHeight` and `PixelRatio` to cover devices with different aspect ratios.
worked it out with an idea I had and ChatGPT
SVA-1351
<p float=" left">
</p>
<p float="right">
</p>

chore: extend normalize function update

---

metro.config.js
package.json
yarn.lock

- addition of [`react-native-svg-transformer`](https://github.com/kristerkari/react-native-svg-transformer), to transform svg's into react components for simple use and display of svg's
- modified `metro.config.js` accordingly to the new package
Usage: https://github.com/kristerkari/react-native-svg-transformer?tab=readme-ov-file#usage

feat: add react-native-svg-transformer package

---

src/components/augmentedReality/ARObjectList.js
src/helpers/augmentedReality/progressSizeGenerator.js
src/helpers/fileSizeHelper.ts
src/screens/SUE/SueReportScreen.tsx

- updated `formatSizeForAugmentedReality` helper to `formatSizeStandard` to use in different parts of the code and to avoid name confusion
- updated the `formatSize` helper in `SueReportScreen` with `formatSizeStandard` because it provides a more accurate calculation
SUE-90

feat: update total image size format

---

src/components/infoCard/InfoCard.tsx
src/components/screens/PointOfInterest.js

- added that if `showFilterByOpeningTimes` is set to false in main-server, not only the filter is not shown, but also the opening times in `DetailScreen` are hidden
- updated `showFilterByOpeningTimes` to `showOpeningTimes` in `PointOfInterest` to improve code clarity
SVA-1395
|before|after|
|--|--|

feat: add control to open times on detail screen

---

app.json

- added `NSAppTransportSecurity` to `infoPlist` in `app.json` to fix http sites not opening on ios platform
SVA-1400

fix: http pages not opening on ios platform

---

src/ConfigurationsProvider.tsx

- added control to `useEffect` to fix the problem of entering an infinite loop when the app first starts if there is no sue object in `globalSettings`
- added skip to prevent loading of `sueReportProgress` staticContent if sue object is not in `globalSettings`
SVA-1403
I added a new `globalSettings` of version 4.1.0 to main-server. This version does not contain sue object. You can try by changing the version in `app.json` to 4.1.0.

fix(config): app not loading problem

---

src/components/noticeboard/NoticeboardCreateForm.tsx
src/config/texts.js
src/screens/Noticeboard/NoticeboardFormScreen.tsx
src/screens/Noticeboard/NoticeboardIndexScreen.tsx

- added categories query to `NoticeboardCreateForm` to add noticeboard in different categories
- deleted `NOTICEBOARD_TYPE_OPTIONS` because we obtained categories with categories query
- updated `categoryName` because we use category names from query instead of customized category name in `onSubmit`
- added `queryVariables` as a prop to `NoticeboardFormScreen` because we need `queryVariables` in `NoticeboardCreateForm`
- deleted `categoryNames` in `texts` because we don't need them
SVAK-51
- To see the categories set in main-server in the app, upgrade the version in `app.json` to `5.1.3`
- Switch to the Service Tab and you can see the noticeboard lists for level 2 or level 3
|2. level create form|3. level create form|2. level category list|3. level category list|
|--|--|--|--|

feat(noticeboard): add the ability to add noticeboards in different categories

---

src/components/widgets/CustomWidget.tsx
src/components/widgets/Widgets.tsx
src/config/texts.js
src/types/WidgetProps.ts

- added `CustomWidget` to show static content as a widget
- added `settings` icon as fallback to prevent the app from crashing if `iconName` is undefined
- added `routeName` and `params` values to `onPress` to redirect to the desired screen within the app
SVA-1406
- upgrade `version` in `app.json` to 5.0.0

feat(widget): add static content widget

---

src/components/consul/selectors/ImageSelector.js
src/config/sue/default.ts
src/queries/SUE/configurations.tsx
src/queries/SUE/requests.tsx
src/screens/SUE/SueReportScreen.tsx

- removed from `requiredFieldsDefaults` object because `geoMap` config is used to set the input requirement instead of `address` values from config
- parse the `contact` object in the `mapKeysToCamelCase` function in `configurations.tsx` since the address config is no longer needed
- removed from control because there is no `contact` object in `SueReportScreen`
SUE-97
config:
```
"contact": {
"email": true,
"first_name": true,
"last_name": true,
"phone": true
}
```
|before|after|
|--|--|

fix(sue): required input problem in config

---

package.json
src/config/Icon.tsx
src/config/fonts.ts
src/config/icons/Tabler.tsx
src/config/icons/index.ts
src/config/index.js
src/config/navigation/tabConfig.tsx
src/icons/SUE/index.js
yarn.lock

- added `tabler-icons-react-native` package to fix the tabler icon family's spacing issue for Android
- added `IconComponent` to the `NamedIcon` function so that the code can work properly with different icon families
- removed from the code because there is no need for `Tabler` icon family as font
- moved the `Icon.tsx` file back into the `config` folder since the tabler font was deleted and there was no need for the extra `icons` folder
SVASD-6
|before|after|
|--|--|

fix(tabler): icon problem on android

---

src/queries/SUE/areaService.tsx

- updated `areaService` to access zip codes via `rs` since not all zip codes are available via `id`
- added `postalCodes` object in the return section to get all postal codes obtained via getByRs in the desired format
- added `_uniq` to remove repeated zip codes from the array
SUE-133
Log:
```
{"postalCodes": ["24011", "24012", "24013", "24014", "24015", "24016", "24017", "24018", "24019", "24020", "24021", "24022", "24023", "24024", "24025", "24026", "24027", "24028", "24029", "24030", "24031", "24032", "24033", "24034", "24035", "24036", "24037", "24038", "24039", "24040", "24041", "24042", "24043", "24044", "24046", "24047", "24048", "24049", "24062", "24063", "24065", "24103", "24105", "24106", "24107", "24109", "24111", "24113", "24114", "24116", "24118", "24143", "24145", "24146", …
```

fix: the problem with the area service request

---

src/screens/BB-BUS/IndexScreen.js

- added `initialFilter` array in `settings.busBb` object to update the filter from main-server
- added `FILTER_IDS` to use the ids in the initial filter correctly
- added const for `busBb` object to avoid code repetition
SVAK-118
If you want to update the filters, an array initialFilter must be added to the settings.busBb object in globalSettings.
This array can be as follows.
```
"initialFilter": [
"top10",
"search",
"aToZ"
]
```
To quickly test whether the code works:
- go to `src/screens/BB-BUS/IndexScreen.js`
- copy the `initialFilter` array and paste it as a const into the code.
```
const initialFilter = ['top10', 'search', 'aToZ'];
```
- remove `busBb?.` from `busBb?.initialFilter?...` in filter state
```
const [filter, setFilter] = useState(
initialFilter?.map((entry, index) => ({ …
```

feat(bbBus): set filter from main-server

---

src/components/SUE/report/SueReportLocation.tsx

- set the address state in the `onChange` prop instead of running the geocode function to fix the problem of automatically updating the map to the wrong location after filling in the address inputs
- added that since the last letters of the data entered in the input with `getValues` are not recognized by the `geocode` function, the data in the `geocode` function should be retrieved from the address state instead of `getValues`
SUE-148
|before (Augsburg)|after (Kiel)|
|--|--|

fix(sue): location inaccuracy from address

---

src/components/screens/DraggableGrid.tsx
src/components/screens/Service.tsx
src/hooks/personalizedTiles.ts

- updated `sortTitles` values in `personalizedTiles` with `umlautSwitcher` to bring mismatched titles into the same format to fix a bug where personalized tiles were not sorted correctly after saving
- removed `replace` from `id` in `DraggableGrid` because `replace` was added at the end of the `umlautSwitcher` function
SVA-1291
Before update:
|before save|update|after save|
|--|--|--|
After update:
|before save|update|after save|
|--|--|--|

fix: the problem of personalized tiles not being sorted correctly

---

src/components/ImagesCarousel.js

- added `autoplayInterval` to give more customization options to the slider
- added options to customize the slider with the `sliderSettings` object added inside the `globalSettings.settings` object
- autoplayInterval: this value is used to set how many milliseconds the slider will scroll to the next image
- refreshInterval: allows the image in the slider to be displayed without being cached and refreshes the image after the milliseconds entered here
EP-21
```
{
...
"sliderSettings": {
"autoplayInterval": 3000,
"refreshInterval": 3000
}
},
...
```
before
https://github.com/user-attachments/assets/312db700-8d65-4f78-a878-76b15f6259a7
after
https://github.com/user-attachments/assets/7b6719a6-d59b-4138-8c7b-c5693c33a261

feat: add `autoplayInterval` to slider

---

src/components/HomeSection.tsx
src/queries/eventRecords.js
src/screens/HomeScreen.js

- react-apollo is not able to handle the new `date` field, which we forgot to use for home section queries
SVASD-10

fix: home section query with react-query

---

app.json

- added minimum version value required for apple silicon processor support to `app.json`
SVA-1384

feat: add the minimum version value for macOS platform

---

src/queries/eventRecords.js

- added `dateFilelds` section missing in the query to fix the problem that the category filter on the event list screen does not appear due to data not loading
SVA-1388
|before|after|
|--|--|

fix: event category query not working

---

src/components/screens/PointOfInterest.js
src/helpers/parser/listItemParser.js
src/queries/pointsOfInterest.js

- added `nestedCategory` to fix the category naming problem on the `DetailScreen`
- added `queryVariables?.category` to the `subtitle` section in `listItemParser` to fix the category naming problem in list view
- added `categories` to `pointOfInterest` query to get all categories that the content contains
SVA-1348
|parent category|before child category|after child category|before DetailScreen|after DetailScreen|
|--|--|--|--|--|

fix: category naming problem

---

src/hooks/reverseGeocode.ts

- added `User-Agent` to the `headers` section of the request to fix the problem of the reverse geocoding service not working due to the policies of the address sections according to the selected location
SUE-151

fix: reverse geocoding request error

---

src/helpers/parser/listItemParser.js

- added `usedAsInitialScreen` value as false to `parseCategories` to fix the problem that if `BOTTOM_FLOATING_BUTTON` is active when switching to the subcategory screen, the upper left close button does not return to the back button
SVAK-92
before
https://github.com/user-attachments/assets/bad12777-3d7c-459a-914e-cf5897734482
after
https://github.com/user-attachments/assets/c29f9601-1a4f-48c4-a488-61bea5bc4994

fix: header left problem on subcategory screen

---

src/components/SUE/report/SueReportDescription.tsx
src/components/consul/selectors/DocumentSelector.js
src/components/consul/selectors/ImageSelector.js
src/components/noticeboard/NoticeboardCreateForm.tsx
src/components/screens/PointOfInterest.js
src/components/screens/consul/Proposals/NewProposal.js
src/config/Icon.tsx
src/config/consts.js
src/config/texts.js
src/helpers/consul/dataErrorMessageGenerator.js
src/screens/Noticeboard/NoticeboardFormScreen.tsx

- added `ImageSelector` component to add images on the noticeboard creation screen
- updated the `showNoticeboardMediaContent` object to set the maximum size and count of images via main-server
- updated `stroke` prop to `strokeWidth` to make `NamedIcon` props the same as `IconProps`
- added noticeboard types required for `ImageSelector` to `consts`
- added texts needed for images to `texts`
- added error messages for noticeboard to `dataErrorMessageGenerator`
- updated `ImageSelector` component according to noticeboard
- updated `SueReportDescription` to apply the changes in the configuration prop updated with `ImageSelector` to sue
- added `configuration` prop to `DocumentSelector` to make `ImageSelector` and `DocumentSelector` the same and understandable
- added the ability to …

feat: add image upload feature for noticeboard

---

app.json
src/components/MultiButtonWithSubQuery.tsx
src/screens/WebScreen.js
src/types/SubQuery.ts

- added the ability to automatically open the browser if the `WebScreen` in the app is redirected with the `isExternal` param
- updated `MultiButtonWithSubQuery` to add `isExternal` as param when redirecting via multi button screen
SVASD-15
changes in main-server:
- redirect to browser:
```
{
"title": "YT",
"routeName": "Web",
"params": {
"webUrl": "https://www.youtube.com/",
"isExternal": true
}
}
```
- redirect to WebScreen in the app:
```
{
"title": "YT",
"routeName": "Web",
"params": {
"webUrl": "https://www.youtube.com/"
}
}
```

feat: add link that opens from browser

---

src/components/EventList.js
src/components/EventSuggeestionButton.tsx
src/components/index.js
src/components/screens/EventRecords.js
src/config/navigation/defaultStackConfig.tsx
src/config/texts.js
src/screens/EventSuggestionScreen.tsx
src/screens/index.js
src/types/Navigation.ts

a redirect button has been added to the form screen to create an event suggestion on the event list screen.
`globalSettings.sections:`
```
"eventListIntro": {
"buttonType": "bottom-floating",
"introText": "Die Events, die hier aufgezeigt werden, finden an Orten in der Reiseregion Havelland statt. Die Reiseregion Havelland geht uber die Grenzen des Landkreises Havelland hinaus. \n\nIhr Event ist nicht dabei? Melden Sie es der Tourismus-Marketing Brandenburg GmbH einfach selbst.",
"formIntroText": "Die Events, die hier aufgezeigt werden, finden an Orten in der Reiseregion Havelland statt. Die Reiseregion Havelland geht uber die Grenzen des Landkreises Havelland hinaus. \n\nIhr Event ist nicht dabei? Melden Sie es der Tourismus-Marketing Brandenburg GmbH einfach selbst.",
"url": …
```

feat: add event suggestion screen

---

src/ConfigurationsProvider.tsx
src/screens/SUE/SueReportScreen.tsx

added `refetch` and `isLoading` to `ConfigurationsProvider` to update the config when the report screen is opened
SUE-139

feat(sue): update config when report screen opens

---

src/components/filter/Filter.tsx

only when selecting `startDate` or `endDate`, both values of the `dateRange` array must be added, so the other value has been added
Only if `startDate` is selected, endDate = 31.12.9999
Only if `endDate` is selected, startDate = today
SVAK-128

fix: start/end date selection problem

---

src/components/DataListSection.tsx
src/components/bookmarks/BookmarkSection.tsx
src/queries/eventRecords.js
src/screens/BookmarkCategoryScreen.js

Request a single event with the event records query for bookmarks instead of multiple events for all dates of an event.
⚠️ **this does not work with int-development**
SVA-1509

fix(bookmarks): multi events handling

---

src/components/OrientationAwareIcon.tsx
src/config/navigation/defaultStackConfig.tsx
src/config/navigation/tabConfig.tsx
src/navigation/MainTabNavigator.tsx
src/types/Navigation.ts

tab navigation feature that can be configured via main-server has been added
To test this feature:
- Create a JSON type content named `tabNavigation` on main-server:
- Update the JSON content as follows or add the desired navigation structure.
```
{
"activeTintColor": "#0f4618",
"activeBackgroundColor": "#fff",
"inactiveTintColor": "#107821",
"inactiveBackgroundColor": "#fff",
"tabConfigs": [
"Home",
"Service",
"Events",
"Index",
"About",
{
"label": "Custom",
"screen": "VolunteerHome",
"iconName": "Volunteer",
"iconSize": 30,
"accessibilityLabel": "Volunteer",
"iconStyle": {
"marginTop": 20
},
"iconLandscapeStyle": {
"marginTop": 20
}
}
]
}
```
- Delete the app's cache and reload it
|before|after|
|--|--|
SVA-1531

feat(tab): configureable tab navigation

---

src/components/TextListItem.tsx
src/components/map/LocationOverview.tsx

- added new style props to customise the `TextListItem` via props
- created `textDirection` depending on the `titleFirst´ prop to change the order of the texts
- added `showOpenStatus` prop to `TextListItem` to show whether POI is open or closed
- using the `isOpen` helper to find out if the POI is open or not
- customised `TextListItem` used in `LocationOverview` with new props
MQGB-34
please remove the date information in the `pointOfInterest` query to avoid the problem of POIs not loading due to server.
```
export const GET_POINT_OF_INTEREST = gql`
query PointOfInterest($id: ID!) {
pointOfInterest(id: $id) {
id
title: name
payload
category {
id
name
iconName
}
...
```
|before|after - open POI|after - close POI|
|--|--|--|

feat: add more information in the preview

---

src/config/navigation/defaultStackConfig.tsx
src/config/navigation/tabConfig.tsx
src/navigation/MainTabNavigator.tsx
src/types/Navigation.ts

- added `tilesScreenParams` option to `getTilesScreen` in `defaultStackConfig` to add the ability to create custom service tiles on main-server without any code modification
SVA-1531
It will be enough to add the desired values to the `tilesScreenParams` section to create a custom service tile page by updating the `tabNavigation` staticContent on the main-server without any code modification.
Note: It is important to remember to create a staticContent named staticJsonName.
```
{
screen: 'Service',
tilesScreenParams: {
staticJsonName: 'homeCompanies',
titleKey: 'headlineCompanies', // optional
imageKey: 'headlineCompaniesImage', // optional
matomoString: 'string', // optional
titleFallback: 'string' // optional
}
...
}
```

feat(tab): add customizable service tile screen

---

src/ConfigurationsProvider.tsx

- copied the target value and overwritten the result variable in the `mergeDefaultConfiguration` function in `ConfigurationsProvider` to fix the problem of `staticContentList` not being able to overwrite style data that can be updated from main-server
SUE-97
update `globalSettings.sections` as follows to be able to test it
```
"sections": {
...
"staticContentList": {
"horizontal": true,
"showStaticContentList": true,
"staticContentListTitle": "staticContentListTitle",
"staticContentListDescription": "staticContentListDescription",
"staticContentName": "homeList"
}
},
```

fix(sue): unable to overwrite configuration error

---

src/components/settings/LocationSettings.js

- added `showAlternativeLocationButton` to add the option to hide the alternative location button
SUE-138
for testing, update the `settings.locationService` object in `globalSettings` as follows
```
"locationService": {
...
"showAlternativeLocationButton": false // true
},
```
|before|after|
|--|--|

feat(sue): hide alternate location selection button

---

src/components/SUE/report/SueReportLocation.tsx
src/components/map/Map.tsx
src/config/appDesignSystem/default.ts
src/screens/SUE/SueMapScreen.tsx
src/types/Map.ts

added active and inactive icon color tones to increase the contrast difference with the map
SUE-142
|before|before with active pin|after|after with active pin|
|--|--|--|--|

feat(sue) increased contrast pin colors

---

src/components/SUE/report/SueReportSend.tsx

- updated the title of the `Input` in the feedback section with `RegularText` to make it look the same as rating in design
SUE-78
|before|after|
|--|--|

fix(sue): input's header design problem

---

patches/react-native-maps+1.18.0.patch

- patch added to fix the problem of half of the pins on the map being visible on android platform
- https://github.com/react-native-maps/react-native-maps/issues/5247#issuecomment-2521958144
SVA-1569
|before|after|
|--|--|

fix(map): the pin problem on the map for android

---

src/components/waste/WasteCollectionSettings.tsx
src/config/texts.js
src/screens/WasteCollectionScreen.js

- moved export button in WasteCollectionSettings with possibility to hide per global settings
|with notifications|without notifications|export overview|
|---|---|---|
|![Simulator Screenshot - iPhone 16 Pro Max - 2025-02-04 at 22 31 08](https://github.com/user-attachments/assets/0c24a3af-b22c-40c0-91bb-27f34ead4b13)|![Simulator Screenshot - iPhone 16 Pro Max - 2025-02-04 at 22 31 10](https://github.com/user-attachments/assets/e398e280-0a73-4d9d-a5a9-35fe7bc97b0a)|![Simulator Screenshot - iPhone 16 Pro Max - 2025-02-04 at 22 31 33](https://github.com/user-attachments/assets/1a2d735c-8a93-4af1-876b-8ddcc1043719)|
GOS-118

feat(waste): add export functionality for waste calendar

---

app.json

- updated `blockedPermissions` to exclude `READ_MEDIA_IMAGES` when saving photos from the camera
SVASD-67

feat: update permissions according to google policies

---

src/components/screens/Overviews.js

- extended the control in `useLayoutEffect` to fix the problem of the return button appearing even though `IndexScreen` is in tab
SVA-1570
|before|after|with initial filter LIST (POI)|map view (POI)|with initial filter MAP (POI)|
|--|--|--|--|--|

fix: the back button issue on the `IndexScreen? placed in tab

---

src/queries/eventRecords.js

- added `webUrls` to `defaultFragment` to fix the problem of links not being added to the share section when sharing events
- removed from `eventRecord` query because `webUrls` was added to `defaultFragment`
SVASD-105
|before|after|
|--|--|

refactor: update event record query structure

---

src/components/oParl/previews/MeetingPreview.tsx
src/components/oParl/previews/OParlItemPreview.tsx
src/components/oParl/previews/OParlPreviewEntry.tsx
src/components/oParl/previews/PersonPreview.tsx
src/components/oParl/sections/OParlPreviewSection.tsx

- added `WrapperHorizontal` to `OParlOrganizationsScreen` and `OParlPersonsScreen` for improved layout
- adjusted imports in `OParlPreviewSection` for better organization
SVA-1384
|--|--|--|--|

fix the design bug of the oparl list

---

src/config/navigation/defaultStackConfig.tsx

This PR adds the title of the screens to `initialParams` instead of `screenOptions` by default
SVA-1384

feat: add page title to `initialParams`

---

src/components/waste/WasteCollectionSettings.tsx

- added `alignSelf` style to fix the problem of date time picker not being centered
SVA-1384
|before|after|
|--|--|

fix(waste): date time picker not centered

---

src/components/waste/WasteCollectionSettings.tsx

- wrap `DateTimePicker` in a container for better alignment on Android
- add specific styles for Android and iOS platforms
SVA-1384
|before without picker|after without picker|before with picker|after with picker|
|--|--|--|--|

fix(waste): adjust date time picker layout for Android

---

src/config/navigation/config.ts
src/config/navigation/tabConfig.tsx
src/navigation/DrawerNavigator.tsx
src/navigation/MainTabNavigator.tsx
src/navigation/Navigator.tsx
src/types/Navigation.ts

- adjusted setting the tab routes to not have the fallback routes set before dynamic routes are loaded, to be able to have a different initial route than home
- currently initialRouteName in linkingConfig.config is still hardcoded
SVA-1531

refactor(navigation): streamline navigator configuration and imports

---

src/components/HeaderLeft.tsx

- remove unnecessary rendering of `ArrowLeft` icon when no `onPress` or `backImage` is provided
SVA-1384
|before|after|
|--|--|

fix: remove unused back button in header for android

---

src/config/navigation/defaultStackConfig.tsx
src/helpers/parser/listItemParser.js

- moved route definitions for `IndexScreen` and `ProfileHomeScreen` to improve readability
- removed unnecessary `initialParams` properties for clarity
- adjusted query parameters for consistency
SVA-1384

refactor: reorganize navigation stack configuration

---

src/components/filter/DateFilter.tsx
src/components/filter/Filter.tsx
src/components/widgets/EventWidget.tsx
src/config/navigation/defaultStackConfig.tsx
src/helpers/parser/listItemParser.js

With this PR, the problem that the daily event screen redirected via widget still shows all events has been fix and `dateRange` dates are shown in the filter component
SVA-1384
|before|after|before|after|before|after|
|--|--|--|--|--|--|

fix: the problem of not showing daily events

---

package.json
src/components/Chat.js
yarn.lock

- upgraded react-native-gifted-chat dependency to the latest version
- updated `scrollToBottom` prop to `isScrollToBottomEnabled` to make the scroll button appear
- added `activeProps` to show full screen image
SVA-1384
|before|after|before|after|before|after|
|--|--|--|--|--|--|

fix: update react-native-gifted-chat to version 2.7.3

---

src/screens/WebScreen.tsx

unset decelerationRate on android because of error: (NOBRIDGE) ERROR  Warning: Error: Exception in HostFunction: Unable to convert string to floating point value: "normal" (see https://github.com/react-native-webview/react-native-webview/issues/3617)

feat(web): adjust deceleration rate based on platform

---

src/components/map/LocationOverview.tsx

- include route prop to manage navigation behavior
- conditionally set `navigation` based on `isPreviewWithoutNavigation ` parameter
SVA-1547
To test this feature, the `isPreviewWithoutNavigation` property should be added to the params object as true when redirecting to the `Index` screen. For example:
```
{
"routeName": "Index",
"params": {
"isPreviewWithoutNavigation": true,
...
}
}
},
```

feat: add route prop to `LocationOverview` component

---

src/screens/SurveyOverviewScreen.tsx

- added `isOngoingSurveysEnmpty` control to avoid too much space above `sectionHeader` in case there is no ongoing survey
SVA-1384
|with ongoing surveys|without ongoing surveys|
|--|--|

fix(survey): enhance header styling in `SurveyOverviewScreen`

---

src/config/navigation/defaultStackConfig.tsx
src/navigation/DrawerNavigatorItem.js
src/screens/WasteCollectionScreen.js
src/screens/WasteCollectionSettingsScreen.tsx

- modified `IndexScreen` options to include `withDrawer` parameter
- updated the `navigate` property in `DrawerNavigatorItem` with `navigateDeprecated` to fix the problem of not being able to navigate with drawer
- https://reactnavigation.org/docs/upgrading-from-6.x/#changes-to-the-navigate-action
SVA-1384
Note that `navigateDeprecated` will be removed in the next version. This can only be used as a temporary solution.
The hamburger icon for drawer navigation is not shown on the Waste calendar page. This is because the `WasteCollectionScreen` has a `useLayoutEffect` where we add different buttons for the `headerRight`.
To test, update the `navigation` value in `globalSettings` to `drawer`

fix(navigation): update screen options and navigation method

---

src/components/form/DateTimeInput.tsx

- added style to center align the `DateTimePicker`
SVA-1384
|before|after|
|--|--|

fix: center align `DateTimePicker` component

---

src/helpers/parser/listItemParser.js

- added a `query` control to the `parseCategories` parser to show categories in the noticeboard creation form because until now the query was only set to POI or TOUR to create a category tree
SVA-1384
|before|after|
|--|--|

fix: categories not showing up on noticeboard

---

src/components/DropdownHeader.js
src/components/filter/Filter.tsx
src/components/screens/Overviews.js

until now the filter applied to the news screen was also applied to the information since it had the same query. Therefore, because the `categoryId` in the applied filter changed, information was listed instead of news. To solve this problem, the news query was extended with `categoryId` for the `filterQuery` value
Also with this PR, the control has been updated to not show the data provider dropdown if there is only 1 option to select in the dropdown (if it is not possible to filter)
SVA-1384
before:
|news (without filter)|infos (without filter)|news (filter)|news list (with filter)|infos (filter)|infos list (with filter)|
|--|--|--|--|--|--|
after:
|news (without filter)|infos (without filter)|news (filter)|news list (with filter)|infos (filter)|infos list (with filter)| …

fix: enhance filtering logic in dropdown and overview components

---

src/components/Chat.js
src/components/selectors/DocumentSelector.tsx
src/components/volunteer/VolunteerFormCalendar.tsx
src/config/consts.js
src/config/texts.js
src/helpers/consul/dataErrorMessageGenerator.js
src/screens/SUE/SueReportScreen.tsx

- added `MB_TO_BYTES` constant for better readability and maintainability
- updated file size checks across multiple components to use `MB_TO_BYTES`
- modified error messages to reflect new size limits
SUE-161

feat: implement `MB_TO_BYTES` constant for file size checks

---

src/components/widgets/DefaultWidget.tsx

- update rendering logic to display `count` only when it exists
SVA-1384
|with count|without count (before)|without count (after)|
|--|--|--|

fix: conditionally render count in `DefaultWidget` component

---

src/navigation/MainTabNavigator.tsx
src/navigation/screenOptions.tsx

- set tab bar inactive background color to a variable for consistency
- clean up unused imports in `screenOptions`
SVA-1578
|without colored|with colored|
|--|--|

fix(navigation): update tab bar style for better appearance

---

App.js
src/RootView.tsx
src/index.js

- removed props from GestureHandlerRootView as it is not intended to be handled as root view for renderings
- created a new RootView component to handle the initial font loading and splash screen hiding
- integrated RootView into the main application structure after provider and contexts before first rendering, to be in place where first needed
- this way it could be a positive side effect, that the splash screen is visible for a longer time, as things will be setup first now

refactor: introduce RootView

---

src/components/screens/OpeningTimesCard.js

- there were `open: null`s we did not catch for opening hours so we simplified the logic to check for "not open" instead of listing different cases that can mean "not open"

fix(opening times): check more explicitly to catch edge cases

---

src/components/vouchers/VoucherRedeem.tsx
src/screens/Voucher/VoucherIndexScreen.tsx

- added `expo-crypto` package to solve the problem of not being able to redeem coupons due to unavailability of uuid package
- wrapped with `WrapperHorizontal` to add side padding to the dropdown in `VoucherIndexScreen`
SVASD-173
|before dropdown|after dropdown|before redeem|after redeem|
|--|--|--|--|

fix(voucher): the coupon unavailability problem

---

src/screens/OParl/OParlPersonsScreen.tsx

- updated loading condition to include `personLoading`
- ensures spinner displays correctly during data fetching
SVA-1613

fix(OParlPersonsScreen): correct loading condition for spinner

---

src/components/TextListItem.tsx
src/hooks/listHooks.js

This PR solves the problem of padding the date header from the left in different list types and adds a `borderRadius` to the image in the `IMAGE_TEXT_LIST` list type
SVASD-162
|before|after|
|--|--|

fix(TextListItem): update `borderRadius` and enhance `renderItem` functionality

---

src/components/weather/DailyWeather.tsx

- updated control to less than 9.5 to remove the unnecessary gap caused by values above 9.50 being completed to 10
- added standard width to fix the problem of items not being sorted properly on the daily weather section
- added `itemsCenter` prop to center items horizontally in `WrapperRow`
The background color of the weather section has been set to red to better show the difference
|before|after|
|--|--|

fix(weather): adjust temperature display logic and styles

---

src/components/vouchers/VoucherRedeem.tsx
src/helpers/matomoHelper.js

- updated `uuid` import in `VoucherRedeem` and `matomoHelper` to use `expo-crypto`'s `randomUUID` for consistency
- improves code clarity and reduces dependency on external uuid library
SVASD-129

fix(helpers): replace `uuid` import with `expo-crypto`'s `randomUUID`

---

src/components/waste/WasteCollectionListItem.tsx
src/helpers/parser/listItemParser.js
src/hooks/waste.tsx
src/queries/waste.js

- updated query to add note feature for waste calendar
- used `pickUpTimes` instead of `listPickUpDates` for the data in the `useWasteMarkedDates` hook to show the notes in the list
- added `Tooltip` component to show if there is a note for a date
SVA-1510
|before|after|after|
|--|--|--|

feat(waste): add note for waste

---

src/hooks/imagePicker.ts

- added android control for android platform to fix the problem of the effect of saving the same image to the gallery twice when saved to both the camera album and the album created with the app name by referencing the same image
SUE-163

fix: the problem of the effect of saving the image twice for android

---

src/components/oParl/Meeting.tsx
src/components/oParl/oParlHelpers.ts

- replaced failing inline sorting logic with a dedicated helper function for better readability and maintainability
- sort not just numbers, but roman numbers and things like "1.a, 1.b" as well
- entries with roman numbers should always be listed first
|before|after|
|---|---|
|![Simulator Screenshot - iPhone 16 Pro Max - 2025-04-17 at 10 44 41](https://github.com/user-attachments/assets/677f6fc6-f998-40fc-a541-90254fa52ef9)|![Simulator Screenshot - iPhone 16 Pro Max - 2025-04-17 at 10 44 58](https://github.com/user-attachments/assets/5c33a292-40b8-423a-b685-c45e6c83befd)|
SVASD-151

feat(oparl): add special agenda items sorting

---

package.json
src/components/LiveTicker.tsx
src/components/index.js
src/screens/HomeScreen.js
yarn.lock

With this PR, a live ticker feature is added to the HomeScreen that can be updated via the main-server.
To activate this feature on the HomeScreen, create a json static content named `homeLiveTicker` on main-server
`homeLiveTicker` static content can be as follows
```
{
"text": "Smart Village App ❤️",
"liveTickerSettings": {
"speed": 0.5,
"style": {
"backgroundColor": "#E5BFF7",
"paddingVertical": 20
}
}
}
```
SVAK-142

feat(live ticker): add live ticker feature to `HomeScreen`

---

src/config/navigation/tabConfig.tsx
src/navigation/MainTabNavigator.tsx
src/types/Navigation.ts

- added `activeIconName` to add the option to use a different icon when the tabbar is active
SVA-1555
In the screenshots, the active and deactive icon of the 3rd icon from the right is activated. It can be seen that the icon changes when Tab is selected.
|||
|--|--|

feat(tabbar): add the ability to use different icons when tabbar is active

---

.codeclimate.yml

- added file types we don't want codeclimate to scan to `exclude_paths`
- added .ts and .tsx file types that we want to be rated by codeclimate to the `ratings` section
SVA-1557

fix(codeclimate): disable files that are unnecessary to scan

---

src/components/Checkbox.js
src/config/texts.js
src/screens/AppIntroScreen.tsx

- added `backgroundColor` prop to update the background color of onboarding
- updated the `renderSlider` function to show the incoming order of content
- added `handleSkip` to redirect to that slide if there is `termsAndConditions` checkbox when skip button is pressed
- added `handleSlideChange` to show alert with next button if there is `termsAndConditions` checkbox
- added `bottomButton` prop to style and `AppIntroSlider` component to show next and skip buttons above the dots
- updated text file to show on skip button
SVA-1577
|before|after|before|after|before|after|
|--|--|--|--|--|--|

feat(onboarding): add 'skip' option to app intro

---

src/components/map/MapLibre.tsx

This PR adds the ability to add new pins to the map view in the Maplibre component
|without new pin|with new pin|with new pin without cluster|
|--|--|--|
SVA-1365

feat(map): add pin to map

---

src/components/map/MapLibre.tsx

This PR adds the polyline property to the maplibre component
to test: 
- Download the json data and add it to the `src/screens` folder
[geometryTourData.json](https://github.com/user-attachments/files/19871094/geometryTourData.json)
- Import this data into `MapScreen.tsx` and add it as a prop to the `MapLibre` component
SVA-1365

feat(map): add polyline attribute

---

src/components/map/MapLibre.tsx
src/screens/SUE/SueMapScreen.tsx

This PR adds the ability to show active and inactive icons to the MapLibre component
|inactive pin|active pin|
|--|--|
SVA-1365

feat(map): add the ability to show a different icon when selected

---

src/components/screens/Service.tsx
src/components/screens/ServiceTile.tsx

This PR ensures that the tiles in the last row are centered.
|before|after|
|--|--|
EP-71

feat(service): add `isLastRow` prop to `ServiceTile` and update rendering logic

---

src/pushNotifications/PermissionHandling.ts

This PR fixes the issue where the push switcher appears on when you close and open the app after turning off the push settings in the app.
The problem was solved by adding inAppPermission control.
As viewed by the user:
- User opens the app and allows push notifications
- Then the user who doesn't want push notifications goes to settings and turns off push permissions
- After closing and reopening the app, the Async Storage value that we saved for push notifications will be updated with true again since there is no `inAppPermisson` control because we did not close the permission in the operating system, we only closed the push permission in the app.
SVA-1619

fix: app push switcher is always on

---

app.json

With this PR, it increases the targetSdkVersion to 35, which is mandatory after the new policy update in the Play Store.
SVA-1637

feat(android): upgrade target sdk version to 35

---

src/components/screens/ServiceTile.tsx

With this PR, it solves the problem that tiles are not displayed correctly on the tile edit page
|--|--|--|--|
custom tiles:
|--|--|--|--|
SVA-1638

fix(tiles): errors in customizable

---

src/hooks/personalizedTiles.ts

Solves the problem of non-display of non-customizable tiles with this PR
|before|after|
|--|--|
SVASD-196

fix: the problem of invisibility in non-customizable tiles

---

src/components/screens/OpeningTimesCard.js
src/components/volunteer/VolunteerAppointmentsCard.tsx
src/components/volunteer/VolunteerEventRecord.tsx

The presentation for all day appointments were a bit off. With the refactoring we will see the same alignment as if there would be some times for the dates. On the other hand, The end date were not presented correctly if it represents full days. Events from 08.08 - 09.08. were shown as 08.08 - 10.08. before.

feat(volunteer): enhance appointment handling

---

src/components/screens/ServiceTile.tsx

This PR solves the problem that the space between the tiles in the last row is not visible
|before|after|
|--|--|
SVA-1384

feat(tiles): add space between tiles in last row
