CHANGELOG.md
README.md
app.json
package.json
src/index.js
src/screens/HomeScreen.js
src/screens/IndexScreen.js
yarn.lock

- setup Apollo GraphQL client: https://www.apollographql.com/docs/react/
- a local development address is given for the GraphQL server uri
- implemented cache persisting with https://github.com/apollographql/apollo-cache-persist
to AsyncStorage
- made first queries
- on HomeScreen querying data from locally connected main server
- on IndexScreen querying data from the client store
- for `fetchPolicy`s see https://www.apollographql.com/docs/react/api/react-apollo#graphql-config-options-fetchPolicy
- increased version to 0.2.0

Setup Apollo GraphQL client with cache persisting

---

src/helpers/index.js
src/helpers/shareHelper.js
src/queries/index.js
src/screens/DetailScreen.js
src/screens/HomeScreen.js
src/screens/IndexScreen.js

- https://docs.expo.io/versions/v32.0.0/react-native/share
- created share helper function
- added params for shareContent to navigation params, that will
be used for share dialog opened from DetailScreen
- added missing line trimming of HtmlView in DetailScreen
---
**share dialog iOS**
**share content example**
> [Bad Belzig App] 28.05.2019 | RSS: Dörferberatung – Ein Fazit

Implement simple share function of detail screens

---

src/components/screens/InfoCard.js
src/components/screens/PointOfInterest.js
src/queries/pointsOfInterest.js

- added new key lastName/contact in query
- created new info box with category in InfoCard
- using RN elements Icons

Update  InfoCard data

---

src/navigation/defaultStackNavigatorConfig.js

Created a condition so that : 
- iOS has bold text
- android regular text (bold text is was not good looking on android header)
- fontWeight is required form default stack navigation

Update on header

---

src/components/screens/InfoCard.js
src/queries/pointsOfInterest.js
src/queries/tours.js

We missed to show the addition in the detail view.

Add addition to address in DetailScreen

---

src/components/screens/NewsItem.js

We sadly missed to refactor the title correctly in NewsItem.

Fix title for NewsItem on DetailScreen

---

src/components/Link.js
src/components/screens/InfoCard.js
src/components/screens/OperatingCompanyInfo.js
src/queries/eventRecords.js

Changes according to CMS 
- rendering first and last name (InfoCard + OperatingCompanyInfo)
- rendering description instead of url when there is one  (InfoCard + Link)
- rendering addition in address (OperatingCompanyInfo)

Updates in events detail screen 

---

src/components/screens/PriceCard.js
src/config/colors.js

- added a color variable for maintainability
- used the darker parimary color with opacity
- changed hardcoded color to new variable in PriceCard

Add color variable in price card

---

src/auth.js
src/index.js

- added access to secrets per namespace
- namespace is used form slug given in app.json

Add namespace to secrets for multiple domains

---

src/components/Link.js
src/components/Text.js
src/components/screens/InfoCard.js
src/components/screens/OperatingCompanyInfo.js
src/components/screens/TourCard.js
src/screens/CompanyScreen.js
src/screens/ServiceScreen.js

- it's named primary now from primary color which is the characteristic of this prop
Resolves #50

Rename prop link in text style component

---

src/screens/CompanyScreen.js
src/screens/ServiceScreen.js

- with this new feature one can setup "iconName"s in the
json data on the server to define icons of the icon set
used in `TabBarIcon`

feature(icons): allow icon names in service boxes

---

src/components/Image.js
src/components/ImageRights.js
src/components/screens/EventRecord.js
src/components/screens/NewsItem.js
src/components/screens/PointOfInterest.js
src/components/screens/Tour.js
src/queries/eventRecords.js
src/queries/newsItems.js
src/queries/pointsOfInterest.js
src/queries/pointsOfInterestAndTours.js
src/queries/tours.js

This pull request introduces copyright texts on images.
Please see the commits for more details.
Example 1 | Example 2
------------ | -------------

feat(image rights): show image rights

---

src/components/HtmlView.js
src/components/Link.js
src/components/screens/EventRecord.js
src/components/screens/InfoCard.js
src/components/screens/NewsItem.js
src/components/screens/OperatingCompanyInfo.js
src/components/screens/PointOfInterest.js
src/components/screens/Tour.js
src/helpers/linkHelper.js
src/screens/HtmlScreen.js
src/screens/IndexScreen.js

- added `openWebScreen` navigation method in components
where necessary to open links
- if a link is determined, do not open the url in an external browser,
but navigate to the web view with the web url to open

feat(external links): open all links in internal web view

---

src/components/CardList.js
src/components/TextList.js
src/queries/eventRecords.js
src/queries/newsItems.js
src/screens/HomeScreen.js
src/screens/IndexScreen.js

This pull request introduces pagination for text lists. This will improve performance and usability significantly, as only a bunch of data is requested at a time. If there are plenty of data for a list, it takes too much time to query and render everything at one time.
Please see the commits for more details.

Pagination for text lists

---

src/NetInfo.js
src/NetworkProvider.js
src/helpers/graphqlHelper.js
src/index.js

Correct initial setup with global settings

---

src/queries/index.js
src/screens/FormScreen.js

- added missing case for app user content
- structured the file for better readability

Refactored main queries file

---

src/helpers/index.js
src/helpers/textHelper.js
src/screens/HomeScreen.js
src/screens/IndexScreen.js

- added text helper to conditionally render subtitles
- wanted to get rid of a | when there is no following text

feat: add text helper for formatting subtitle

---

src/components/CardListItem.js
src/components/Icon.js
src/components/SettingsListItem.js
src/components/Switch.js
src/components/TextListItem.js
src/components/ToggleListItem.js
src/components/index.js
src/config/colors.js
src/config/texts.js
src/navigation/AppStackNavigator.js
src/screens/HomeScreen.js
src/screens/SettingsScreen.js
src/screens/index.js

This PR introduces a new settings screen and an interface for first interactions.
The actions are not persisted yet.
The current development can be used to integrate the functionalities for the different options step by step.
Home Screen with Icon | Settings Screen | Activating Push
------------ | ------------- | -------------

integration of a settings area

---

src/hooks/index.js
src/screens/HomeScreen.js

#132: added export for push notification hook from index

---

src/components/screens/About.js
src/components/screens/HomeCarousel.js
src/components/screens/Service.js
src/helpers/refreshIntervalHelper.js
src/hooks/RefreshTime.ts
src/hooks/index.js
src/screens/AboutScreen.js
src/screens/CompanyScreen.js
src/screens/DetailScreen.js
src/screens/HtmlScreen.js
src/screens/ServiceScreen.js

As described in #121 there was a lot of code duplication for the refreshTime.
It is now centralised in a new custom hook.
There should be no visual changes.
The default value for the second argument was chosen because there was only one place that differed from it.
---
Fixes #121

Addition of a  useRefreshTime hook

---

src/components/ListComponent.js
src/components/index.js
src/helpers/index.js
src/helpers/queryDataParser.js
src/queries/index.js
src/queries/pointsOfInterest.js
src/queries/pointsOfInterestAndTours.js
src/queries/tours.js
src/queries/types.js
src/screens/HomeScreen.js
src/screens/IndexScreen.js

- refactor in preparation of the bookmark feature
- extracted parsing logic from IndexScreen and HomeScreen
- added ListComponent to handle selection by settings and query type
- replaced getComponent structure in IndexScreen by ListComponent
- replaced getListComponent structure in HomeScreen by ListComponent
at this point everything should still look and behave exactly the same 😄 
---
SVA-62

Unify ListComponent

---

src/screens/IndexScreen.js

- removed the style because the style property was not defined so never used

chore(IndexScreen): remove unnecessary style

---

src/components/CategoryList.js

- added check for section data to return no section header if there is no data
- added check for intro text to render no text and wrapper if there is no text

refactor(CategoryList): add checks for data and intro text

---

src/components/map/LocationOverview.tsx
src/helpers/graphqlHelper.js

- added fetchPolicy and skip parameter to queries

fix(location overview): fetch policy

---

src/components/CardList.js
src/components/CardListItem.js
src/components/Text.js
src/components/widgets/EventWidget.tsx
src/components/widgets/Widgets.tsx
src/helpers/graphqlHelper.js
src/icons/calendar.js
src/icons/index.js
src/queries/eventRecords.js
src/screens/HomeScreen.js
src/screens/IndexScreen.js

Added an event widget to the home screen
- it shows the number of events that are active today.
- interaction will lead to the index screen for the events, filtered for today.
- changed condition to in index screen to still render header and list if data length is 0
- otherwise the filter logic needs to be entirely reworked for the event widget
---
SVA-82

feature: event widget

---

src/screens/FormScreen.js

CheckBox text has been corrected from a question to a statement.

chore(feedback form): small correction on check-box text

---

src/navigation/defaultStackNavigatorConfig.js

- changed the screen title to be left aligned
Before:
After:

style(header title): left aligned

---

src/components/weather/DailyWeather.tsx
src/components/weather/HourlyWeather.tsx
src/components/weather/WeatherAlert.tsx
src/components/widgets/WeatherWidget.tsx
src/config/texts.js
src/navigation/AppStackNavigator.js
src/screens/WeatherScreen.js

- refactorings
- style adjustments
- fix for offline (polling)
please see the commit messages for detail
SVA-80
---
screens for new landscape mode after orientation change:

finish weather widget and weather screens

---

src/screens/ConstructionSiteOverviewScreen.js

Refactored the ConstructionSiteOverview to use TextListItem to increase maintainability of the codebase.

refactor(construction site): use textlistitem for better maintainability

---

src/navigation/AppStackNavigator.js

- added Form to AppStackNavigator to be able to navigate to the form screen with drawer mode apps

Add form as route for drawer

---

babel.config.js
package.json
src/components/Image.js
src/components/ImageMessage.js
src/components/ImagesCarousel.js
src/components/ImagesCarouselItem.js
src/components/index.js
src/components/screens/HomeCarousel.js
src/helpers/momentHelper.js
src/screens/HomeScreen.js
yarn.lock

SVA-81 build from three previous PRs: https://github.com/ikuseiGmbH/smart-village-app-app/pull/174 https://github.com/ikuseiGmbH/smart-village-app-app/pull/175 and https://github.com/ikuseiGmbH/smart-village-app-app/pull/176

Time of day dependent welcome message

---

src/components/DropdownHeader.js

- one entry means two items (Alle + entry)

feat(filter): do not show a filter when there is just one entry

---

src/components/widgets/ConstructionSiteWidget.tsx
src/components/widgets/DefaultWidget.tsx
src/components/widgets/EventWidget.tsx
src/components/widgets/LunchWidget.tsx
src/components/widgets/WeatherWidget.tsx
src/components/widgets/Widgets.tsx
src/navigation/AppStackNavigator.js
src/screens/HomeScreen.js
src/types/WidgetProps.ts
src/types/index.ts

- added option to customize texts serversided
- exchanged widget touchable with touchable opacity
- with no padding horizontally the touch shadow looked wrong
SVA-154

feature(widgets): customizable texts

---

src/components/screens/About.js
src/components/screens/Service.js
src/screens/HomeScreen.js

- added useHomeRefresh to remaining components

refactor(home screen): useHomeRefresh

---

src/components/StorySection.js

An error in the logic to handle the "display only summary" setting caused the body to not show under certain circumstances.

fix(story section): error in logic to display body

---

src/components/Image.js
src/components/ImagesCarousel.js
src/components/ImagesCarouselItem.js
src/hooks/TimeHooks.ts
src/hooks/index.js

- added option to set a refresh interval for the image component
- added parsing of refresh interval for ImagesCarousel
The first image on the internal test server has a refresh interval set. So let the app run against that server and try it out :)
SVA-182

feat(image): add refresh interval

---

src/config/texts.js
src/screens/WeatherScreen.js

- added pull to refresh for weather screen
- added proper component if there is no data

feat(weather): pull to refresh

---

src/components/infoCard/AddressSection.tsx

- hide address entry if the string is empty

fix(address): hide empty address

---

src/components/TextListItem.js

fix(textListItem): remove unnecessary noSubtitle prop

---

src/components/DropdownSelect.js

- added orientation handling for dropdown
SVA-180
----
Labeled as draft as I am unsure, if this is what we actually want/need here.

fix(dropdown): position in landscape mode

---

src/components/map/LocationOverview.tsx
src/components/map/WebViewMap.tsx
src/components/screens/PointOfInterest.js
src/config/texts.js
src/screens/ConstructionSiteDetailScreen.js

- added placeholder text while no POI is selected to make functionality apparent
- added a default zoom level
SVA-188

Location Overview: better zoom and placeholder while no POI is selected

---

src/screens/WasteCollectionScreen.js

- increased marking dot size to 6 (was 4)
SVA-79

style(waste calendar): dot size

---

src/components/CrossData.tsx
src/components/DataProviderButton.tsx
src/components/Offer.js
src/components/index.js
src/components/screens/EventRecord.js
src/components/screens/NewsItem.js
src/components/screens/PointOfInterest.js
src/components/screens/Tour.js
src/config/texts.js
src/helpers/genericTypeHelper.ts
src/queries/genericItem.js
src/screens/BookmarkScreen.js
src/screens/DataProviderScreen.js

- changed strings for commercials to the ones agreed upon in SVA-77
- added function to get section title from genericType
- reused it in bookmark screen
- added jobs and ads as sections to the data provider screen
- they are now located above the rest of the sections
SVA-192

feat(cross data): added jobs and ads

---

PULL_REQUEST_TEMPLATE.md

Added reminders for screenshots and testing to the PR template

chore(pr template): added basic testing reminders

---

src/hooks/apollo.ts
src/queries/OParl/index.ts
src/queries/OParl/organization.ts
src/queries/OParl/person.ts
src/screens/OParl/OParlPeopleScreen.tsx
src/types/OParlObjectTypes.ts

- big oparl systems were running into performance and stability issues

feat(oparl): added pagination to people screen

---

src/components/Button.js
src/config/texts.js
src/hooks/surveyHooks.ts
src/queries/survey.js
src/screens/SurveyDetailScreen.tsx

- reworked the Button component, to allow for disabled state
- expanded upon useAnswerSelection hook to handle all state logic, as well as mutations
- implemented all necessary changes to SurveyDetailScreen
---
SVA2-12, SVA2-21

Survey: added submission logic to detail screen

---

src/components/Results.tsx
src/components/SurveyAnswer.tsx
src/screens/SurveyDetailScreen.tsx
src/screens/SurveyOverviewScreen.tsx

- the `Results` are now shown for archived surveys
- the answer options are no longer interactable for archived surveys
- the button (and hint text) are no longer shown for archived surveys

Survey: Archived Survey Logic

---

src/components/BB-BUS/Authority.js
src/components/BB-BUS/Block.js
src/components/BB-BUS/Persons.js
src/components/BB-BUS/TextBlock.js
src/components/BB-BUS/helpers.js
src/screens/BB-BUS/DetailScreen.js

- Removed accordion logic in favor of more simple logic.
- reduced the number of `openWebScreen` functions
- added missing return statement to `removeCommunicationsNesting`
---

Refactor: bb-bus detail

---

src/screens/HomeScreen.js

- replaced the hard coded navigation titles from the navigation params
- replaced them by the section titles

fix(home screen): navigation titles

---

src/components/BB-BUS/Persons.js

The title prop for the Person Block was not undefined, which caused an error.

BB-Bus: person block title

---

src/components/screens/ServiceTiles.js
src/components/screens/index.js
src/screens/CompanyScreen.js
src/screens/ServiceScreen.js

- extracted duplicated code from company and service screens

refactor(service tiles): duplicated code

---

CHANGELOG.md
README.md
app.json

- updated CHANGELOG
- updated README
- updated version number everywhere

Increase version to 1.8.0

---

src/config/navigation/defaultStackConfig.tsx

fix(default stack config): use headerRight config everywhere

---

src/config/navigation/config.ts

chore: reorder navigator config for easier commenting

---

src/SettingsProvider.js
src/config/consts.js
src/config/navigation/defaultStackConfig.tsx
src/config/navigation/index.ts
src/config/navigation/tabConfig.tsx
src/index.js
src/navigation/CustomDrawerContentComponent.js
src/navigation/DrawerNavigator.tsx
src/navigation/DrawerNavigatorItems.js
src/navigation/Navigator.tsx
src/screens/HomeScreen.js

- removed remnants of navigation config from global settings
- removed unused consts
- added index file to navigation config folder
Fixes #255
---
There should be no visual changes.

chore(navigation config): remove from global settings

---

src/components/widgets/SurveyWidget.tsx
src/components/widgets/Widgets.tsx
src/config/Icon.tsx
src/config/texts.js

- added new survey widget
- the widget shows the current number of ongoing surveys and navigates to the survey overview if clicked
---
SVA-256

Feature: survey widget

---

src/components/SurveyAnswer.tsx

- the german answers were displayed as the polish answers as well
---
SVA2-35
---

fix(survey): only german answers

---

src/components/widgets/ConstructionSiteNewsWidget.tsx
src/components/widgets/Widgets.tsx
src/helpers/queryDataParser.js
src/screens/DetailScreen.js
src/screens/IndexScreen.js
src/types/WidgetProps.ts

- added new widget for construction sites which are represented as newsitems
---
SVA-274

feat(widgets): construction sites as news

---

package.json
src/helpers/storageHelper.js
src/pushNotifications/WasteReminder.ts
tsconfig.json

- removed "EXPO_NO_TYPESCRIPT_SETUP" from yarn start
- applied expo setup for typescript
- auto imports work fine again with current vscode
Please double check with your vscode @donni106

ts config: apply expo setup

---

src/components/ShareHeader.tsx
src/helpers/shareHelper.js
src/hooks/openWebScreen.ts

- added the correct type to openShare and fixed the types for ShareHeader and useOpenWebScreen
closes #294

chore(shareContent): improve type of openShare

---

src/screens/HtmlScreen.js

- added the possibility to pass in a params object instead of only a webUrl
---
SVA-302

feat(html screen): improved subqueries

---

src/helpers/parser/listItemParser.js

- added an array of types to filter instead of checking each type individually
- added `GenericType.Commercial` to the array
---
SVA-269

fix(commercial): filter by date

---

src/config/texts.js

fix: correct translation of verified verification status

---

src/screens/EncounterDataScreen.tsx
src/screens/EncounterHomeScreen.tsx

changed the touchables to be touchable opacities instead
SVA-352

Fix: encounter information icons not clickable on android

---

src/screens/EncounterDataScreen.tsx

- exchanged the support id input with a selectable text
- fixed lable for verified status
---
SVA-370

Encounter: minor improvements

---

src/components/Results.tsx
src/components/SurveyAnswer.tsx
src/config/texts.js
src/hooks/surveyHooks.ts
src/queries/survey.js
src/screens/SurveyDetailScreen.tsx
src/types/Survey.ts

- updated all relevant places to use string arrays instead of a single string for selections of answers
- added extra logic to ensure old stored submissions are handled correctly
- removed redundant condition from submission function
- it does not cause real issues if the condition is not met
- the condition is already checked on the detail screen itself as part of the button disabled condition
- added a hint that multiple options can be selected
---
SVA-361
- The survey with title `Test mit HTML` is multi select

Survey: allow selection of multiple answers for surveys that have it enabled

---

src/queries/categories.js

- added ids as query param to categories query
---
SVA-366
---

feat(categories): filter by ids

---

src/config/navigation/defaultStackConfig.tsx
src/queries/categories.js
src/screens/MultiButtonScreen.tsx
src/screens/index.js
src/types/Navigation.ts

- added a new screen that allows for multiple buttons and texts based on a static json file
---
SVA-366
---
- added a new navigation point to the bottom of the drawer navigation for the internal test

Feature: multi button screen

---

App.js

- fixed sentry setup in regards to expo
SVA-404

fix(sentry): setup with expo

---

src/components/Image.js

- trimmed the uri if present
- destructured source from props again to get rid of type inference issue
---
SVA-391
closes #410 
---
the home image on the internal development currently has whitespace in the url. with this fix the permission request should no longer trigger

Fix: photo permission bug

---

src/queries/pointsOfInterest.js

- **before this is added to a release, the servers need to be updated. otherwise there will be gql errors**
SVA-367

feat(pois): filter by location

---

src/components/FeedbackFooter.tsx

the import from `'.'` caused a require cycle, so i removed it.

fix(feedback footer): require cycle

---

src/queries/pointsOfInterest.js
src/queries/tours.js
src/screens/MultiButtonScreen.tsx

- added option for multiple category ids for points of interest
- updated tours query with new possible params
- added pull to refresh for multi button screen to be able
to trigger updates on the fly instead of waiting for the next day
- adjusted return of render item function with removal of unnecessary nesting
SVA-475

fix(categoryIds): add param to attraction queries

---

src/helpers/momentHelper.js
src/helpers/parser/listItemParser.js

- added new helper to use where needed
SVA-496
---
We should check in the future, which places might be affected as well.

fix(local time): parsing moments from utc strings

---

src/components/screens/NewsItem.js

SVA-496
created #483 to take care of remaining places.

fix(date): newsitem detail showing wrong date for midnight

---

src/components/volunteer/VolunteerWelcome.tsx
src/screens/volunteer/VolunteerLoginScreen.tsx

- updated register button navigation to webview
and removed invitation link that pointed there
before
- adjusted injected adjustments of the webviews
for register and password reset to reduce "foreign"
elements
HDVT-39

Volunteer: register webview

---

src/components/volunteer/VolunteerFormConversation.tsx
src/components/volunteer/VolunteerGroup.tsx
src/components/volunteer/VolunteerGroupMember.tsx
src/components/volunteer/VolunteerTask.js
src/components/volunteer/VolunteerUser.tsx
src/components/volunteer/index.ts
src/config/texts.js
src/helpers/parser/listItemParser.js
src/helpers/queryHelper.ts
src/hooks/volunteer/data.ts
src/queries/index.js
src/queries/types.ts
src/screens/volunteer/VolunteerDetailScreen.tsx
src/screens/volunteer/VolunteerFormScreen.tsx
src/screens/volunteer/VolunteerMeScreen.tsx
src/screens/volunteer/VolunteerPersonalScreen.tsx

- list group members in groups on new index screen
- navigate in members to see user details
- start conversations from group member user details
HDVT-23

feat(volunteer): list group members

---

src/components/volunteer/VolunteerEventAttending.tsx
src/components/volunteer/VolunteerEventRecord.tsx
src/components/volunteer/VolunteerUser.tsx
src/config/texts.js
src/helpers/parser/listItemParser.js
src/helpers/queryHelper.ts
src/hooks/volunteer/data.ts

- list event participants in events on new index screen
- navigate in participants to see user details
- start conversations from event participant user details
HDVT-23

feat(volunteer): list event participants

---

src/components/DropdownSelect.js
src/components/form/DropdownInput.tsx
src/components/volunteer/VolunteerConversationsSection.tsx
src/components/volunteer/VolunteerFormConversation.tsx
src/components/volunteer/VolunteerMessageTextField.tsx
src/components/volunteer/index.ts
src/config/Icon.tsx
src/helpers/parser/listItemParser.js
src/hooks/volunteer/data.ts
src/hooks/volunteer/user.tsx
src/queries/volunteer/conversation.ts
src/screens/volunteer/VolunteerDetailScreen.tsx
src/screens/volunteer/VolunteerIndexScreen.tsx
src/screens/volunteer/VolunteerPersonalScreen.tsx
src/types/volunteer/conversation.ts

Example with three different accounts:

Volunteer: group messages and auto refresh

---

src/queries/categories.js

feat(categories): add query param to exclude specific ids

---

src/components/EmptyMessage.js
src/components/EventList.js
src/components/ListComponent.js
src/components/VerticalList.js
src/components/index.js
src/config/Icon.tsx
src/config/texts.js
src/screens/HtmlScreen.js
src/screens/IndexScreen.js

"No content found" text added by default on a page without content.
The EmptyPage.js file has been created in the Components folder. Updated IndexScreen.js and HtmlScreen.js pages. 
home screen events widget | no events for the current day | home screen about item at the bottom | no content
-- | -- | -- | --
 ![HomeScreen](https://user-images.githubusercontent.com/1942953/150178917-29fbf1f5-2b35-4504-9eb3-0d772d9a21b7.png) |  ![Simulator Screen Shot - iPhone 13 - 2022-01-21 at 13 33 27](https://user-images.githubusercontent.com/11755668/150515452-7a3a411d-0d74-446b-89e9-7791b17bcbf1.png) | ![HomeScreen](https://user-images.githubusercontent.com/1942953/150178965-cf0f9af1-a58d-4f2c-adb4-a54762fb4e67.png)  |  ![Simulator Screen Shot - iPhone 13 - 2022-01-21 at 13 33 …

feat(empty screen): new empty message component

---

src/queries/types.ts

- prefixed query type values that werde duplicated across
consul and volunteer to avoid impossible mappings
- sorted query types alphabetically for better handling

fix(volunteer & consul): prefixed query types

---

src/components/screens/consul/Debates/DebateDetail.js
src/components/screens/consul/Debates/Debates.js
src/components/screens/consul/Polls/PollDetail.js
src/components/screens/consul/Polls/Polls.js
src/components/screens/consul/Proposals/ProposalDetail.js
src/components/screens/consul/Proposals/Proposals.js
src/components/screens/consul/User/User.js
src/components/screens/consul/UserComments/UserCommentDetail.js
src/components/screens/consul/UserComments/UserComments.js
src/components/widgets/Widgets.tsx
src/screens/consul/ConsulDetailScreen.js
src/screens/consul/ConsulIndexScreen.js
src/screens/volunteer/VolunteerDetailScreen.tsx

- added empty message component for screens with no content
you can use it without any special adaptation
---
||
|--|
|![Simulator Screen Shot - iPhone 13 - 2022-04-27 at 14 37 19](https://user-images.githubusercontent.com/11755668/165519564-91cf0a8f-8c66-44c2-b713-4401fe085ad2.png)
SVA-403

feat(consul): add empty message

---

src/hooks/listHooks.js

**EPIC** volunteer

---

src/components/consul/ConsulWelcome.js
src/screens/consul/LoginRegister/ConsulRegisteredScreen.js

- updated the static contents that were fetched for
consul screen to avoid conflicts with volunteer contents
when they will differ at some point
SVA-403

fix(consul): static content names

---

src/components/consul/detail/ConsulCommentList.js
src/components/consul/detail/ConsulCommentListItem.js
src/components/screens/consul/Debates/DebateDetail.js
src/components/screens/consul/Polls/PollDetail.js
src/components/screens/consul/Proposals/ProposalDetail.js
src/config/Icon.tsx
src/screens/consul/ConsulDetailScreen.js

- added shadow to comment input (example taken from LinkedIn)
- relocated the submit button
- used `TouchableOpacity` is instead of `Button`
- changed placeholders of reply and comment inputs
- added send icon
---
|||
|--|--|
|New Comment Input | LinkedIn Comment Input|
SVA-403

style(consul): comment input

---

src/components/volunteer/VolunteerEventRecord.tsx
src/components/volunteer/VolunteerFormCalendar.tsx
src/components/volunteer/VolunteerFormGroup.tsx
src/config/texts.js
src/queries/volunteer/calendar.ts
src/queries/volunteer/group.ts
src/types/volunteer/calendar.ts
src/types/volunteer/group.ts

- added a new form field to enter organizational infos
that will be appended to the `description` as we do not
have an own field we can save the info at
- as we render the `description` in an html view, we can
use html tags for styling - so there will be a bold headline
- added a new form field to enter infos for participants
that will be rendered only in case of attending the event
- added a new form field to enter owner infos for groups
that will be appended to the `description` as we do not
have an own field we can save the info at
- as we render the `description` in an html view, we can
use html tags for styling - so there will be a bold headline
HDVT-13
HDVT-15
---
Event organizer:
|form|screen|
|---|---|
|![Simulator Screen Shot - iPhone 11 Pro - 2022-04-28 at 12 51 …

feat(volunteer): add form fields for event organizers, event participant infos and group owner

---

src/components/volunteer/VolunteerAvatar.tsx
src/components/volunteer/VolunteerEventAttending.tsx
src/components/volunteer/VolunteerGroupMember.tsx
src/helpers/volunteerHelper.ts
src/types/volunteer/index.ts
src/types/volunteer/user.ts

- created a new `useEffect` on the `VolunteerGroupMember`
page to fix the Avatar not displaying issue.
- created new `members` useState of `VolunteerUser`
type to avoid multiple renders
- added `VolunteerUser` type to avoid code duplication
- replaced the types used in `VolunteerAvatar` and
`VolunteerGroupMember`, `VolunteerEventAttending`
with `VolunteerUser` to  avoid code duplication
- added `VolunteerUser` type to `keyExtractor` in `VolunteerGroupMember`, 
to fix `guid = undefined` error
- created `attendees` state using `VolunteerUser` type
for `ListItem` data
- changed `acceptedMembers.slice` to `acceptedMembers?.slice`
because data on `VolunteerGroupMember`
page is undefined and causing crash
---

fix(volunteer): avatar

---

src/components/DropdownSelect.js
src/components/volunteer/VolunteerFormConversation.tsx

although the index changed when searching via dropdown, the data the user wanted to select was being matched with the data before the search was made
the array shown on the screen and the selected array are not the same

fix(volunteer): select multiple dropdown

---

src/helpers/volunteerHelper.ts
src/queries/volunteer/auth.ts
src/queries/volunteer/calendar.ts
src/queries/volunteer/conversation.ts
src/queries/volunteer/group.ts
src/queries/volunteer/post.ts
src/queries/volunteer/user.ts

- changed secret key from `version` to `v1`
- added secret key `v2` and exported a new `volunteerApiV2Url`
that can be used for new endpoints from the Smart Village App
HumHub module
HDVT-39

feat(volunteer): distinguish between v1 and v2 api

---

src/components/volunteer/VolunteerUser.tsx

- removed bad UI behavior with showing the email
address for a millisecond until `isMe` was set
with initializing without value and explicitly checking
for `true` and `false` on rendering
HDVT-39

fix(volunteer): hide user email

---

src/components/screens/consul/Proposals/NewProposal.js
src/components/screens/consul/Proposals/ProposalDetail.js
src/config/texts.js
src/hooks/imagePicker.ts
src/queries/consul/uploads/index.js
src/queries/consul/uploads/upload.js
src/queries/volunteer/index.ts
src/queries/volunteer/upload.ts

- added a new type named `PICKER` for the
photo upload component to the `INPUTS` JSON
- added a new button to the render function of
the `Controller` component to select an image
using the image picker
- added 2 different error messages because the
server only supports jpg format and the size of
the photo can be up to 1 megabyte.
- added `imageAttributes` to variables object
for image to be used in proposal mutation
- used `useSelectImage()` hooks to select
image from library
- deleted `resourceId` props from `upload.js`
as we don't need it
- changed the name of the alert function that
appears if the user has not approved the
TermsOfService to be more clear
- added defaultValue for image to remove warn
- added new `image` props to proposal edit
button to show image on edit page
- added …

feature: images upload

---

src/components/form/DropdownInput.tsx
src/components/volunteer/VolunteerCalendar.tsx
src/components/volunteer/VolunteerFormCalendar.tsx
src/components/volunteer/VolunteerGroup.tsx
src/config/texts.js
src/queries/volunteer/calendar.ts
src/types/volunteer/calendar.ts
src/types/volunteer/group.ts

- added a new form field to enter entrance fees
that will be appended to the `description` as we do not
have an own field we can save the info at
- as we render the `description` in an html view, we can
use html tags for styling - so there will be a bold headline
- adjusted incomplete types for calendar and group components
HDVT-13
|form|view|
|---|---|
|![IMG_0060](https://user-images.githubusercontent.com/1942953/168852894-8177bb5b-66dd-4e81-87c6-2034690ddda6.PNG)|![IMG_0059](https://user-images.githubusercontent.com/1942953/168852917-8783683d-7c89-4efc-a92d-d521f286d3c7.PNG)|

feat(volunteer): add form field for entrance fees

---

src/components/consul/selectors/DocumentSelector.js
src/components/consul/selectors/ImageSelector.js
src/components/screens/consul/Proposals/NewProposal.js
src/components/screens/consul/Proposals/ProposalDetail.js
src/config/texts.js
src/queries/consul/Proposals/deleteAttributes.js
src/queries/consul/Proposals/index.js
src/queries/consul/Proposals/proposals.js

- added new `deleteImage` and `deleteDocument` 
mutation
- added `deleteImage` mutation to `ImageSelector`
component to delete image when editing proposal
containing image
- added `imageId` prop to `ImageSelector` because
id is required when deleting the image
- added `deleteDocument` mutation to `DocumentSelector`
component to delete the document while editing the
proposal containing the document
- added a new alert to prevent users from accidentally
deleting image and document
- added `onDeleteImage` and `onDeleteDocument` function 
that is triggered according to the result of Alert for the 
user who wants to delete a image and document
- added texts for new alert
SVA-612

feature(consul): add delete mutation

---

app.json

- fixed an issue where app language was showing as
English in App Store
> ⚠️ **We can't see if the language problem of the application in the App Store is resolved or not, until we get the build and upload it to the App Store.** ⚠️
SVA-621

feat: change app store language

---

src/BBBusClient.tsx
src/components/BB-BUS/Authority.js
src/components/BB-BUS/TextBlock.js
src/components/BB-BUS/helpers.js
src/queries/BB-BUS/getService.ts
src/screens/BB-BUS/DetailScreen.js
src/screens/BB-BUS/IndexScreen.js

* this PR introduces the necessary changes to work with the new version of the bb bus server that connects to a newer version of the bus api
* when this gets merged, the area ids of the communities need to be updated accordingly, as the ids used by the API have changed.
* the url pointing to the bb bus server needs to be adjusted as well
---
SVA-423

feat(bb bus): migrate to api v4

---

src/components/augmentedReality/ARObjectList.js
src/components/augmentedReality/ARObjectListItem.js
src/config/texts.js
src/screens/augmentedReality/ARShowScreen.js

- added `screenVideoRecording` function to
record the video of augmented reality object
- added the ability to take a screen video image
with the `_startVideoRecording` function thanks
to the ref added to the augmented scene
- added a button to the screen to enable screen
recording
SVA-633
|Screen Recording Button|
|--|

feat(ar): record screen

---

src/components/augmentedReality/ARObjectList.js
src/components/augmentedReality/ARObjectListItem.js
src/components/augmentedReality/AugmentedReality.js
src/components/augmentedReality/WhatIsARButton.js
src/components/augmentedReality/index.js
src/components/screens/Tour.js
src/config/texts.js
src/screens/SettingsScreen.js
src/screens/augmentedReality/ARShowScreen.js
src/screens/augmentedReality/ArtworkDetailScreen.js

- added `viro` components required to display
the test object we have
- added `ViroAmbientLight` component to
show 3d objects
- added `diffuseTexture` object in
`ViroMaterials.createMaterials` to add texture
to object
- added callback functions in `AugmentedRealityView`
to indicate whether the object has started loading,
is loading or has encountered an error
- added `RegularText` for test purposes to go to the
previous page from the ar show screen
- removed from the `WrapperWithOrientation`
component in the `AugmentedReality`
component to match the structure of the tour
detail page
- fixed the refetch param error required to
refresh the `ARModal` in `ARInfoScreen`
when going from `ARDetailScreen`
- added texture data to the `resources` prop
instead of `ViroMaterials.createMaterials` …

feat(ar): show ar model

---

src/components/augmentedReality/ARObjectList.js
src/components/augmentedReality/ARObjectListItem.js
src/components/augmentedReality/AugmentedReality.js
src/components/augmentedReality/WhatIsARButton.js
src/components/augmentedReality/index.js
src/components/screens/Tour.js
src/config/texts.js
src/screens/SettingsScreen.js
src/screens/augmentedReality/ARShowScreen.js
src/screens/augmentedReality/ArtworkDetailScreen.js

the files in local are all stored in an array
`viro` uses different types of data in different places
therefore we need to parse the array in local
- added parser to place all augmented
reality objects where `viro` wants them
SVA-633

feat(ar object): parse ar object

---

src/screens/augmentedReality/ARShowScreen.js

- integrated viro sound to allow users to
listen to audio
- added pause and start to a single state
to synchronise the animation with the audio
file
- updated `isStartAnimation` state name to
`isStartAnimationAndSound` for clarity
- added control according to the mp3 data of
the 3D object so that the application does
not crash
- added `isObjectLoading` control to run the
sound file when the object is loaded
SVA-633

feat(ar): add viro sound

---

src/components/map/Map.tsx
src/components/oParl/Location.tsx

- updated `WebViewMap` component in location
component with new `Map`
- updated the `onMarkerPress` prop in the `Map`
component to optional as it is not always needed
- added if control according to `onMarkerPress`
prop to get rid of the error in `Marker`'s `onPress`
prop
SVA-634

feat(map): add on location component new map

---

src/components/screens/PointOfInterest.js

- added new `Map` to `PointOfInterest`
SVA-634
|Old Map|New Map|
|--|--|

feat(map): add on `POI` new map

---

src/components/screens/consul/Proposals/ProposalDetail.js

- added new `Map` to `ProposalDetail`
SVA-634

feat(map): add on proposal detail screen new map

---

src/screens/ConstructionSiteDetailScreen.js

- added new `Map` to `ConstructionSiteDetailScreen`
SVA-634

feat(map): add on `ConstructionSiteDetailScreen` new map

---

src/queries/volunteer/user.ts

- in order to request user data without being an admin we needed a new endpoint in our v2 api

feat(volunteer): update route for user requests with id

---

src/SettingsProvider.js
src/components/DataListSection.tsx
src/components/HomeSection.tsx
src/components/volunteer/VolunteerEventRecord.tsx
src/components/widgets/EventWidget.tsx
src/config/texts.js
src/helpers/parser/listItemParser.js
src/hooks/volunteer/data.ts
src/index.js
src/queries/volunteer/calendar.ts
src/screens/HomeScreen.js
src/screens/IndexScreen.js
src/screens/volunteer/VolunteerIndexScreen.tsx

This integrates volunteer events in main server events if a global setting is activated (`hdvt.events = true`).
HDVT-43
---
|home section|index|index today|detail|
|---|---|---|---|
|![Simulator Screen Shot - iPhone 11 - 2022-08-09 at 18 39 28](https://user-images.githubusercontent.com/1942953/183708780-0754a6c4-6aba-4fdf-9bb1-86cb351ca1be.png)|![Simulator Screen Shot - iPhone 11 - 2022-08-09 at 17 57 25](https://user-images.githubusercontent.com/1942953/183708793-a06b88de-b9a2-4dc4-aec5-d22748834e86.png)|![Simulator Screen Shot - iPhone 11 - 2022-08-09 at 17 57 31](https://user-images.githubusercontent.com/1942953/183708808-e3b2abf6-4107-43bd-ac5a-8c49ee7732cc.png)|![Simulator Screen Shot - iPhone 11 - 2022-08-09 at 18 39 45](https://user-images.githubusercontent.com/1942953/183708817-7dc …

feat(volunteer): hdvt events between main server events

---

src/components/consul/selectors/DocumentSelector.js
src/components/consul/selectors/ImageSelector.js
src/components/volunteer/VolunteerFormCalendar.tsx
src/config/texts.js
src/helpers/index.js
src/helpers/jsonParser.ts
src/queries/volunteer/calendarUpload.ts
src/queries/volunteer/index.ts
src/types/volunteer/calendar.ts

- refactored `DocumentSelector` and `ImageSelector` used
in consul for use in `HDVT`
- updated with `mutateAsync` in `onSubmit` function in
`VolunteerFormCalendar` to be able to upload data after the
appointment is created
- added `DocumentSelector` and `ImageSelector` components
to `VolunteerFormCalendar` to display `Document` and `Image`
selection buttons on the screen
- added `calendarUpload` query to be able to upload files
- added new types to calendar for `Documents` and `Images`
- added new text to `texts` file for document and image upload
features
HDVT-55
|Image and Document selection buttons|image supported by the server|Image not supported by the server and error message|
|--|--|--|
|image selection screen|document …

feat(volunteer): upload image and document for calendar

---

src/components/volunteer/VolunteerFormCalendar.tsx
src/hooks/listHooks.js

- solved cycle error caused by imports

fix: solve cycle warn

---

src/screens/augmentedReality/ARShowScreen.js

- deleted this feature because the screen recording
function does not work at the same time as the
music data
SVA-633

fix(ar): delete screen recording function

---

src/components/TextListItem.tsx
src/components/volunteer/VolunteerGroup.tsx
src/components/volunteer/VolunteerHomeSection.tsx
src/config/texts.js
src/helpers/parser/listItemParser.js
src/helpers/volunteerHelper.ts
src/hooks/volunteer/data.ts
src/queries/index.js
src/queries/volunteer/calendar.ts
src/queries/volunteer/group.ts
src/screens/volunteer/VolunteerPersonalScreen.tsx

Update user groups to show where member and also mark the groups with admin role.
|section|index|
|---|---|
|![Simulator Screen Shot - iPhone 11 - 2022-08-12 at 12 34 34](https://user-images.githubusercontent.com/1942953/184338098-5fa4c255-1e70-4dc4-ad8e-0b03045b7327.png)|![Simulator Screen Shot - iPhone 11 - 2022-08-12 at 12 34 37](https://user-images.githubusercontent.com/1942953/184338106-f07d276a-5c59-474d-848d-7c78e148a3a8.png)|
HDVT-14

feat(volunteer): list all my groups

---

src/config/navigation/tabConfig.tsx
src/navigation/MainTabNavigator.tsx
src/types/Navigation.ts

This way we can achieve fast changes of tab bar background colors with changes in `tabConfig.tsx`.
SVA-677

feat: customize colors of tab bar backgrounds

---

src/components/widgets/EventWidget.tsx

- we have to remove the date range if we don't want to start with a filtered list

fix: event widget initial list data

---

package.json
src/components/Chat.js
src/components/index.js
src/components/volunteer/VolunteerConversationsSection.tsx
src/components/volunteer/VolunteerMessage.tsx
src/helpers/parser/listItemParser.js
src/screens/volunteer/VolunteerDetailScreen.tsx
src/screens/volunteer/VolunteerPersonalScreen.tsx

- added `gifted-chat` package
- added new chat component
- added `UserAvatar` prepared for use in chat component
- added `alwaysShowSend` prop to show the send button
on the screen continuously
- added `onFocus` control to `messagesContainerStyle`
so that the messages are not under the input when the
keyboard appears on the screen
- added `onScrollToBottom` prop to quickly navigate to the
newest incoming message
- added `renderAvatar` prop to see avatar next to messages
from another user
- added `renderBubble` prop to create our own design in
message bubbles
- added `renderComposer` prop to render text input in the
design we want
- return `renderDay` prop as `null` because the date information
of the message is shown inside the message bubble in the
created design and add date information …

feat(volunteer): add gifted chat

---

src/CustomMatomoProvider.js
src/OParlClient.tsx
src/config/secrets.temp
src/hooks/apollo.ts
src/hooks/waterTemperature.ts
src/queries/waterTemperature.js
src/screens/OParl/OParlOrganisationsScreen.tsx

- for more flexibility in setup processes, configs should be editable without app builds

feat: move configs from secrets to global settings

---

src/components/Chat.js
src/config/Icon.tsx
src/screens/augmentedReality/ARShowScreen.js

- moved icons that were not defined in configs

refactor(icons): all icons in config

---

src/components/augmentedReality/AugmentedRealityView.js
src/helpers/augmentedReality/downloadObject.js
src/screens/augmentedReality/ARShowScreen.js

- added new data requested from the server
-  chromaKeyFilteredVideo
-  maxDistance
-  minDistance
-  physicalWidth
-  position
-  rolloffModel
-  rotation
-  scale
-  isSpatialSound
- added new data to the array of downloaded objects `(localUris)` inside `downloadObject`
- added `?` to provide data control
- deleted undefined data with `JSON.parse` because the data coming from the server may be undefined
- deleted previously used data as `position`, `rotation` and `scale` information comes from the server
- added `chromaKeyFilteredVideo` to remove unwanted background colour in videos
- added `ViroSpatialSound` component so that the sound file can have a Spatial property
- added `ViroVideo` component to show video on stage
- Added `ViroImage` component to show an image on stage
SVA-633

feat(ar): add new server requests, spatial sound, video and image components

---

src/components/map/Map.tsx

- `showsUserLocation = false` was causing location requests in iOS even if location services where turned off entirely
- added check for global setting and setting the default value for that special prop

fix(ios): location request on map

---

src/components/augmentedReality/AugmentedRealityView.js

- added `physicalWidth` value added to settings object in `globalSettings` to `AugmentedRealityView` page
SVA-565

feat(ar): add physical width value in global settings

---

src/screens/augmentedReality/ArtworkDetailScreen.js

- added `description` to `HtmlView` in `ArtworkDetailScreen` to show the description of the artwork
- deleted html static content because we no longer need it
SVA-565

feat(ar): add description to artwork detail page

---

src/components/Button.js
src/components/consul/selectors/DocumentSelector.js
src/components/consul/selectors/ImageSelector.js
src/components/form/DropdownInput.tsx
src/components/form/Input.tsx
src/components/volunteer/VolunteerEventRecord.tsx
src/components/volunteer/VolunteerFormCalendar.tsx
src/config/texts.js
src/queries/volunteer/calendar.ts
src/queries/volunteer/calendarUpload.ts
src/screens/volunteer/VolunteerFormScreen.tsx
src/types/volunteer/calendar.ts

- added a button on the right top of the 
header on the `VolunteerEventRecord` 
to redirect to the `VolunteerForm`
- added `shareContent` as param to 
show settings button and share button 
together
- added user information with the `checkIfMe` 
function because the user can only edit
their own event
- added style for buttons in header
- added default variables to 
all editable inputs to organise 
the event
- edited time variables inside 
the appointments object to 
prevent type error
- added default value to be able 
to edit files within the event
- sorted by file type in `fileFilters` 
because different file types are in 
the `files` array
- added update link to `calendar.ts` to 
organise the event
- replaced `POST` request with `PUT` 
to update the event if `calendarId` 
exists
- added …

feature(volunteer): editing of calendar data

---

src/components/Title.js
src/components/screens/PointOfInterest.js
src/components/screens/consul/Proposals/ProposalDetail.js
src/components/volunteer/VolunteerGroup.tsx
src/components/volunteer/VolunteerUser.tsx
src/screens/ConstructionSiteDetailScreen.js
src/screens/consul/LoginRegister/ConsulLoginScreen.js
src/screens/consul/LoginRegister/ConsulRegisterScreen.js
src/screens/volunteer/VolunteerLoginScreen.tsx
src/screens/volunteer/VolunteerRegisteredScreen.tsx
src/screens/volunteer/VolunteerRegistrationScreen.tsx
src/screens/volunteer/VolunteerSignupScreen.tsx

Adjust design a bit according to layouts.
HDVT-87
|login|register|code|
|---|---|---|
|![Simulator Screen Shot - iPhone 11 - 2022-11-01 at 16 59 21](https://user-images.githubusercontent.com/1942953/199279189-4b56a1bc-efa0-4734-a792-3efd636dfb22.png)|![Simulator Screen Shot - iPhone 11 - 2022-11-01 at 16 59 24](https://user-images.githubusercontent.com/1942953/199279195-a1b854a3-7368-465f-b05f-691e09942d9d.png)|![Simulator Screen Shot - iPhone 11 - 2022-11-01 at 16 59 26](https://user-images.githubusercontent.com/1942953/199279210-908f4df6-a2cf-4e96-8622-8b3c177fbd82.png)|

feat(volunteer): update login register

---

src/components/Chat.js

- updated the icon of the scroll
down button with `ArrowDown`
HDVT-85
|before|after|
|--|--|

feat(volunteer): update the icon of the scroll down button

---

src/components/volunteer/VolunteerGroup.tsx
src/hooks/volunteer/user.tsx

feature(volunteer): redirect unregistered users to `VolunteerHomeScreen`

---

src/config/texts.js

- updated `texts` file to change `Datenquelle` on the filter to `Datenquellenauswahl`
SVA-788
|before|after|
|--|--|

refactor: change wording on the data source filter

---

src/screens/volunteer/VolunteerPersonalScreen.tsx

feat(volunteer): navigate from personal to login if not logged in

---

src/components/Chat.js
src/components/volunteer/VolunteerAvatar.tsx
src/components/volunteer/VolunteerMessage.tsx

- deleted because the `UserAvatar` component is partly identical to `VolunteerAvatar`
- deleted styles needed for `UserAvatar` as unnecessary
- using the `userInfo` function for the `guid` and `title` required to use `VolunteerAvatar`
HDVT-85

refactor(volunteer): delete `UserAvatar` component

---

src/components/volunteer/VolunteerUser.tsx

- removed the wrapping view which caused problems on large screens
HDVT-87

fix(volunteer): tablet profile

---

src/components/volunteer/VolunteerEventRecord.tsx
src/components/volunteer/VolunteerFormCalendar.tsx
src/components/volunteer/VolunteerUser.tsx

- not only owners can create events but also members, so used "my groups" to fill the select list with possible groups to create an event in
HDVT-87

fix(volunteer): event creation

---

src/components/HomeService.js
src/components/index.js
src/components/screens/DraggableGrid.tsx
src/components/screens/DraggableItem.tsx
src/components/screens/Service.tsx
src/components/screens/ServiceTile.tsx
src/components/screens/ServiceTiles.js
src/config/Icon.tsx
src/config/texts.js
src/hooks/index.js
src/hooks/personalizedTiles.ts
src/screens/HomeScreen.js
src/screens/HtmlScreen.js
src/screens/TilesScreen.js
src/screens/volunteer/VolunteerHomeScreen.tsx
src/screens/volunteer/VolunteerPersonalScreen.tsx

SVA-740
**storage**
the values for sorting and toggling are stored as key/value entries on the device in an object with the name of the corresponding static json, example:
```
"townHall": Object {
"sorter": Object {
"Bürgeramt/Termine": 1,
"Bürgerbeteiligung": 6,
"Bürgermeister": 0,
"Bürgerservice": 2,
"Formulare": 3,
"Gemeindeporträt": 5,
"Kommunalpolitik": 9,
"Kontakt zur Verwaltung": 8,
"Presse": 7,
"Stellenangebote": 4,
},
"toggles": Object {
"Bürgeramt/Termine": 0,
"Bürgerbeteiligung": 0,
"Bürgermeister": 1,
"Bürgerservice": 0,
"Formulare": 1,
"Gemeindeporträt": 0,
"Kommunalpolitik": 0,
"Kontakt zur Verwaltung": 0,
"Presse": 1,
"Stellenangebote": 0,
"test": 0,
},
},
```
|tiles|bigtiles|with background gradient|
|---|---|---|
|![Simulator Screen Shot - iPhone 12 mini - 2022-11-18 at …

feat(personalized tiles): sorting and toggling visibility with storing on device

---

src/components/screens/EventRecord.js
src/queries/eventRecords.js

SVA-764
|without setting|with setting|
|---|---|
|![Simulator Screen Shot - iPhone 12 mini - 2022-11-29 at 17 41 28](https://user-images.githubusercontent.com/1942953/204592895-f5c655fd-0676-4af4-8b3c-9de9cc21424a.png)|![Simulator Screen Shot - iPhone 12 mini - 2022-11-29 at 17 41 40](https://user-images.githubusercontent.com/1942953/204592933-0ac11001-7382-4908-9c3f-520f43a919d7.png)|

feat: use data resource settings for toggling url links/buttons

---

src/components/CrossData.tsx
src/components/Offer.js
src/components/bookmarks/BookmarkHeader.tsx
src/config/consts.js
src/config/texts.js
src/helpers/genericTypeHelper.ts
src/helpers/parser/listItemParser.js
src/pushNotifications/TokenHandling.ts
src/queries/genericItem.js
src/screens/BookmarkScreen.js
src/screens/DetailScreen.js
src/types/GenericType.ts

feat(deadline): add content rendering for index and detail and toggle push device assignment

---

src/components/consul/selectors/ImageSelector.js
src/components/defectReport/DefectReportCreateForm.tsx
src/components/defectReport/DefectReportLocationForm.tsx
src/components/defectReport/index.ts
src/components/index.js
src/components/noticeboard/NoticeboardMessageForm.tsx
src/components/screens/consul/Proposals/NewProposal.js
src/components/settings/LocationSettings.js
src/config/consts.js
src/config/navigation/defaultStackConfig.tsx
src/config/texts.js
src/helpers/genericTypeHelper.ts
src/hooks/locationHooks.ts
src/queries/genericItem.js
src/queries/mediaContent.js
src/screens/DefectReport/DefectReportFormScreen.tsx
src/screens/DefectReport/index.ts
src/screens/DetailScreen.js
src/screens/index.js
src/types/GenericType.ts
src/types/Navigation.ts

- created new feature form to report defects
- refactored `ImageSelector` with a `isConsul` in addition to `isVolunteer` and added a default for our main server
- refactored location settings abort button to be the same as in the new screen being less significant
you need to add a new service icon in homeService for example
```
{
"title": "Mängelmelder",
"routeName": "Html",
"iconName": "warning-outline",
"params": {
"title": "Mängelmelder",
"rootRouteName": "Mängelmelder",
"query": "publicHtmlFile",
"queryVariables": {
"name": "defectreport"
},
"subQuery": {
"routeName": "DefectReportForm",
"buttonTitle": "Mängel melden",
"params": {
"rootRouteName": "Mängelmelder",
"consentForDataProcessingText": "Maecenas sed diam eget risus varius blandit sit amet non magna. Aenean lacinia bibendum …
```

feat(defect report): new form with image upload

---

src/components/weather/DailyWeather.tsx
src/components/weather/HourlyWeather.tsx
src/components/widgets/WeatherWidget.tsx
src/screens/WeatherScreen.js

- added `description` information from API to add alternative text to weather icons
SVA-868

feat(accessibility): add alternative text to weather icons

---

src/pushNotifications/PermissionHandling.ts
src/pushNotifications/TokenHandling.ts

- refactored code to understand whats happening
- fixed body of `removeTokenFromServer` to send correct data the server requires for a successful action
- info: this has changed in November 2020
SVA-932

fix: push notification settings

---

package.json
src/components/HtmlView.js
src/config/consts.js
src/config/styles/html.js
yarn.lock

- upgraded `react-native-render-html `package to version 6.3.4
- upgraded `@native-html/table-plugin `package  to version 5.3.1
- added `TableRenderer` instead of `renderers`   because `mateTableRenderer` is deprecated
- deleted because `alterNode` and `IGNORED_TAGS`   have been deprecated
- added `source` prop instead of `html` prop
- moved `onLinkPress` prop to section `a` in   `renderersProps`
- moved to the `renderersProps` prop as the   `cssRules` we used in the `makeTableRenderer`   section are deprecated
- updated `baseFontStyle` to `baseStyle`
- added `contentWidth` because `imagesMaxWidth`   is deprecated
- deprecated `alterChildren` prop and moved to   `onElement` in `domVisitors`
- added `systemFonts` prop to support the fonts   we use in the application
- added `margin` values …

chore: update react native render html package

---

src/AccessibilityProvider.tsx
src/helpers/accessibilityListeners.ts
src/helpers/index.js
src/index.js
src/types/Accessibility.ts
src/types/index.ts

- added listener to actively use the accessibility features supported by react native and manage changes in the application
- added new type to specify the type of listeners
- added provider to manage possible changes in accessibility
SVA-921
⚠️ accessibility features are generally supported by the iOS platform ⚠️
1. please take the above code and paste it into `VersionNumber.js`
```
export const VersionNumber = () => {
const { accessibility } = useContext(AccessibilityContext);
console.warn({ accessibility });
return (
<Wrapper>
{accessibility.isBoldTextEnabled ? (
<BoldText center small>
Version: {appJson.expo.version}
</BoldText>
) : (
<RegularText
small
style={styles.version}
accessibilityLabel={`${consts.a11yLabel.appVersion} ${appJson.expo.version}`}
>
Version: …
```

feat(accessibility): add provider and listeners

---

src/screens/HomeScreen.js

- replaced `ScrollView` with `FlatList` to remove `VirtualisedLists` error on `HomeScreen`
- added `flatListData` to show the content of `FlatList`
- added `ConnectedImagesCarousel` and `Widgets` shown in the top section of `HomeScreen` as `ListHeaderComponent` to `FlatList`
- added `HomeService` and `About`, shown at the bottom of `HomeScreen`, to `FlatList` as `ListFooterComponent`
- added the `HomeSection` component shown in the centre section of `HomeScreen` to the `renderItem` section of `FlatList`
|home screen header|home screen (home sections)|home screen (home sections)|home screen (footer)|
|--|--|--|--|

fix(VirtualisedLists): replace `ScrollView` with `FlatList`

---

src/screens/WasteCollectionScreen.js

and fix style of inputs
- the styles were applied to the wrong prop
- the top border of the second input was too thick
SVA-732

feat(waste calendar): preselect if there is only one street

---

src/components/survey/SurveyAnswer.tsx
src/screens/SurveyDetailScreen.tsx

- edited code for opacity to improve code clarity
SVA-928

refactor: set opacity for finished surveys options

---

src/components/Checkbox.js
src/components/Label.js
src/components/form/Input.tsx
src/config/texts.js
src/screens/FeedbackScreen.js
src/screens/consul/LoginRegister/ConsulLoginScreen.js
src/screens/consul/LoginRegister/ConsulRegisterScreen.js
src/screens/volunteer/VolunteerLoginScreen.tsx
src/screens/volunteer/VolunteerRegistrationScreen.tsx

- updated the inputs on the `FeedbackScreen` with `react-hook-form` to have the same structure everywhere in the code
- added `useMutation` instead of the old `Mutation` component to be able to use it with new inputs
- added all informative texts to `texts` file 
- changed styling to match the pre-update design
- added design missing props to `Input.tsx`
- added `boldLabel` feature to `Input`
- added `boldTitle` feature to `Checkbox`
- added `disabled` feature to send button on `FeedbackScreen`
- added `*` next to the labels of required inputs that must be filled
SVA-911
‼️ after this update, we can show the error messages we have created for the users under the inputs ‼️
‼️ before the update, we were only showing the please fill in the missing fields alert ‼️
|before|after|
|--|--| …

feat(feedback): update inputs with react hook form

---

src/config/texts.js
src/screens/FeedbackScreen.js

- removed the requirement for `Name`, `E-Mail` and `Telephone` inputs in the feedback form as they are not required inputs
- deleted the text inputsErrorMessages in the text file because it was not used
SBB-33

refactor: remove the requirement on inputs

---

src/screens/WasteCollectionScreen.js

- added `isStreetInputFocused` to recognise if input is pressed
- updated the `isStreetInputFocused` value to `true` in the `onFocus` prop to
recognise that it is focused on the street input
- added `isStreetInputFocused` control in `filterStreets` function for automatic
showing of streets
- updated `isStreetInputFocused` to `false` in the `onFocus` prop in the city input
to ensure that the streets are not visible
- added `isInputAutoFocus` value to `globalSettings` to activate the feature on the server
- removed `streetCount` limitation for listing all streets after auto-focus feature is activated
- added `height` property to `flatListProps` to display all elements in the list and make
the list scrollable
SVA-833
|before|after|
|--|--|

feat(waste calendar): show results when street input is pressed

---

app.json

- added `LSApplicationQueriesSchemes` to `info.plist` to redirect whatsapp links in the webview in the application to whatsapp application
SVA-1047

feat: add whatsapp link redirection to ios app

---

src/config/texts.js

- changed the text of the alert shown to users reporting defects at the request of the customer
SVA-1043
|before|after|
|--|--|

refactor: change the alert text of the defect reporter

---

package.json
yarn.lock

- added `expo-clipboard` package used in `ARShowScreen` again
SVA-1073

chore: add expo-clipboard package

---

src/components/screens/consul/Debates/NewDebate.js

- sorted alphabetically to make the input features more organised and easier to find
- added `containerStyle` according to platform to `description` section in `INPUTS` array to solve the problem of overlapping inputs
- added `maxHeight` so that the `tags` input in the `INPUTS` array does not overlap the `checkbox`
- added `textAlignVertical` property to start typing from above in message input
SVA-1099
|before - iOS|after - iOS|
|--|--|
|before - Android|after - Android|
|--|--|

fix: consul input's nesting problem

---

src/components/defectReport/DefectReportLocationForm.tsx
src/components/map/LocationOverview.tsx
src/components/map/Map.tsx
src/components/settings/LocationSettings.js

- added `zoomLevelForMaps` in `globalSettings` to `Map.tsx` so that zoom values of maps can be set from main server
- added the `isMultipleMarkersMap` prop to `Map.tsx` because we want the maps to have a different zoom value for POI and added the zoom value of the POI map according to this prop
- moved `Map.tsx` up in the code as we now need to use `globalSettings` for the zoom value
- deleted `zoom` prop as the `zoom` value is now set from the `Map` component
- added the `isMultipleMarkersMap` prop as `true` to the `Maps` component in `LocationOverview` because it is only used in POI maps
SVA-1095
`globalSettings: { settings: { "zoomLevelForMaps": { "multipleMarkers": 4, "singleMarker": 1 } } }`
|defect report|settings screen|POI map|
|--|--|--|
`globalSettings: { settings: { …

feat: adjust zoom value of maps

---

src/components/consul/selectors/ImageSelector.js
src/components/form/Input.tsx
src/components/screens/consul/Debates/NewDebate.js
src/components/screens/consul/Proposals/NewProposal.js
src/components/volunteer/VolunteerFormCalendar.tsx
src/config/consts.js
src/helpers/consul/dataErrorMessageGenerator.js
src/hooks/imagePicker.ts
src/screens/FeedbackScreen.js

- updated the `expo-image-picker` package while updating the expo sdd and refactored the required
fields that changed due to the update
- for more detailed information please read the document: https://docs.expo.dev/versions/v48.0.0/sdk/imagepicker/#imagepickerlaunchimagelibraryasyncoptions
- removed privatisation for consul to remove complexity in `ImageSelector`
- replaced the `image` `defaultValues` in `NewPropsal` with an empty array since the customisation for consul has been removed and the application can run again
- renamed the `isVolunteer` prop to `isMultiImages` as only volunteer can select multiple images
- added `errorType` prop to `ImageSelector` component because different features have different error messages
- added `errorTextGenerator` function for generating error …

fix: application crashing on the proposal creation screen for consul

---

src/components/MultiButtonWithSubQuery.tsx

- added navigation according to `params.paramsForMultiButtons` object to be able to navigate to different screens inside the application
- added new types for `paramsForMultiButtons` object to eliminate type error
- edited comment lines according to the new feature
SVA-1120
|`staticContent` where the property can be tested|`HtmlScreen` with multi button prepared with different navigation types|`WebScreen`|`IndexScreen` with `categories` query|`HtmlScreen` with button|
|--|--|--|--|--|

feat: add a multi-button feature for navigating screens in the app

---

src/config/consts.js

- changed the max screen width to from 428 to 504 to fit all phone sizes
-  https://yesviz.com/viewport/  biggest phone viewport width in this list: 504
- adjusted the buttons width to match with the bottom design on all devices
- fixed the TabBar look on iPhone 14 Pro Max and any other devices with a bigger viewport width than 428
| Before (iPhone 14 Pro Max) | After (iPhone 14 Pro Max) |
| ------------- | ------------- |
| ![Simulator Screenshot - iPhone 14 Pro Max - 2023-09-04 at 11 47 27](https://github.com/smart-village-solutions/smart-village-app-app/assets/105894697/6e0cb2d0-31bf-489c-a436-3c320b42034e) | ![Simulator Screenshot - iPhone 14 Pro Max - 2023-09-04 at 11 46 59](https://github.com/smart-village-solutions/smart-village-app-app/assets/105894697/91a72477-ea49-4572-9760-f2a47 …

refactor: adjust max screen with to fit all phone sizes

---

src/components/infoCard/InfoCard.tsx
src/helpers/linkHelper.js
src/helpers/shareHelper.js

- added `url` data returned from `mergeWebUrls` to be able to add links to share messages if there are any
- exported from `InfoCard` to use the `mergeWebUrls` helper
SBB-115
|share without link|share with one link|share with multiple link|
|--|--|--|

feat: add link to share feature

---

src/components/EmptyMessage.js
src/components/ImagesCarouselItem.js
src/components/IndexFilterElement.js
src/components/Wrapper.js
src/components/consul/detail/ConsulCommentList.js
src/components/consul/detail/ConsulVideo.js
src/components/consul/selectors/DocumentSelector.js
src/components/consul/selectors/ImageSelector.js
src/components/screens/consul/Debates/NewDebate.js
src/components/screens/consul/Proposals/NewProposal.js
src/navigation/DrawerNavigatorItem.js
src/navigation/DrawerNavigatorItems.js
src/screens/TilesScreen.js
src/screens/WasteCollectionScreen.js

- corrected order of code in files
- moved styles before prop types in files
- moved consts to the top instead of the bottom
- organized imports

refactor: unify structures

---

src/helpers/linkHelper.js

- added filtering on platform to exclude web urls for the foreign system
|before|after iOS|after Android|
|---|---|---|
|<img width="261" alt="image" src="https://github.com/smart-village-solutions/smart-village-app-app/assets/1942953/67013264-4c2c-4422-9ca2-c3c90d65d913">|<img width="229" alt="image" src="https://github.com/smart-village-solutions/smart-village-app-app/assets/1942953/f0110452-8da1-42a1-a5d8-9c665f91d67e">|<img width="193" alt="image" src="https://github.com/smart-village-solutions/smart-village-app-app/assets/1942953/8b4ab373-ea33-47e4-a8fb-de0fb7ddaf76">|
MQGB-57

feat(web urls): merge system dependent

---

src/components/Button.js
src/config/Icon.tsx

- changed `medium` prop to `small` and `small` prop to `smallest` and `extraLarge` to `big` since we decided
that `large` button will be the standard button
- added different size styles for icons to make them more understandable
- added `height` for standard button instead of `buttonStyle` style and added `buttonRadius` style for radius
- updated the icon prop as a component to be flexible with the icon
- updated the style for the button's title according to the changed size of the button to make it look better and fit the design
- added icon prop to button for icon that can be added to the left or right of the text on the button
- added `IconSetName` to `Icon.tsx` to make the icon type the same as the name of the icon library we use
- added icon sizes that can be changed according to …

feature: add different sizes and properties for button

---

src/components/ConnectedImagesCarousel.js
src/components/Disturber.tsx
src/components/HomeService.js
src/components/index.js
src/helpers/momentHelper.js
src/screens/HomeScreen.js
src/screens/LunchScreen.js

- added `Distruber` component to show distruber module on `HomeScreen`
- added `isActive` and `findClosesItem` helpers to show the active and latest distruber
- added `useStaticContent` hook to pull data from json content added to main server
- added a close button to ensure that the disturber is not shown and when the button is pressed, the disturber's ID is saved in the device's memory and a useEffect is added to ensure that it is not shown when the app is reopened until a new disturber is added
- added null and type checks to handle invalid or missing data gracefully
- used JavaScript's `reduce` and `map` methods for efficient computation
- utilized `Moment.js` for date manipulations
- added `containerStyle` prop to change the style of the button
- updated `PropTypes` to include the …

feat: new module disturber

---

src/components/HeaderLeft.tsx
src/components/IndexMapSwitch.js
src/components/VerticalList.js
src/components/Wrapper.js
src/components/index.js
src/components/map/LocationOverview.tsx
src/components/map/Map.tsx
src/helpers/parser/listItemParser.js
src/queries/pointsOfInterest.js
src/screens/IndexScreen.js
src/screens/consul/ConsulIndexScreen.js
src/types/Map.ts

this updates #898 and merges two branches for full screen map thus replacing #910
ℹ️ still missing: active colored marker on the map
MQGB-34

feat: full screen map in location overview

---

src/helpers/linkHelper.js

- added control to prevent the app from crashing if the data is undefined
MQGB-57

fix: add undefined control to url

---

src/components/Text.js
src/components/screens/PointOfInterest.js
src/components/screens/TimeTables.tsx
src/components/screens/index.js
src/config/texts.js
src/queries/pointsOfInterest.js
src/screens/DetailScreen.js

- enhanced the `TimeTables` component to display a list of departure times
- added `TimeTablesListItem` sub-component for detailed list items
- included a variety of route types (bus, tram, metro, etc.) in `texts.js`
- added `TimeTables` component to display departure times in `PointOfInterest.js`
- included new `TimeTables` section when `travelTimes` data is available
- created `TimeTables` component to show departure times
- extended `texts` in `text.js` to include new labels like 'Abfährtszeiten', 'Haltestelle', and 'Heute'
- introduced `HeadlineText` styled component for headlines, supporting `extraSmall` size option
- added `CategoryText` styled component for category labels, providing a `large` size option
- modified `GET_POINT_OF_INTEREST` GraphQL query to accept a `date` parameter …

feature: list departure times in detail screen

---

src/screens/IndexScreen.js

- added `initialFilter` control to `useLayoutEffect` to change the view according to the initial filter
MQGB-34
**initialFilter = "map"**
|service tab to `IndexScreen`|`CategoryList` to `IndexScreen`|`CategoryList` to `IndexScreen` (map view)|
|--|--|--|
|![Simulator Screenshot - iPhone 14 Pro Max - 2023-09-25 at 15 52 52](https://github.com/smart-village-solutions/smart-village-app-app/assets/11755668/e2feb511-f44e-4ad4-8f9e-bbaeebb12c27)|![Simulator Screenshot - iPhone 14 Pro Max - 2023-09-25 at 15 53 24](https://github.com/smart-village-solutions/smart-village-app-app/assets/11755668/5f9ed8cc-8821-4755-abe9-6c057f4907ba)|![Simulator Screenshot - iPhone 14 Pro Max - 2023-09-25 at 15 53 27](https://github.com/smart-village-solutions/smart-village-app-app/assets/11755668/43eb26bc-f5f8-42a0 …

feat: update the header according to the initial filter

---

src/components/volunteer/VolunteerFormCalendar.tsx

- added `filterGroupDropDownData` to `useEffect` to ensure dropdown data is refreshed
HDVT-93

fix(volunteer): the problem of not creating events

---

src/components/Disturber.tsx

- added new `showButtonToClose` value to `homeDisturber` `staticContent` to show or not show the button to close the disturber
SVA-1161

feat(disturber): hide the close button on the main server

---

src/components/augmentedReality/ARObjectListItem.js
src/components/augmentedReality/IconForDownloadType.js
src/components/augmentedReality/WhatIsARButton.js
src/screens/MapViewScreen.js

- updated the augmented reality preview in `MapViewScreen` with the new preview to get the same view as the newly updated preview view in the app
- updated the `title` text in `ARObjectListItem` with `BoldText`
- added `flexDirection` style for different ordering when using `ARObjectListItem` in `ARModal` or list view
- updated the color of the arrow used in augmented reality lists with `darkText` to match the structure of the app
|before|after|
|--|--|
|before|after|
|--|--|
|before|after|
|--|--|

refactor: set map preview and list view for augmented reality

---

src/components/volunteer/VolunteerEventRecord.tsx
src/components/volunteer/VolunteerGroup.tsx
src/components/volunteer/VolunteerUser.tsx
src/hooks/volunteer/header.tsx

- added `globalSettings` where necessary for `navigationType` since the navigation structure of the application is now set over the server
SVA-1130

fix: navigation type error for volunteer

---

src/components/defectReport/DefectReportCreateForm.tsx
src/components/screens/consul/Proposals/NewProposal.js
src/components/volunteer/VolunteerFormCalendar.tsx

- fixed an issue that caused the application to crash because the image and document selectors could not get the correct value due to updating the field in the `Controller` component of `react-hook-form`
HDVT-93

fix: issue with selectors causing the application to crash

---

src/helpers/shareHelper.js

- updated `urlSection` in `shareHelper.js` to add link to share news feature
SBB-115

feat: add a link to the share feature for news

---

package.json
src/components/EventList.js
src/hooks/listHooks.js
yarn.lock

- updated the `sectionData` function to create an array of the data type requested by `FlashList`, since `SectionList` and `FlashList` have different data structures
- added `SectionHeader` component to `listHooks` to render `SectionHeader` with `FlashList`
- added `stickyHeaderIndices` to make `FlashList`'s `SectionHeader` sticky
- removed the control added to prevent `SectionList` from crashing the application on android devices since this problem does not occur with `FlashList`
- deleted the `renderSectionHeader` prop that `SectionList` needs because it was added to `listHooks`
- added `queryVariables` to the options object of `listHooks` because `queryVariables` are required for navigation to `IndexScreen` when `SectionHeader` is clicked
- added `FlashList` to `package.json` to …

feature: change event list

---

package.json
src/components/SUE/index.ts
src/components/SUE/report/SueReportCategory.tsx
src/components/SUE/report/SueReportDescription.tsx
src/components/SUE/report/SueReportLocation.tsx
src/components/SUE/report/SueReportProgress.tsx
src/components/SUE/report/SueReportServices.tsx
src/components/SUE/report/SueReportUser.tsx
src/components/SUE/report/index.ts
src/components/consul/selectors/ImageSelector.js
src/components/settings/LocationSettings.js
src/config/consts.js
src/config/navigation/defaultStackConfig.tsx
src/config/texts.js
src/helpers/parser/sueParser.js
src/helpers/sueHelper.ts
src/queries/SUE/requests.tsx
src/screens/MapViewScreen.js
src/screens/SUE/SueDetailScreen.tsx
src/screens/SUE/SueMapScreen.tsx
src/screens/SUE/SueReportScreen.tsx
src/screens/SUE/index.ts
src/screens/index.js
src/types/Navigation.ts
yarn.lock

- created `SueReportScreen`
- updated the files required for navigation to the report screen
- connected to server for post request
- added progress bar to show the pagination of the report screen
- added category selection component required for reporting
- added component with inputs required to send report title and description
- added the component with the address inputs required to send the report address
- added component with personal information inputs required to send the information of the reporting person
SUE-7
- images upload ✔️ 
- select location from map ✔️ 
- progress bar shows progress ✔️ 
- disabling the pagination button if there is missing information
upgrade the version in `app.json` to 60.0.0
Change the `initialRouteName` of any tab in `tabConfig` to …

feat(sue): report a case

---

src/components/map/Map.tsx
src/screens/SUE/SueMapScreen.tsx
src/types/Map.ts

- implemented complex conditions to colorize map markers depending on given values and active state
- needed to `parseListItemsFromQuery` in `mapToMapMarkers` to have `iconName` and `status` set in the object to map further for necessary icon values
SUE-4

feat(sue): map marker depending on status

---

src/components/SUE/report/SueReportLocation.tsx
src/config/texts.js
src/screens/SUE/SueReportScreen.tsx

- renamed `homeNumber` to `houseNumber` as it is more common
- removed initial map marker when there is no address selected yet
SUE-7
https://github.com/smart-village-solutions/smart-village-app-app/assets/1942953/00aa1cb9-e07c-4cc8-8372-b4be06315203

feat(sue): reverse geocoding

---

src/components/SUE/report/SueReportDescription.tsx
src/components/SUE/report/SueReportLocation.tsx
src/components/SUE/report/SueReportUser.tsx
src/components/consul/selectors/ImageSelector.js
src/config/consts.js
src/config/texts.js
src/helpers/consul/dataErrorMessageGenerator.js
src/screens/SUE/SueReportScreen.tsx

- removed the * icon in inputs that are not required to be filled in when sending a report
- removed checks for non-required inputs when submitting the report
- added error message to warn the user if an image with a size higher than 10MB is selected
- removed the `errorMessage` prop from the hidden `Input` component in `ImageSelector` to prevent the error message from being repeated and appearing above the image selection button
- added `RegularText` component to `ImageSelector` to show error message
- added new error message text to `texts.js`
- added a new section for Sue to `dataErrorMessageGenerator.js` to check if the selected image is larger than 10MB and generate an error message
- added controls to `SueReportScreen` to check each step on the report screen and prevent the user …

feat(sue): improve report form

---

src/components/CardListItem.js
src/components/map/LocationOverview.tsx
src/components/map/Map.tsx

- we introduced `overtitle` already with MeinQuartier so we should use it for SUE as well

feat: adjustments for map and card list

---

src/components/CardListItem.js
src/components/Image.js
src/components/TextListItem.tsx
src/hooks/listHooks.js

- added a control to `listHooks` to fix the problem of the first item's image not appearing in the `EventList` in text list type with large images
- fixed styles array format in `CardListItem`
- added `style` prop to `RNEImage` component to apply the style of the image more correctly
- updated the extra style of images in `TextListItem` created `withCard` prop and accepted as standard
SVA-1248
|before - list with large images|after - list with large images|before- list without large images|after - list without large images|
|--|--|--|--|
|before - event list|after - event list|before - text with small images|after - text with small images|
|--|--|--|--|

fix: the errors of the lists

---

src/components/SUE/report/SueReportServices.tsx

- added refetch for services when the report screen is opened in order to show any changes made on the server actively in the application
- added `LoadingSpinner` to show data during loading
SUE-30

feat: update categories when report screen opens

---

src/queries/index.js
src/queries/types.ts
src/queries/vouchers.js

- added queries to get the voucher information from the server
SVAK-35

feat: add voucher queries

---

src/config/navigation/defaultStackConfig.tsx
src/config/texts.js
src/queries/index.js
src/queries/types.ts
src/queries/vouchers.js
src/screens/Voucher/VoucherHome.tsx
src/screens/Voucher/index.ts
src/screens/index.js
src/types/Navigation.ts

- added `VoucherHome` screen to the navigation for the home screen of the voucher module
- added `Image` component to display at the top of `VoucherHome`
- added html section that can be updated via main server
- added `ServiceTiles` component that should be present in `VoucherHome` with `voucherHome` static name
SVAK-35
|service tab|`VoucherHome` screen|
|--|--|

feat: add voucher home screen

---

src/components/ListComponent.js
src/components/index.js
src/components/vouchers/Discount.tsx
src/components/vouchers/VoucherList.tsx
src/components/vouchers/VoucherListItem.tsx
src/components/vouchers/VouchersList.tsx
src/components/vouchers/index.ts
src/components/widgets/VoucherWidget.tsx
src/config/consts.js
src/config/navigation/defaultStackConfig.tsx
src/config/texts.js
src/helpers/parser/listItemParser.js
src/hooks/listHooks.js
src/queries/vouchers.js
src/screens/BookmarkScreen.js
src/screens/Voucher/VoucherHomeScreen.tsx
src/screens/Voucher/VoucherIndexScreen.tsx
src/screens/Voucher/index.ts
src/types/Navigation.ts
src/types/index.ts
src/types/voucher/index.ts
src/types/voucher/voucher.ts

- added `VoucherIndexScreen` for listing vouchers
- updated `VoucherHome` to `VoucherHomeScreen` to keep the code in the same format
- added a new `VoucherList` to show the section header of the voucher list by categories
- added `VoucherList` to `ListComponent`
- added `parseVouchers` to `listItemParser` so that voucher items can be formatted as needed
- added `Discount` component to show discount information in voucher list
- added the ability to add vouchers to favourites in the `Discount` component
- added `Vouchers` to `BorkmarkScreen` to show vouchers on favourites screen
- added `VoucherListItem` option to `listHooks` to show in voucher list
- added `VoucherCategoryHeader` to create section header according to categories
- updated the redirect screen when clicking on …

feat: add voucher index

---

package.json
src/components/Checkbox.js
src/components/vouchers/VoucherRedeem.tsx
src/components/vouchers/index.ts
src/config/navigation/defaultStackConfig.tsx
src/config/texts.js
src/helpers/parser/listItemParser.js
src/screens/Voucher/VoucherDetailScreen.tsx
src/screens/Voucher/index.ts
src/types/Navigation.ts
src/types/voucher/voucher.ts
yarn.lock

- added `VoucherDetailScreen` to show the details of the voucher
- added redirect to `VoucherDetail` in `listItemParser`
- added information to `VoucherDetailScreen` to show how many vouchers are left and with which frequency they can be used
- added `contentBlocks` information to `VoucherDetailScreen` to show information about the voucher
- added `VoucherRedeem` component to enable users to redeem the voucher
- set defaultTime to 15 minutes as standard
- added `react-native-circular-progress-indicator` package to show timer counter
- added react-native's `Modal` component to show the bottom sheet
- added `lightest` prop to make the title in the checkbox white because the background color of the voucher bottom sheet is `primary`
SVAK-35
|VoucherDetailScreen|voucher redeem bottom sheet …

feat: add voucher detail

---

src/config/navigation/defaultStackConfig.tsx
src/config/texts.js
src/helpers/voucherHelper.ts
src/hooks/index.js
src/hooks/voucherHooks.ts
src/queries/vouchers.ts
src/screens/Voucher/VoucherHomeScreen.tsx
src/screens/Voucher/VoucherLoginScreen.tsx
src/screens/Voucher/index.ts
src/types/Navigation.ts
src/types/voucher/index.ts
src/types/voucher/login.ts

- added components and screens for login of voucher module, which is based on existing ones like volunteer
SVAK-41
|home with login button|login form|login form error|home without login button after login success|
|---|---|---|---|
|![Simulator Screen Shot - iPhone SE (3rd generation) - 2024-01-09 at 16 09 25](https://github.com/smart-village-solutions/smart-village-app-app/assets/1942953/e88896cc-1612-4204-8c3f-95c6f1dc96af)|![Simulator Screen Shot - iPhone SE (3rd generation) - 2024-01-09 at 16 20 22](https://github.com/smart-village-solutions/smart-village-app-app/assets/1942953/6d806cc1-c1de-4e06-96fd-7646f94d8836)|![Simulator Screen Shot - iPhone SE (3rd generation) - 2024-01-09 at 16 20 31](https://github.com/smart-village-solutions/smart-village-app-app/assets/1942953/eabcec4b-7864- …

feat: voucher login

---

src/components/vouchers/VoucherList.tsx
src/components/vouchers/VoucherRedeem.tsx
src/config/texts.js
src/helpers/parser/listItemParser.js
src/queries/vouchers.ts
src/screens/Voucher/VoucherDetailScreen.tsx
src/screens/Voucher/VoucherHomeScreen.tsx
src/screens/Voucher/VoucherIndexScreen.tsx

- added `redeemQuotaOfVoucher` mutation to redeem the voucher
- added controls whether the user is logged in or not
- added login section to `ListHeaderComponent` prop in `VoucherIndexScreen` according to `isLoggedIn` status
SVAK-42
|index - vouchers|index - vouchersCategories|detail|
|--|--|--|

feat: redeem voucher

---

src/config/texts.js
src/hooks/staticContent.ts
src/screens/Voucher/VoucherLoginScreen.tsx

feat: add static content text for login screen

---

src/components/DropdownHeader.js
src/screens/Voucher/VoucherIndexScreen.tsx
src/types/voucher/voucher.ts

- added dropdown filter to `VoucherIndexScreen`
- added `vouchersCategories` query to `VoucherIndexScreen` to show categories in dropdown
- added `updateListDataByDropdown` function to refresh the list according to the category selected in the dropdown menu
SVAK-35
|index screen|index screen|categorised index screen|
|--|--|--|

feat: add dropdown filter to vouchers index

---

src/screens/BookmarkScreen.js

- added query filter to list favourites according to query
SVAK-35
|bookmark screen with vouchers only|bookmark screen|
|--|--|

feat: add filter to bookmark for vouchers

---

src/components/widgets/VoucherWidget.tsx

- updated query to show count in widget
SVAK-35

fix: the problem of not showing the count of vouchers widget

---

src/components/vouchers/VoucherRedeem.tsx
src/helpers/voucherHelper.ts
src/queries/vouchers.ts
src/screens/Voucher/VoucherLoginScreen.tsx

- added member id to async storage for using it in several places
SVAK-42

feat: add transactions to storage for redeeming vouchers

---

src/screens/SUE/SueReportScreen.tsx

- added all data in place with `setValue` using a `map` from the stored data to the array instead of running the `setValue` function one by one to avoid code clutter
SUE-28

refactor: return the object to an array and use the `setValue` function

---

src/components/SUE/report/SueReportLocation.tsx
src/screens/SUE/SueReportScreen.tsx

feat(sue): location fields not required

---

src/components/Logo.js

SVA-1294
|before|after|
|--|--|

fix: prop error of `Image` component in `Logo` component

---

src/screens/SUE/SueListScreen.tsx

- added `servicesFilterData` to get services information from server and add it to filter dropdown
- updated the data of `servicesData` in `servicesFilterData` to fit the data coming from the server to the data type requested by the dropdown
SUE-14
|filter with services data|filter with services data|filtered list with `Wilder Müll` service|
|--|--|--|

feat: get the service data from server to filter it

---

src/components/DefaultKeyboardAvoidingView.tsx
src/components/SUE/report/SueReportDescription.tsx
src/components/SUE/report/SueReportLocation.tsx
src/components/SUE/report/SueReportUser.tsx
src/components/form/Input.tsx

- updated the `behavior` value in `DefaultKeyboardAvoidingView` to `height` for android to have the same experience on iOS and Android
- wrapped the `Input` component with `forwardRef` since the reference value generated with `useRef` cannot be sent to the `Input` with prop
- https://react.dev/reference/react/forwardRef
- added `ref` and `onSubmitEditing` props to automatically focus on the next input after pressing the done or submit button from the keyboard after writing to any input on the report screen
SUE-58
https://github.com/smart-village-solutions/smart-village-app-app/assets/11755668/bd3db55d-a96b-4a9a-923e-bdd2f11fa1c2

feat: improve inputs on the report screen

---

src/components/SUE/SueStatus.tsx
src/components/Search.tsx
src/components/filter/Filter.tsx
src/components/filter/Sue/StatusFilter.tsx

- added the `isFilter` prop to the `SueStatus` component since the status component has a special design for the filter and updated the style according to the `isFilter` prop
- added `invert` prop to the reset filters button in the filter component to avoid confusion for users
- updated size of search bar
SUE-14
|search bar & status filters|inverted button & selected status filter|
|--|--|

refactor: update the design of filters

---

src/screens/SUE/SueReportScreen.tsx

- added automatic scrolling to `ScrollView` to save the user the effort of scrolling the screen to confirm the terms of service
SUE-56
https://github.com/smart-village-solutions/smart-village-app-app/assets/11755668/3a491807-46b3-4210-b091-3bac41b8dfc1

feat: scroll screen to terms of service

---

src/components/CardListItem.js
src/components/Search.tsx
src/components/VerticalList.js
src/components/filter/DateFilter.tsx
src/components/filter/Filter.tsx
src/config/texts.js
src/screens/SUE/SueListScreen.tsx

- updated the `containerStyle` of the `DateFilter` in the `Filter` component due to the date filter not showing properly on devices with small screens
- updated `setDate` in `DateFilter` to automatically close the calendar when the date is selected in the filter
- added `clearButtonMode` to `Search.tsx` to show the clear button when a text is started to be written in the search input
- added `ListEmptyComponent` to `ListComponent` in `SueListScreen` to inform the user when there is no data to be shown in the list
- added text to `ListComponent` to show the user how many items are listed in the list
SUE-14
|iPhone 15 Pro Max|iPhone 15|iPhone SE|
|--|--|--|
|empty messages|input with Clear button|
|--|--|

feat: improve the filter feature

---

src/screens/SUE/SueListScreen.tsx
src/screens/SUE/SueMapScreen.tsx

- updated `initial_start_date` to 1900 to list reports before 2020
SUE-53

feat: list reports before 2020

---

src/components/SUE/report/SueReportLocation.tsx
src/components/SUE/report/SueReportUser.tsx
src/config/texts.js
src/queries/SUE/requests.tsx
src/screens/SUE/SueReportScreen.tsx

- updated `mutateAsync` structure to `onError` and `onSuccess` to better analyse error reports from api
- added `status` check to `onSuccess` section because most of the errors in api are not displayed in `onError` section
- added the `termsOfService` control we created inside `onSubmit` to the `alertTextGeneratorForMissingData` function to make the code more understandable
- added control of values in `postRequests` to not send unfilled content in the form to api
SUE-63

fix: add error check to fix the problem that the report is not sent to api

---

package.json
src/components/SUE/report/SueReportUser.tsx
src/config/consts.js
src/config/texts.js
src/screens/SUE/SueReportScreen.tsx
yarn.lock

- added `libphonenumber-js` package to generate phone numbers in accordance with DIN-5008 standards to meet the requirements of the API
- added `parsePhoneNumber` to bring the phone number into a format that conforms to DIN-5008 standards in order to adhere to the requirements of the API
- added `rules` to input in `SueReportUser` to check if a valid phone number is entered in the input
- added `PHONE_REGEX` to check if the phone number is valid
SUE-71
DIN-5008 Doc.: https://www.din-5008-richtlinien.de
examples of different telephone numbers formatted in an automatic way.
||||
|--|--|--|
||||
|--|--|--|

feat: add phone number check

---

src/config/consts.js

- integrated the control regex used on the server side into the app to test an error in the phone number input
SUE-71

feat: change phone number regex

---

src/components/Search.tsx

- added `Keboard.dismiss` to `onSearch` function to dismiss the keyboard when the search button is pressed while in list view
- added `onSumbitEditing` to enable automatic search when you click the enter button on the keyboard
SUE-83

feat: add keyboard switch off when the search button is pressed

---

package.json
src/components/map/Map.tsx
src/screens/SUE/SueMapScreen.tsx
yarn.lock

- added `react-native-map-clustering` package to add clustering to map view
- added `MapView` component imported from `react-native-map-clustering` package instead of `react-native-maps` to add clustering feature to map view
- added `clusteringEnabled` prop to add clustering to map view
- added `renderCluster` function to customise the clustering design
SUE-22
|before|after|
|--|--|

feat: add clustering for map view

---

src/helpers/parser/listItemParser.js
src/queries/vouchers.ts

feat: add subtitle for list view

---

src/components/vouchers/VoucherListItem.tsx
src/helpers/parser/listItemParser.js
src/queries/vouchers.ts
src/screens/Voucher/VoucherDetailScreen.tsx

- added title and subtitle to show on detail screen
- deleted `subtitle` in `listItemParser` because `teaser` value in query was updated as `subtitle`
- added limitation with `numberOfLines` to title and subtitle in list view
SVAK-35
|list view|detail screen|
|--|--|

feat: add title and subtitle to detail screen

---

src/components/BB-BUS/IndexFilter.js

- added `undefined` control to `IndexFilter` to prevent the app from crashing in case the requested data is not received from the server or an error occurs

fix: application crashes in case of server-induced busbb errors

---

src/components/vouchers/VoucherListItem.tsx
src/helpers/parser/listItemParser.js
src/queries/vouchers.ts
src/screens/Voucher/VoucherDetailScreen.tsx
src/types/voucher/voucher.ts

- added `mediaContents` to query to get voucher's image data from server
- added picture to `voucherParser` in `listItemParser` to convert picture to desired format
- added picture value instead of default picture to show picture content in list and detail screens
SVAK-35
Since no current voucher has image data, the following method can be used to add an image and test it.
Update the picture object in the `parseVoucher` function in `listItemParser.js` as follows. This data is the `mediaContents` data from the server.
```
picture: {
url: mainImageOfMediaContents([
{
id: '505266',
contentType: 'image',
captionText: '',
copyright: '',
sourceUrl: {
id: '1063261',
url: 'https://fileserver.smart-village.app/nrw-detmold/cms_uploads/6.7-33c4442566ceabaa2ecc5c76bd35f529.png'
}
}
])
},
```
This way …

feat: add image to detail screen and list screen

---

src/components/vouchers/VoucherRedeem.tsx
src/config/texts.js
src/queries/vouchers.ts

- updated the queries according to the type variables made on the server
- added checking how many vouchers a user can use based on `availableQuantityForMember` instead of `maxPerPerson`
- added availability checks of the voucher according to the response from the server
- updated button's title according to availability
SVAK-35
|redeemable voucher|redeemed voucher|unavailable voucher|
|--|--|--|

feat: add availability for voucher

---

src/queries/pointsOfInterest.js
src/queries/vouchers.ts
src/screens/DetailScreen.js
src/screens/Voucher/VoucherHomeScreen.tsx
src/screens/Voucher/VoucherIndexScreen.tsx

- added `mediaContents` to `pointsOfInterest` query to display images in voucher list in `DetailScreen`
- added `mediaContents` to `vouchers` query to display images in redeemed vouchers list
- added a condition to show the login button to the user if the memberId does not exist in order to prevent memberId = null error that may occur due to the cache being reset
- added condition to prevent `undefined` error because there are no categories in the data in the voucher category list
- updated the condition in `queryVariables` to solve the problem of detail screen not loading
SVAK-35

fix(voucher): general bug fix

---

src/components/map/LocationOverview.tsx

- added undefined check because each category does not have an iconName, this value becomes null and causes the app to crash
SVAK-74

fix: app crashes in map view

---

src/helpers/parser/listItemParser.js

SVAK-76
|before|after|
|--|--|

feat(voucher): sort categories alphabetically

---

src/screens/Voucher/VoucherHomeScreen.tsx
src/screens/Voucher/VoucherLoginScreen.tsx

- added as `headerImage` param because `headerImage` param is missing when redirecting to `VoucherHomeScreen`
SVAK-41

fix(voucher): header image not showing after login

---

src/components/Image.js

- added new control to fix the problem of images not appearing through cache only in development mode and on android platform
SVA-1317
|before|after|
|--|--|

fix: pictures not showing up problem for android

---

src/components/vouchers/VoucherListItem.tsx
src/screens/Voucher/VoucherDetailScreen.tsx

- added design deficiencies and changes recognised
SVAK-35
|--|--|--|--|

feat: update styles

---

src/config/texts.js
src/queries/vouchers.ts
src/screens/Voucher/VoucherDetailScreen.tsx

- added new fields to `GET_VOUCHER` query to add provider information to detail screen
- updated the props of the `OperationCompany` component in `VoucherDetailScreen` to show provider information on the detail screen
- added `Button` component to `VoucherDetailScreen` to redirect to POI detail screen
SVAK-86
|before|after|
|--|--|

feat: add provider section to detail screen

---

src/helpers/augmentedReality/deleteObject.js
src/helpers/storageHelper.js
src/helpers/voucherHelper.ts
src/hooks/voucherHooks.ts

- removed the check in `useEffect` to fix the issue where the `isLoggedIn` value was `false` because the `logInCallback` function was not executed again when the connection was lost, even though the user's token was registered on the device and logged in
- updated `addToStore` with `AsyncStorage.removeItem` to fix `memberId` not being deleted in `voucherHelper`
SVAK-90

feat: use vouchers in offline mode

---

src/config/texts.js
src/helpers/dateTimeHelper.ts
src/screens/Voucher/VoucherDetailScreen.tsx

- added `dateOfAvailabilityText` function to show the coupon's availability time on the detail screen
- added checks inside the `dateOfAvailabilityText` function because different situations can occur
- added coupon validity check according to `availableQuantity` value and updated text colors
SVAK-88
|vouchers list|availability from| availability to| availability with endDate|
|--|--|--|--|

feat: add the availability date to the detail screen

---

src/config/texts.js
src/helpers/parser/listItemParser.js

- updated header to prevent title duplication on the voucher detail screen
SVAK-83

chore: update title

---

src/components/screens/ServiceTiles.js

- added `useStaticContent` to `ServiceTiles.js` to get htmlContent from server
- added the `htmlContent.forAbove` content as content with the `html` prop in `ServiceTiles` and merged them in the `contentForAbove` constant and turned them into a single html content
- added `contentForBelow` html to be shown at the bottom of `ServiceTiles`
- added the name in `useStaticContent` to `'${staticJsonName}Content'` so that this feature works on all staticContent screens
SVAK-85
To use this feature, create a JSON on the main-server with the same staticContent name but with 'Content' appended to the end.
For example: 
staticContent = "homeService"
for staticContent html = "homeServiceContent"
Make sure that `homeServiceContent` is in JSON format.
The content of `homeServiceContent` can be as …

feat: add html content above and below tile screen

---

src/components/vouchers/VoucherListItem.tsx

- replaced the `Touchable` component with the `TouchableOpacity` component to fix the problem of the app crashing because there are multiple components inside the `Touchable` component that are not inside the same fragment
SVAK-35

fix: android version crashing in voucher list

---

src/components/vouchers/Discount.tsx
src/components/vouchers/VoucherRedeem.tsx
src/helpers/voucherHelper.ts
src/queries/pointsOfInterest.js
src/screens/Voucher/VoucherIndexScreen.tsx

- added `memberId` condition to `isButtonDisabled` to fix the problem of the user being able to use the coupon due to `isLoggedIn` being `true` in the absence of `memberId`
- updated `removeItem` in the `voucherMemberLoginInfo` helper function in `voucherHelper` with the new `removeFromStore` created in `storageHelper`
- added `subtitle` value to `pointOfInterest` query to fix the error of subtitle not appearing in the voucher list shown in poi `DetailScreen`
- added missing `imageUri` param when redirecting to `VoucherHomeScreen` after user login on `VoucherLogin` screen redirected via login button on voucher list
- added `toLocaleString` to set the currency to be shown with `,` instead of `.`
- added `await` statement to `redeemQuotaOfVoucher` mutation in `VoucherRedeem` to fix the …

fix: minor bug fixed

---

src/components/SUE/report/SueReportLocation.tsx
src/components/map/Map.tsx
src/screens/MapViewScreen.js
src/screens/SUE/SueDetailScreen.tsx

- wrapped the `Map` component in `SueReportLocation` with `WrapperHorizontal` so that the active location button and the fullscreen map view button have the same style
- added `isMaximiseButtonVisible` and `onMaximiseButtonPress` props to `Map` component to show the button to switch to full screen map view
- added `isAugmentedReality` control because `MapViewScreen` cannot find `modelId` and gives error
SUE-80
|report screen|report map full screen|detail screen|detail map full screen|
|--|--|--|--|

feat: add switch button to full screen map view

---

src/components/SUE/report/SueReportLocation.tsx
src/components/map/Map.tsx

- added the `Callout` component of the `react-native-maps` package to add title on the pins in the report screen
- added `calloutTextEnabled` prop to enable the `Callout` feature on the pin
- added condition to `onMapPress` prop in `sueReportLocation` to ensure that the location is not selected after clicking the pin on the map
SUE-75
|before|after|
|--|--|

feat: add title on pins

---

src/components/Image.js

- changed the `apiKey` value from `sueConfig` in `ConfigurationsContext` to fix the problem of images not appearing
SUE-22

fix(sue): the problem of images not loading

---

src/components/map/Map.tsx
src/helpers/textHelper.js
src/types/Map.ts

- added category to the pop'up text that opens when clicking on the pins on the map on the report screen
- added `truncateText` helper to shorten long texts on the pins
SUE-75
|before|after|long text test|
|--|--|--|

feat(sue): update the text on the pins on the report screen

---

src/components/SUE/report/SueReportSend.tsx
src/config/appDesignSystem/default.ts
src/config/sue/default.ts

feat(sue): add `sueReportScreen` config to `sueConfig`

---

src/screens/SUE/SueMapScreen.tsx

- added button to show current location in full screen map view 
SUE-44

feat(sue): add current location to full screen map view

---

src/components/SUE/report/SueReportDescription.tsx
src/components/SUE/report/SueReportLocation.tsx
src/components/SUE/report/SueReportUser.tsx
src/config/consts.js
src/hooks/reverseGeocode.ts
src/screens/SUE/SueReportScreen.tsx

- added `INPUT_KEYS` constant to update the input keys used in many different parts of the code in one place
SUE-57

feat(sue): update sue input keys

---

src/components/SUE/report/SueReportDescription.tsx
src/components/SUE/report/SueReportLocation.tsx
src/components/SUE/report/SueReportUser.tsx
src/config/consts.js
src/hooks/reverseGeocode.ts
src/screens/SUE/SueReportScreen.tsx

- added required information of address inputs to `requiredInputs` according to `locationStreetIsRequired` and `locationIsRequired` values
SUE-57
||||
|--|--|--|

feat(sue): set address inputs according to `geoMap` config

---

src/components/SUE/report/SueReportDescription.tsx
src/components/SUE/report/SueReportLocation.tsx
src/components/SUE/report/SueReportServices.tsx
src/components/SUE/report/SueReportUser.tsx
src/config/consts.js
src/config/texts.js
src/hooks/reverseGeocode.ts
src/screens/SUE/SueReportScreen.tsx

- updated the keys used in the app to update the inputs with configApi
- `firstName` -> `name`
- `lastName` -> `familyName`
- `zipCode` -> `postalCode`
- updated types to simplify the code
SUE-97

feat(sue): update keys according to config api

---

src/components/Button.js
src/config/normalize.js

- added `Dimension` to adjust to the dimensions of the device
- integrated the function used in the `react-native-size-metters` package
SVA-1351

chore: update normalize function

---

src/components/SUE/report/SueReportDescription.tsx
src/components/consul/selectors/ImageSelector.js
src/screens/SUE/SueReportScreen.tsx

- added controls to the `onDeleteImage` function to delete the information shown in the address step when an image with coordinate information is deleted
- added `showCoordinatesFromImageAlert` control to not show the received coordinates from image alert every time
- added `from` prop to `imageSelect` to be able to know through which function the image was selected
- added location data from the `exif` to the `location` object if the image contains coordinate information
- added the device's location information to the `location` object since there is no coordinate information in the exif when the image is taken from the camera
- added control to skip the location check if the coordinate information is not correctly contained in the location object
- updated `onPress` functions to …

feat(sue): improve the ability to get coordinate information from a photo

---

src/components/SUE/report/SueReportDescription.tsx
src/components/SUE/report/SueReportLocation.tsx
src/components/SUE/report/SueReportUser.tsx
src/components/consul/selectors/ImageSelector.js
src/config/texts.js
src/hooks/reverseGeocode.ts
src/screens/SUE/SueListScreen.tsx
src/screens/SUE/SueMapViewScreen.tsx
src/screens/SUE/SueReportScreen.tsx

- added space before the `*` icon of the labels so that all inputs look the same
- updated `setShowCoordinatesFromImageAlert` to `false` in `imageSelector` to show the alert when the image is selected again after returning to the description step
- updated all letters to lowercase due to case sensitivity during search
- added alert for location question to big map view on report screen
- removed the extra contact check in `SueReportScreen` because we check in `missingAnyInput` and show alert
SUE-76

feat(sue): bug fixes and improvements

---

src/ConfigurationsProvider.tsx
src/components/ImagesCarousel.js
src/components/SUE/report/SueReportDescription.tsx
src/components/SUE/report/SueReportServices.tsx
src/screens/SUE/SueReportScreen.tsx

- updated components with `useMemo` hook to avoid performance problem and reduce re-render issue
- stopped the `Carousel` component according to the isFocused hook because it was constantly running in the background, causing unnecessary re-rendering and badly affecting performance
SUE-76

feat(sue): improve performance problems

---

src/components/CardListItem.js
src/components/ImageMessage.js
src/components/SUE/report/SueReportSend.tsx
src/components/SUE/report/SueReportUser.tsx
src/config/sue/default.ts
src/config/texts.js
src/hooks/openWebScreen.ts
src/screens/SUE/SueReportScreen.tsx

- add space around both sides of header to be able to place a background color accordingly
- added check for navigation param in each step to disable touchable if false
SUE-106

fix(sue): adjust header text container and steps click

---

src/components/SUE/report/SueReportLocation.tsx
src/screens/SUE/SueMapViewScreen.tsx
src/screens/SUE/SueReportScreen.tsx

We do not need them anymore, right? Or did I miss something?
SUE-76

fix(sue): remove throwing errors where not needed

---

src/config/sue/default.ts
src/helpers/sueHelper.ts
src/queries/SUE/requests.tsx
src/screens/SUE/SueReportScreen.tsx

- removed `jurisdictionId` value from requests as it is not used in version 3.0 of api
- removed the mapping feature for input keys to be in the desired format after the update in config api
SUE-113

feat(sue): adjust according to api update

---

src/components/screens/PointOfInterest.js

- added `showOpeningTimes` filter to main-server to show open times on detail screen
SVA-1395

feat: add filter for opening times on detail screen

---

App.js

- update font loading using `useFonts` as in the expo documentation
- https://docs.expo.dev/develop/user-interface/fonts/#with-usefonts-hook
SVA-1400

refactor: update the font loading as in the document

---

src/components/consul/selectors/ImageSelector.js
src/queries/SUE/requests.tsx

- added `selectedPosition` control to `ImageSelector` to fix the problem of not being able to delete images
- added separate control to the data inside the object to fix the problem of not being able to send a report due to one of the data inside the data object being `undefined`
SUE-113

fix(sue): report not sending error

---

src/components/BB-BUS/IndexFilter.js
src/components/BB-BUS/ServiceList.js
src/components/Button.js
src/components/CardListItem.js
src/components/CategoryList.js
src/components/CategoryListItem.js
src/components/Checkbox.js
src/components/ConnectedImagesCarousel.js
src/components/DiagonalGradient.js
src/components/EmptyMessage.js
src/components/HtmlView.js
src/components/Image.js
src/components/Logo.js
src/components/Modal.js
src/components/Radiobutton.js
src/components/TextListItem.tsx
src/components/VerticalList.js
src/components/form/PickerInput.js
src/navigation/DrawerNavigatorItems.js

fix: default prop error

---

src/components/CardListItem.js
src/components/wasteCalendar/WasteReminderSettings.tsx
src/screens/AppIntroScreen.tsx

fix: key error & key extractor error

---

src/hooks/staticContent.ts

fix: delete warnings in the code

---

src/components/CardListItem.js
src/components/screens/DraggableGrid.tsx
src/components/screens/Service.tsx
src/hooks/listHooks.js

- added a general `keyExtractor` to eliminate the key warning in `CardListItem`
- added `draggableKey` prop to remove key warning on personalized tiles
SVA-1429

feat: remove key warnings

---

package.json
src/SettingsProvider.js
src/components/index.js
src/components/whistleblow/WhistleblowReportForm.tsx
src/components/whistleblow/index.ts
src/config/Icon.tsx
src/config/navigation/defaultStackConfig.tsx
src/config/texts.js
src/helpers/index.js
src/helpers/whistleblow/globaleaks/index.ts
src/helpers/whistleblow/globaleaks/proofOfWork.ts
src/helpers/whistleblow/index.ts
src/index.js
src/queries/index.js
src/queries/whistleblow/auth.ts
src/queries/whistleblow/index.ts
src/queries/whistleblow/whistleblower.ts
src/screens/NestedInfoScreen.tsx
src/screens/index.js
src/screens/whistleblow/WhistleblowFormScreen.tsx
src/screens/whistleblow/index.ts
src/types/Navigation.ts
src/types/SubQuery.ts
src/types/index.ts
src/types/whistleblow/globaleaks/index.ts
src/types/whistleblow/globaleaks/submission.ts
src/types/whistleblow/index.ts
yarn.lock

- implemented Globaleaks API flow including Proof of Work logics for submitting reports with a three input form and the possibility to copy the receipt code after successful submission
- included `expo-crypto` package for Proof of Work digest function
- included `expo-clipboard` for copying the receipt code
- created `initialContext` object to be reused for setting the `initialGlobalSettings` on app start
SBB-134
|||
|---|---|
|![Simulator Screen Shot - iPhone 12 - 2024-02-23 at 11 23 54](https://github.com/smart-village-solutions/smart-village-app-app/assets/1942953/f99575d4-4589-47d6-8e8d-1a02737f4e89)|![Simulator Screen Shot - iPhone 12 - 2024-02-23 at 12 33 55](https://github.com/smart-village-solutions/smart-village-app-app/assets/1942953/796c08a2-9821-4b2b-85a4-29473cd6638d)|

feat(whistleblow): integration of globaleaks

---

src/config/texts.js
src/screens/FeedbackScreen.js

feat(feedback): add text info for required fields

---

src/helpers/parser/sueParser.js
src/helpers/sueHelper.ts
src/queries/SUE/index.ts
src/queries/SUE/location.tsx
src/queries/index.js
src/queries/types.ts
src/screens/SUE/SueListScreen.tsx
src/screens/SUE/SueMapScreen.tsx

- integrated `locations` endpoint to reduce long loading time in map view
- added `useInfiniteQuery` for pagination instead of `useQuery`
- added `limit` and `offset` values to query to use pagination
- updated `SORT_BY` options according to server requirements
- removed codes to sort listItem locally since there are sorting options on the server
- added `cacheTime` until end of day
- deleted `RegularText` added for pagination test
- reduced unnecessary codes
SUE-144

feat(sue): reduce loading time

---

src/components/screens/Overviews.js

Enabling and disabling the location services had no effect for the distance sorting. This is cleaned up now.

fix(overviews): improve location-based sorting logic and clean up redundant code

---

app.json
src/components/Chat.js
src/components/DefaultKeyboardAvoidingView.tsx
src/navigation/MainTabNavigator.tsx

solving the problem that the inputs are behind the keyboard and the inputs are not visible
|sue report screen|volunteer chat screen|
|--|--|

fix: keyboard issues

---

src/components/SUE/report/SueReportLocation.tsx
src/screens/SUE/SueMapViewScreen.tsx

|small map view|big map view|
|--|--|
SUE-154

feat(sue): add clustering for report map view

---

src/components/screens/Overviews.js

- updated `sortByDistance` logic to consider `locationService` settings, so that it can be turned off per global settings
SVAK-148

feat: enhance location-based sorting functionality

---

src/screens/OParl/OParlOrganisationsScreen.tsx
src/screens/OParl/OParlPersonsScreen.tsx
src/screens/OParl/OParlSearchScreen.tsx

conditional rendering of `dropdownData?.length <= 2` did the trick
SVASD-65

fix(oparl): organisation dropdown select

---

src/components/CategoryList.js
src/components/CategoryListItem.js
src/components/screens/Overviews.js
src/helpers/parser/listItemParser.js
src/queries/categories.js

- this PR improves and corrects rendering of category lists, especially for categories that has pois as well as tours
SVASD-77

refactor(category): enhance category parsing and rendering

---

src/helpers/textHelper.js
src/screens/SUE/SueReportScreen.tsx
src/screens/SettingsScreen.js

- added `alertText` to reduce returns in `alertTextGeneratorForMissingData` function
SVA-1557

fix(sue): reduce returns on sue report screen

---

src/config/navigation/defaultStackConfig.tsx
src/config/texts.js
src/screens/SUE/SueHomeScreen.tsx
src/screens/SUE/SueListScreen.tsx
src/screens/SUE/index.ts
src/types/Navigation.ts

added `SueHomeScreen` to use Sue as a module and added button to switch between list view and map view
the following updates to the main-server are required to use Sue as a module!
- `sueHomeCarousel` needs to be created specifically for sue like `homeCarousel`
- add the following section to `globalSettings` for the customized aspectRatio for `sueHomeCarousel`
```
"sueHomeCarousel": {
"imageAspectRatio": "393:295"
},
...
```
- for the content list to appear
```
"sections": {
"staticContentList": {
"horizontal": true,
"showStaticContentList": true,
"staticContentListTitle": "Mach Meldung in drei Schritten",
"staticContentListDescription": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.",
"staticContentName": "homeList"
},
...
```
- to make the …

feature(sue): add `SueHomeScreen`

---

src/components/waste/WasteCollectionSettings.tsx
src/components/waste/WasteHeader.tsx
src/components/waste/WasteInputForm.tsx
src/config/texts.js
src/screens/WasteCollectionScreen.js

- added localization support for various texts in WasteHeader, WasteCollectionScreen, and WasteInputForm
- integrated wasteAddresses texts from global settings for dynamic text rendering
GOS-118

feat(waste): enhance text localization in waste components

---

src/components/waste/WasteInputForm.tsx
src/hooks/waste.tsx

fix(waste): the problem of autocomplete list not showing up on android

---

src/components/filter/Filter.tsx
src/components/screens/EventRecords.js
src/components/screens/Overviews.js
src/screens/ConstructionSiteOverviewScreen.js
src/screens/Noticeboard/NoticeboardIndexScreen.tsx
src/screens/SUE/SueListScreen.tsx

This PR allows the data to be displayed again in the list view in the SUE module and allows the data count display to be updated according to the filters made.
|without filter|with filter|
|--|--|
SUE-144

fix(sue): the problem of not showing data in list view

---

src/screens/HomeScreen.js

staticContentList has been removed from homeScreen because it was used in sueHomeScreen.
SVA-1473
|before|after|
|--|--|

refactor: remove unused static content logic and clean up imports

---

src/components/DropdownSelect.js
src/components/filter/DateFilter.tsx
src/components/filter/DropdownFilter.tsx
src/components/filter/Filter.tsx
src/components/filter/FilterComponent.tsx
src/components/widgets/EventWidget.tsx
src/config/navigation/defaultStackConfig.tsx
src/helpers/parser/listItemParser.js
src/hooks/listHooks.js

- introduced `isOverlayFilter` prop to `DropdownSelect`, `DropdownFilter`, and `FilterComponent` for better control of dropdown behavior
- updated `adjustFrame` according to `isOverlayFilter` to fix the problem of dropdown appearing above the `DropdownSelect` component shown in the overlay filter
SVA-1384
|before|after|
|--|--|

feat: add `isOverlayFilter` prop to `Dropdown` components

---

src/components/ImagesCarousel.js

- added start stop via `carouselRef` instead of the `isPaused` control in the return section to fix the problem of starting from the first image after the slider is paused and started
SVA-1384

fix: the problem in the slider that starts over when you want to pause

---

.github/scripts/eas-update.js
app.json
app.json.erb.tmpl
package.json
src/components/VersionNumber.js

New command `yarn update:all "EAS UPDATE MESSAGE` to make EAS Update more efficient with automatically incrementing a new `otaVersion` that will be shown in version number string to know about the latest version on devices.
GOS-105

release: add script for EAS Update

---

src/screens/SurveyDetailScreen.tsx

- ensure date components are only rendered if dates are present
- improves robustness of the `SurveyDetailScreen`

fix(survey): add conditional rendering for date components

---

src/config/navigation/tabConfig.tsx
src/navigation/MainTabNavigator.tsx
src/types/Navigation.ts

- introduced `tabBarLabelStyle` parameter in `createDynamicTabConfig`
- updated `MainTabNavigator` to utilize new `tabBarLabelStyle`
- modified `CustomTab` type to include `tabBarLabelStyle`
SVA-1531

feat(tab): add `tabBarLabelStyle` to tab configuration

---

src/components/Calendar.tsx
src/components/EventList.js
src/components/GroupedListItem.tsx
src/components/TextListItem.tsx
src/components/waste/WasteCollectionListItem.tsx
src/hooks/listHooks.js
src/screens/AppIntroScreen.tsx
src/screens/WebScreen.tsx

https://medium.com/welldone-software/why-did-you-render-mr-big-pure-react-component-2a36dd86996f

refactor: replace inline styles with style objects to reduce re-renderings

---

src/components/Calendar.tsx
src/components/VerticalList.js
src/components/screens/EventRecords.js
src/hooks/listHooks.js

This PR prevents multi-day events from repeating in the calendar view and updates the style of the sticky header.
SVASD-130
|before list view|after list view|before calendar view|after calendar view|
|--|--|--|--|

feat(event): remove dates from sub list in calendar view

---

src/config/texts.js
src/screens/Voucher/VoucherScannerScreen.tsx

- added a button to request camera permission if not granted
- updated texts for camera permission messages
- improved user experience in the VoucherScannerScreen
SVASD-176
|before|after|
|--|--|
https://github.com/user-attachments/assets/a919c15a-7bab-4020-b952-02e82189f1c8

feat(scanner): add camera permission request functionality

---

src/components/SUE/report/SueReportSend.tsx

- added `feedbackFormTexts` object to `SueReportSend` to add the ability to update the text in the feedback form at the end of the report page via the main server
SUE-165

feat(sue): make the feedback form updatable via main-server

---

src/components/SUE/report/SueReportLocation.tsx
src/components/map/Map.tsx
src/screens/SUE/SueMapViewScreen.tsx

Added border to increase the accessibility of this PR and to make the pin added to the map visible
|--|--|--|--|
SUE-165

feat(sue): update pin on report screen

---

src/components/map/MapLibre.tsx
src/screens/MapScreen.tsx
src/screens/MapViewScreen.js

This PR adds a button to switch to full screen map view to the maplibre component
SVA-1365

feat(map): integrate maplibre package into full screen map

---

src/components/map/MapLibre.tsx

With this PR, automatic address generation with pins added to the map and removal of the pin if the pin is not at the desired address has been added.
|mini map with pin and address|full screen map with selected pin|full screen map with alert (zone alert)|
|--|--|--|
SVA-1365

feat(map): add the ability to generate an address from the selected location

---

src/components/SUE/report/SueReportLocation.tsx
src/components/map/MapLibre.tsx
src/screens/SUE/SueMapViewScreen.tsx

|before|after|
|--|--|
SVA-1365

feat(map): simplify MarkerView usage and adjust callout margin

---

src/components/waste/WasteInputForm.tsx
src/config/texts.js
src/hooks/waste.tsx
src/queries/waste.js
src/screens/WasteCollectionScreen.js
src/screens/WasteCollectionSettingsScreen.tsx

This PR improves the performance of the waste calendar and fixes minor UI bugs
|--|--|--|--|
SVA-1539
SVA-1510

feat(waste): improve waste calendar performance

---

src/components/SUE/report/SueReportLocation.tsx
src/components/map/MapLibre.tsx
src/screens/SUE/SueMapScreen.tsx
src/screens/SUE/SueMapViewScreen.tsx

This PR solves the problem of not being able to add pins to the map and not being able to remove the added pin
SVA-1365

fix(map): the problem of not being able to add pins to the map

---

src/components/SUE/report/SueReportLocation.tsx
src/components/augmentedReality/AugmentedReality.js
src/components/map/MapLibre.tsx
src/components/screens/PointOfInterest.js
src/screens/MapScreen.tsx
src/screens/MapViewScreen.js
src/screens/SUE/SueDetailScreen.tsx
src/screens/SUE/SueMapScreen.tsx
src/screens/SUE/SueMapViewScreen.tsx

feat(map): return enhancements and align several code spots

---

src/config/texts.js
src/screens/volunteer/VolunteerRegistrationScreen.tsx
src/screens/volunteer/VolunteerSignupScreen.tsx

feat(volunteer): add texts to registration process

---

src/components/HtmlView.js
src/components/StorySection.js
src/components/screens/EventRecord.js
src/components/screens/PointOfInterest.js

|news intro|news description|event|poi|
|---|---|---|---|
|![Simulator Screenshot - iPhone 16 Pro Max - 2025-06-27 at 23 42 41](https://github.com/user-attachments/assets/b917a4f6-4085-485a-a0a4-1ca7595ff5e9)|![Simulator Screenshot - iPhone 16 Pro Max - 2025-06-27 at 23 42 44](https://github.com/user-attachments/assets/de36aa6d-4596-48db-b501-16dc25baec32)|![Simulator Screenshot - iPhone 16 Pro Max - 2025-06-27 at 23 44 16](https://github.com/user-attachments/assets/ea30bdd0-2210-4753-b755-51a989256555)|![Simulator Screenshot - iPhone 16 Pro Max - 2025-06-27 at 23 44 55](https://github.com/user-attachments/assets/a4c0a9cb-10dd-4e19-afdb-c80edac43a91)|
SVASD-223

feat: copy of descriptions in detail screens

---

src/components/Button.js
src/components/Image.js
src/components/ImageButton.tsx
src/components/ImagesCarousel.js
src/components/ImagesCarouselItem.js

This PR gives the button the invert button property with white border and adds the ability to add multiple buttons to the home carousel
If we want to show a button, the button object can be continued. But to add more than one button, buttons array should be added.
before: 
```
[
{
...
"button": {
"style": {
"big": false,
"disabled": false,
"iconColor": "white",
"iconPosition": "right",
"invert": false,
"noFullWidth": false,
"small": false,
"smallest": false
},
"routeName": "SueReport",
"iconName": "Plus",
"title": "Etwas melden",
"params": {}
}
}
]
```
after:
```
[
{
...
"buttons": [
{
"style": {
"big": false,
"disabled": false,
"iconColor": "white",
"iconPosition": "right",
"invert": false,
"noFullWidth": false,
"small": false,
"smallest": false
},
"routeName": "SueReport",
"iconName": …
```

feat: add button to carousel

---

src/pushNotifications/PermissionHandling.ts
src/pushNotifications/TokenHandling.ts

With this PR, it adds a warning to the user if there is no response from the server when turning the notification settings on or off
SVA-1644

feat(push): add server non response control
